### ISSUE TITLE
create-react-app, mixed content

### ISSUE THREAD

**Issue by snnwolf** [gitpod-io/gitpod#1005]
**Describe the bug**

Error in browser:
SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS

**To Reproduce**

- create new project with `npx create-react-app .`
- run `yarn start`

Trying use `react-app-rewired` for rewrite DevServer config FAILed.

[Project](https://github.com/snnwolf/bookhist.ui)
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/snnwolf/bookhist.ui)

**Additional Information**

`package.json`
```json
{
  "name": "app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}

```

devtool alarming with:
```[HMR] Waiting for update signal from WDS...
webpackHotDevClient.js:60 Mixed Content: The page at 'https://3000-e576231e-b896-48be-bd84-9c7418f41a68.ws-eu01.gitpod.io/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://3000-e576231e-b896-48be-bd84-9c7418f41a68.ws-eu01.gitpod.io/sockjs-node'. This request has been blocked; this endpoint must be available over WSS.
./node_modules/react-dev-utils/webpackHotDevClient.js @ webpackHotDevClient.js:60
webpackHotDevClient.js:60 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at Object../node_modules/react-dev-utils/webpackHotDevClient.js (https://3000-e576231e-b896-48be-bd84-9c7418f41a68.ws-eu01.gitpod.io/static/js/0.chunk.js:3874:18)
    at __webpack_require__ (https://3000-e576231e-b896-48be-bd84-9c7418f41a68.ws-eu01.gitpod.io/static/js/bundle.js:786:30)
    at fn (https://3000-e576231e-b896-48be-bd84-9c7418f41a68.ws-eu01.gitpod.io/static/js/bundle.js:151:20)
    at Object.1 (https://3000-e576231e-b896-48be-bd84-9c7418f41a68.ws-eu01.gitpod.io/static/js/main.chunk.js:355:1)
    at __webpack_require__ (https://3000-e576231e-b896-48be-bd84-9c7418f41a68.ws-eu01.gitpod.io/static/js/bundle.js:786:30)
    at checkDeferredModules (https://3000-e576231e-b896-48be-bd84-9c7418f41a68.ws-eu01.gitpod.io/static/js/bundle.js:46:23)
    at Array.webpackJsonpCallback [as push] (https://3000-e576231e-b896-48be-bd84-9c7418f41a68.ws-eu01.gitpod.io/static/js/bundle.js:33:19)
    at https://3000-e576231e-b896-48be-bd84-9c7418f41a68.ws-eu01.gitpod.io/static/js/main.chunk.js:1:59```

Could you help me with advice?

**Comment by svenefftinge** [comment]
create-react-app has hardcoded the protocol to be `ws` rather than checking if it is `https` and then use `wss`. But they have fixed that already, so will lang in the next release https://github.com/facebook/create-react-app/commit/9f4cb4f0c0ed280fcd6c9faf13ebe2619a398942#diff-5166b8ed2c51bdab6a247a95b14ff595

**Comment by svenefftinge** [comment]
Applying [this comment](https://github.com/facebook/create-react-app/pull/8079#issuecomment-562373869) will make it work in the meantime

**Comment by snnwolf** [comment]
@svenefftinge thanks. It works!!!
