### ISSUE TITLE
GitHub.vscode-pull-request-github is outdated

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/gitpod#10072]
### Bug description

Starting a PR review or commenting on PR from Gitpod web VSCODE does not work.

Logs:
```
[[object Object]]Extension 'GitHub.vscode-pull-request-github' CANNOT use API proposal: commentsResolvedState.
Its package.json#enabledApiProposals-property declares: tokenInformation but NOT commentsResolvedState.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.vscode-pull-request-github mainThreadExtensionService.ts:79:10
Error: Extension 'GitHub.vscode-pull-request-github' CANNOT use API proposal: commentsResolvedState.
Its package.json#enabledApiProposals-property declares: tokenInformation but NOT commentsResolvedState.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api GitHub.vscode-pull-request-github
	at f (/ide/out/vs/workbench/api/node/extensionHostProcess.js:81:64186)
	at f.get state [as state] (/ide/out/vs/workbench/api/node/extensionHostProcess.js:83:56537)
	at Object.get state [as state] (/ide/out/vs/workbench/api/node/extensionHostProcess.js:83:55390)
	at Ya (/workspace/.vscode-remote/extensions/github.vscode-pull-request-github-0.42.0/dist/extension.js:1144:1456)
	at ef.updateCommentThreadComments (/workspace/.vscode-remote/extensions/github.vscode-pull-request-github-0.42.0/dist/extension.js:1174:26747)
	at ef.optimisticallyAddComment (/workspace/.vscode-remote/extensions/github.vscode-pull-request-github-0.42.0/dist/extension.js:1174:26647)
	at ef.startReview (/workspace/.vscode-remote/extensions/github.vscode-pull-request-github-0.42.0/dist/extension.js:1174:25669)
	at /workspace/.vscode-remote/extensions/github.vscode-pull-request-github-0.42.0/dist/extension.js:1185:6841
	at o._executeContributedCommand (/ide/out/vs/workbench/api/node/extensionHostProcess.js:83:31333)
	at o.$executeContributedCommand (/ide/out/vs/workbench/api/node/extensionHostProcess.js:83:32037)
	at s._doInvokeHandler (/ide/out/vs/workbench/api/node/extensionHostProcess.js:86:13828)
	at s._invokeHandler (/ide/out/vs/workbench/api/node/extensionHostProcess.js:86:13512)
	at s._receiveRequest (/ide/out/vs/workbench/api/node/extensionHostProcess.js:86:12173)
	at s._receiveOneMessage (/ide/out/vs/workbench/api/node/extensionHostProcess.js:86:10843)
	at /ide/out/vs/workbench/api/node/extensionHostProcess.js:86:8949
	at m.invoke (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.deliver (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
	at v.fire (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
	at l.fire (/ide/out/vs/workbench/api/node/extensionHostProcess.js:66:19001)
	at /ide/out/vs/workbench/api/node/extensionHostProcess.js:102:34426
	at m.invoke (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.deliver (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
	at v.fire (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
	at l.fire (/ide/out/vs/workbench/api/node/extensionHostProcess.js:66:19001)
	at r._receiveMessage (/ide/out/vs/workbench/api/node/extensionHostProcess.js:66:23582)
	at /ide/out/vs/workbench/api/node/extensionHostProcess.js:66:21116
	at m.invoke (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.deliver (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
	at v.fire (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
	at v.acceptChunk (/ide/out/vs/workbench/api/node/extensionHostProcess.js:66:15832)
	at /ide/out/vs/workbench/api/node/extensionHostProcess.js:66:14962
	at m.invoke (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
	at w.deliver (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:2265)
	at v.fire (/ide/out/vs/workbench/api/node/extensionHostProcess.js:58:1843)
	at f._processReadQueue (/ide/out/vs/workbench/api/node/extensionHostProcess.js:102:21280)
```

### Steps to reproduce

- Open a PR from Github.
- Add a comment on a changed file.
- Check if the comment was added on the PR on github.com

### Anything else?

For more context please see:
- https://discord.com/channels/816244985187008514/816246578594840586/974281814942310451
- https://discord.com/channels/816244985187008514/931200235601023016/976128541211107370

cc @smacintyre

**Comment by jeanp413** [comment]
Thanks for reporting this @axonasif, this is fixed in production now
