### ISSUE TITLE
[Rust] Language Server breaks

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#101]
The Rust support initially works nicely, but then stops working.
I see the following in the output:
```
[Error - 10:08:57] Request completionItem/resolve failed.
Error: data did not match any variant of untagged enum Documentation
at new t (https://cdn.gitpod.io/theia/bundle-8fb9800bd1b57f776710643582d55a93.js:57:524287)
at https://cdn.gitpod.io/theia/bundle-8fb9800bd1b57f776710643582d55a93.js:12:171494
at https://cdn.gitpod.io/theia/bundle-8fb9800bd1b57f776710643582d55a93.js:12:171788
at https://cdn.gitpod.io/theia/bundle-8fb9800bd1b57f776710643582d55a93.js:12:172147
at https://cdn.gitpod.io/theia/bundle-8fb9800bd1b57f776710643582d55a93.js:91:48351
at u (https://cdn.gitpod.io/theia/bundle-8fb9800bd1b57f776710643582d55a93.js:91:48461)
at n (https://cdn.gitpod.io/theia/bundle-8fb9800bd1b57f776710643582d55a93.js:91:47412)
```

**Comment by svenefftinge** [comment]
Afterwards no request gets a response anymore

**Comment by svenefftinge** [comment]
I tested with http://gitpod.io#https://github.com/BookOwl/snake-rs

**Comment by svenefftinge** [comment]
Fixed it in https://github.com/theia-ide/theia-rust-extension/pull/9
