### ISSUE TITLE
Can see "configure Gitpod App" even though I am using an oauth for my self-hosted installation

### ISSUE THREAD

**Issue by lucasvaltl** [gitpod-io/gitpod#10355]
### Bug description

When I try to create a project on a self-hosted installation (Created with the [GKE guide](https://github.com/gitpod-io/gitpod-gke-guide)), I see "configure gitpod app" even though I am not using a github.com oauth app as a way to link my github to gitpod, but rather oauth. 

This _seems_ to be a bug - it shows me the following error upon opening the pop up window where you would grant Github permissions:

> {"error":"Error: unhandled request: GET /apps/github/reconfigure?account=undefined&state=eyJmcm9tIjoiL3JlY29uZmlndXJlIiwibmV4dCI6Ii9uZXcifQ%3D%3D\nStack: Error: unhandled request: GET /apps/github/reconfigure?account=undefined&state=eyJmcm9tIjoiL3JlY29uZmlndXJlIiwibmV4dCI6Ii9uZXcifQ%3D%3D\n    at unhandledToError (/app/node_modules/@gitpod/server/dist/src/express-util.js:127:17)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:323:13)\n    at /app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)\n    at next (/app/node_modules/express/lib/router/index.js:275:10)\n    at /app/node_modules/express/lib/router/index.js:641:15\n    at next (/app/node_modules/express/lib/router/index.js:260:14)\n    at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)\n    at router (/app/node_modules/express/lib/router/index.js:47:12)\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:323:13)\n    at /app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:341:12)\n    at next (/app/node_modules/express/lib/router/index.js:275:10)\n    at /app/node_modules/express/lib/router/index.js:641:15"}

### Steps to reproduce

Walk through via loom: https://www.loom.com/share/1fe4a58f42994d0c98719c500a2d814f

1. Spin up self hosted instance
2. Connect to github.com using oauth
3. try to create a project 
4. (I think this is what happened) give permissions via github
5. press configure Gitpod App
6. See error 
--> Happy to give access to the dummy github account used here.

**Comment by geropl** [comment]
I don't think this is the case anymore, but we need somebody to validate that.

**Comment by lucasvaltl** [comment]
I believe this is fixed - have not run into this when creating a project in the last two months.
