### ISSUE TITLE
Can't connect to remote MS SQL SERVER

### ISSUE THREAD

**Issue by malizia-g** [gitpod-io/gitpod#1037]
Hello,
I'm trying to connect with Express to a remote MSSQL SERVER. I'm shure the server is accepting remote connections.
If I try this code from my laptop everything works fine (the sql server is not hosted localy on my laptop)

```
var express = require('express');
var router = express.Router();
const sql = require('mssql')

const config = {
  user: 'xxxx',  //user name
  password: 'xxx', //password
  server: "my-connection-string",  //connection string
  database: 'xxxx', //(Nome del DB)
}

/* GET users listing. */
router.get('/', function(req, res, next) {
  sql.connect(config, err => {
    if(err) console.log(err);  // ... error check
    
    // Query
    let sqlRequest = new sql.Request();  //Oggetto che serve a creare le query
    sqlRequest.query('select * from dbo.[cr-unit-attributes]', (err, result) => {
        if (err) console.log(err); // ... error checks
        res.send(result);  //Invio il risultato
    });
  });
});
```

But if I try from gitpod I get this error:

```
{ ConnectionError: Connection is closed.
    at Request._query (/workspace/sql-clash-rest-crud/node_modules/mssql/lib/base/request.js:447:37)
    at Request._query (/workspace/sql-clash-rest-crud/node_modules/mssql/lib/tedious/request.js:346:11)
    at Request.query (/workspace/sql-clash-rest-crud/node_modules/mssql/lib/base/request.js:383:12)
    at Immediate.sql.connect.err (/workspace/sql-clash-rest-crud/routes/users.js:19:16)
    at runCallback (timers.js:706:11)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5) code: 'ECONNCLOSED', name: 'ConnectionError' }
GET /users 200 6.172 ms - -
{ ConnectionError: Failed to connect to < in 15000msmy-connection-string>
    at Connection.tedious.once.err (/workspace/sql-clash-rest-crud/node_modules/mssql/lib/tedious/connection-pool.js:68:17)
    at Object.onceWrapper (events.js:286:20)
    at Connection.emit (events.js:198:13)
    at Connection.connectTimeout (/workspace/sql-clash-rest-crud/node_modules/tedious/lib/connection.js:1190:10)
    at Timeout.connectTimer.setTimeout [as _onTimeout] (/workspace/sql-clash-rest-crud/node_modules/tedious/lib/connection.js:1152:12)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  code: 'ETIMEOUT',
  originalError:
```
   

Thank you!

Fabio

**Comment by JesterOrNot** [comment]
@malizia-g Do you have access to the device in which the server runs if so you can probably hook it up via Inlets see https://www.gitpod.io/blog/local-services-in-gitpod/
Or if that does not work I bet self-hosting could work see https://www.gitpod.io/blog/self-host-your-gitpod/

**Comment by malizia-g** [comment]
Thank you very mutch for your reply, you provided me some really interesting informations.
But those are not solving my problem:
- No I don't have access to the server device.
- At the moment I can't self host gitpod. 
(I'm a teacher and my students are using gipod. But we need to connect to the school server DB).
As I wrote, I can reach the DB remotely from my laptop using the same code, so I can't figure what could be the problem.

**Comment by svenefftinge** [comment]
@geropl could you take a look at this one?

**Comment by malizia-g** [comment]
Does anyone has a clue?
I also tried to install the mssql extension for visual studio code....
But I still can't reach the server ....

**Comment by jankeromnes** [comment]
Are you able to ping `my-connection-string` from your laptop but not from Gitpod? (This could indicate a firewall block of some kind.)

Also, please make sure the connection users TCP and not UDP (the latter currently doesn't work on Gitpod).

**Comment by malizia-g** [comment]
Thanks for your reply.
How can I ping from gitpod? The command is not available from the command line
