### ISSUE TITLE
Can't get workspace running on local VS Code

### ISSUE THREAD

**Issue by M-Gonzalo** [gitpod-io/gitpod#10477]
### Bug description

I consistently get an error while trying to open my Bitbucket workspaces with my local copy of VS Code (they work on the web editor, though). Github repos are working fine.

Log:
```
[Info  - 23:55:51.811] Reading sessions from keychain...
[Info  - 23:57:11.327] Opening Gitpod workspace
vscode://gitpod.gitpod-desktop/workspace/*****************
[Info  - 23:57:11.359] acquiring lock: gitpod.io
[Info  - 23:57:11.600] acquired lock: gitpod.io
[Info  - 23:57:11.605] fetching the local app from https://gitpod.io/static/bin/gitpod-local-companion-linux
[Info  - 23:57:13.414] released lock: gitpod.io
[Error  - 23:57:13.754] failed to access the local app: Error: workspace not found
[Error  - 23:57:13.760] Failed to connect /***************** Gitpod workspace
Error: workspace not found
    at Object.onEnd (/home//*****************/.vscode/extensions/gitpod.gitpod-desktop-0.0.37/dist/extension.js:2:39099)
    at /home//*****************/.vscode/extensions/gitpod.gitpod-desktop-0.0.37/dist/extension.js:2:83511
    at /home//*****************/.vscode/extensions/gitpod.gitpod-desktop-0.0.37/dist/extension.js:2:70831
    at Array.forEach (<anonymous>)
    at e.rawOnError (/home//*****************/.vscode/extensions/gitpod.gitpod-desktop-0.0.37/dist/extension.js:2:70793)
    at e.onTransportHeaders (/home//*****************/.vscode/extensions/gitpod.gitpod-desktop-0.0.37/dist/extension.js:2:68370)
    at e.responseCallback (/home//*****************/.vscode/extensions/gitpod.gitpod-desktop-0.0.37/dist/extension.js:2:58475)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:390:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at Socket.socketOnData (node:_http_client:487:22)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)

```

### Steps to reproduce

Open a bitbucket workspace (it works on the web editor) and try to open it with local VS Code

**Comment by geropl** [comment]
According to @jeanp413 [this call](https://github.com/gitpod-io/gitpod-vscode-desktop/blob/ca0c978032d1da2e6bcd8b6a058b98d5608a7c00/src/remoteConnector.ts#L426) fails when retrieving the workspace from local VSCode. Works for a GitHub repo, but fails for a BitBucket one.

**Comment by jeanp413** [comment]
@M-Gonzalo  could you try the following and let me know if that works or not :pray: 
- update your vscode settings.json with `"gitpod.remote.useLocalApp": false` or install the pre-release version of `gitpod-desktop` extension
- configuring your [ssh keys in Gitpod](https://gitpod.io/keys) before trying to connect again 

![image](https://user-images.githubusercontent.com/25115070/179345479-c330312f-db0c-461a-9314-ff6c4a74d7b9.png)

**Comment by mustard-mh** [comment]
I'll close this issue, feel free to re-open it if it happens again

**Comment by M-Gonzalo** [comment]
> @M-Gonzalo could you try the following and let me know if that works or not pray
> 
>     * update your vscode settings.json with `"gitpod.remote.useLocalApp": false` or install the pre-release version of `gitpod-desktop` extension
> 
>     * configuring your [ssh keys in Gitpod](https://gitpod.io/keys) before trying to connect again
> 
> 
> ![image](https://user-images.githubusercontent.com/25115070/179345479-c330312f-db0c-461a-9314-ff6c4a74d7b9.png)

My man, this issue is two months old. I had to move on, didn't have any choice.
I won't be testing this since I have no use for Gitpod right now.
