### ISSUE TITLE
[Excalidraw Extension] Blank custom editor in VSCode Browser

### ISSUE THREAD

**Issue by pomdtr** [gitpod-io/gitpod#10523]
### Bug description

The excalidraw custom editor does not display properly in gitpod. 
However, it works fine in `github.dev`, `github codespaces` and `vscode`.

### Steps to reproduce

- Open the [excalidraw-vscode](https://github.com/excalidraw/excalidraw-vscode) repository in gitpod
- Install the [excalidraw extension](https://open-vsx.org/extension/pomdtr/excalidraw-editor)
- Open the `examples/text.excalidraw` file

### Workspace affected

excalidraw-excalidrawvs-bs2w57wmia6.ws-eu47.gitpod.io

### Expected behavior

On github.dev, the test.excalidraw file is shown:

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/17577332/172569796-22c21acf-a2d8-4b6e-9d90-d02a3cc325bc.png">

### Example repository

https://github.com/excalidraw/excalidraw-vscode

**Comment by filiptronicek** [comment]
Hi @pomdtr 👋, thanks for raising the issue. I can reproduce this and it seems like there is an error in the activation of the extension. I'll dig deeper, but this log is so far what I've got:

```
[2022-06-08 17:35:44.238] [exthost] [info] Extension host started
[2022-06-08 17:35:44.902] [exthost] [info] ExtensionService#_doActivateExtension pomdtr.excalidraw-editor, startup: true, activationEvent: 'workspaceContains:**/*.{excalidraw,excalidraw.svg,excalidraw.png}'
[2022-06-08 17:35:44.973] [exthost] [error] Activating extension pomdtr.excalidraw-editor failed due to an error:
[2022-06-08 17:35:45.016] [exthost] [error] Error: 
	at O._loadCommonJSModule (../../../vs/workbench/api/worker/extensionHostWorker.js:75:63362)
	at async Promise.all (index 0)
	at async f._activate (../../../vs/workbench/api/worker/extensionHostWorker.js:69:8180)
	at async f._waitForDepsThenActivate (../../../vs/workbench/api/worker/extensionHostWorker.js:69:8122)
	at async f._initialize (../../../vs/workbench/api/worker/extensionHostWorker.js:69:7486)
```

**Comment by jeanp413** [comment]
I also took a look, it seems it's an openvsx bug, I created an issue upstream https://github.com/eclipse/openvsx/issues/468

**Comment by veepdotai** [comment]
I have this bug. It still exists. It's annoynig because excalidraw ia a very useful tool and that could be a reason to go and see gitpod competitors.
