### ISSUE TITLE
Django server issue

### ISSUE THREAD

**Issue by LeVlad** [gitpod-io/gitpod#11364]
### Bug description

I have installed Django with allauth, psycopg2-binary, dj-database-url and gunicorn and can't seem to make "python3 manage.py runserver" work.

### Steps to reproduce

opened gitpod
saw that yet again the requirements were not saved and started to re-install the packages
1.pip3 install Django==3.2
2.pip3 install django-allauth==0.41.0
3.pip3 install dj_database_url psycopg2
4.pip3 install gunicorn
5. python3 manage.py runserver

### Workspace affected

https://levlad-stoicshirts-60ny0znp5sd.ws-eu54.gitpod.io/

### Expected behavior

....server successfully created at ...

### Example repository

gitpod /workspace/StoicShirts (main) $ python3 manage.py makemigrations
/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py:105: RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': connection to server at "ec2-3-248-121-12.eu-west-1.compute.amazonaws.com" (3.248.121.12), port 5432 failed: FATAL:  password authentication failed for user "tbkjdbabdcnidp"
connection to server at "ec2-3-248-121-12.eu-west-1.compute.amazonaws.com" (3.248.121.12), port 5432 failed: FATAL:  no pg_hba.conf entry for host "34.140.245.112", user "tbkjdbabdcnidp", database "daqug9935cmjj1", no encryption

  warnings.warn(
No changes detected
gitpod /workspace/StoicShirts (main) $ python3 manage.py migrate
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "ec2-3-248-121-12.eu-west-1.compute.amazonaws.com" (3.248.121.12), port 5432 failed: FATAL:  password authentication failed for user "tbkjdbabdcnidp"
connection to server at "ec2-3-248-121-12.eu-west-1.compute.amazonaws.com" (3.248.121.12), port 5432 failed: FATAL:  no pg_hba.conf entry for host "34.140.245.112", user "tbkjdbabdcnidp", database "daqug9935cmjj1", no encryption

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/models/base.py", line 1290, in check
    *cls._check_indexes(databases),
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/models/base.py", line 1680, in _check_indexes
    connection.features.supports_covering_indexes or
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/postgresql/features.py", line 93, in is_postgresql_11
    return self.connection.pg_version >= 110000
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 329, in pg_version
    with self.temporary_connection():
  File "/home/gitpod/.pyenv/versions/3.8.11/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 603, in temporary_connection
    with self.cursor() as cursor:
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "ec2-3-248-121-12.eu-west-1.compute.amazonaws.com" (3.248.121.12), port 5432 failed: FATAL:  password authentication failed for user "tbkjdbabdcnidp"
connection to server at "ec2-3-248-121-12.eu-west-1.compute.amazonaws.com" (3.248.121.12), port 5432 failed: FATAL:  no pg_hba.conf entry for host "34.140.245.112", user "tbkjdbabdcnidp", database "daqug9935cmjj1", no encryption

gitpod /workspace/StoicShirts (main) $ python3 manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "ec2-3-248-121-12.eu-west-1.compute.amazonaws.com" (3.248.121.12), port 5432 failed: FATAL:  password authentication failed for user "tbkjdbabdcnidp"
connection to server at "ec2-3-248-121-12.eu-west-1.compute.amazonaws.com" (3.248.121.12), port 5432 failed: FATAL:  no pg_hba.conf entry for host "34.140.245.112", user "tbkjdbabdcnidp", database "daqug9935cmjj1", no encryption

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/3.8.11/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/gitpod/.pyenv/versions/3.8.11/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check_migrations()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/core/management/base.py", line 486, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/migrations/loader.py", line 53, in __init__
    self.build_graph()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/migrations/loader.py", line 220, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
    if self.has_table():
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 55, in has_table
    with self.connection.cursor() as cursor:
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 187, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "ec2-3-248-121-12.eu-west-1.compute.amazonaws.com" (3.248.121.12), port 5432 failed: FATAL:  password authentication failed for user "tbkjdbabdcnidp"
connection to server at "ec2-3-248-121-12.eu-west-1.compute.amazonaws.com" (3.248.121.12), port 5432 failed: FATAL:  no pg_hba.conf entry for host "34.140.245.112", user "tbkjdbabdcnidp", database "daqug9935cmjj1", no encryption

### Anything else?

How come all of a sudden the packages we install in Gitpod do not stay installed?

**Comment by samuel025** [comment]
try deleting your database and migrations folder. Then migrate and run
