### ISSUE TITLE
rustlang: datatype helper?

### ISSUE THREAD

**Issue by Kreyren** [gitpod-io/gitpod#1200]
Apparently jetbrains products have a helper that outputs datatypes of rustlang in the editor:
![image](https://user-images.githubusercontent.com/11302521/74023584-489c0180-49a0-11ea-986b-c0c3fb4105d5.png)

Is there a way to get this in gitpod? I believe that it would help a lot with a development especially for new developers to understand the language better.

Relevant plugin: https://plugins.jetbrains.com/plugin/8182-rust

**Comment by Kreyren** [comment]
Relevant https://github.com/rust-lang/rls-vscode/issues/374

**Comment by svenefftinge** [comment]
It should be implemented in the rust vs code extension.

**Comment by Kreyren** [comment]
@svenefftinge can't confirm on my end

**Comment by Kreyren** [comment]
PSA As referrenced on https://github.com/rust-lang/rls-vscode/issues/374#issuecomment-583472960 this is apparently implemented in `rust-analyzer` extension (https://github.com/rust-analyzer/rust-analyzer) which requires compilation to be imported on the vscode which results in following on gitpod:

```
gitpod /workspace/rustlang-fibonacci/rust-analyzer $ cargo xtask install
    Finished dev [unoptimized] target(s) in 0.06s
     Running `target/debug/xtask install`

will run: cargo --version
cargo 1.41.0 (626f0f40e 2019-12-03)

will run: cargo install --path crates/ra_lsp_server --locked --force
  Installing ra_lsp_server v0.1.0 (/workspace/rustlang-fibonacci/rust-analyzer/crates/ra_lsp_server)
    Updating crates.io index
    Finished release [optimized] target(s) in 0.62s
   Replacing /workspace/.cargo/bin/ra_lsp_server
    Replaced package `ra_lsp_server v0.1.0 (/workspace/rustlang-fibonacci/rust-analyzer/crates/ra_lsp_server)` with `ra_lsp_server v0.1.0 (/workspace/rustlang-fibonacci/rust-analyzer/crates/ra_lsp_server)` (executable `ra_lsp_server`)

will run: npm --version
6.13.7

will run: npm install
audited 199 packages in 2.902s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


will run: npm run package --scripts-prepend-node-path

> rust-analyzer@0.1.0 package /workspace/rustlang-fibonacci/rust-analyzer/editors/code
> vsce package

Executing prepublish script 'npm run vscode:prepublish'...

> rust-analyzer@0.1.0 vscode:prepublish /workspace/rustlang-fibonacci/rust-analyzer/editors/code
> tsc && rollup -c


out/main.js → ./out/main.js...
(!) Mixing named and default exports
https://rollupjs.org/guide/en/#output-exports
The following entry modules are using named and default exports together:
out/main.js

Consumers of your bundle will have to use chunk['default'] to access their default export, which may not be what you want. Use `output.exports: 'named'` to disable this warning
created ./out/main.js in 2.7s
 DONE  Packaged: /workspace/rustlang-fibonacci/rust-analyzer/editors/code/rust-analyzer-0.1.0.vsix (6 files, 139.01KB)
 INFO  
The latest version of vsce is 1.73.0 and you have 1.71.0.
Update it now: npm install -g vsce

will run: code --version

will run: code-insiders --version

will run: codium --version

will run: code-oss --version
Error: install client

Caused by:
    Can't execute `code --version`. Perhaps it is not in $PATH?
```

**Comment by Kreyren** [comment]
WIP contribution to rls-vscode also have this issue on gitpod 

```
gitpod /workspace/rls-vscode $ npm run installDevExtension

> rust@0.7.0 installDevExtension /workspace/rls-vscode
> npm install && ./node_modules/.bin/vsce package -o ./out/rls-vscode-dev.vsix && code --install-extension ./out/rls-vscode-dev.vsix

up to date in 11.565s
Executing prepublish script 'npm run vscode:prepublish'...

> rust@0.7.0 vscode:prepublish /workspace/rls-vscode
> npm run check:version && npm run lint && npm run compile


> rust@0.7.0 check:version /workspace/rls-vscode
> node cmd/check-version.js


> rust@0.7.0 lint /workspace/rls-vscode
> tslint --config ./tslint.json './src/**/*.ts'


> rust@0.7.0 compile /workspace/rls-vscode
> tsc -p ./

 DONE  Packaged: /workspace/rls-vscode/out/rls-vscode-dev.vsix (85 files, 157.23KB)
 WARNING  
The latest version of vsce is 1.73.0 and you have 1.64.0.
Update it now: npm install -g vsce
sh: 1: code: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! rust@0.7.0 installDevExtension: `npm install && ./node_modules/.bin/vsce package -o ./out/rls-vscode-dev.vsix && code --install-extension ./out/rls-vscode-dev.vsix`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the rust@0.7.0 installDevExtension script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2020-02-13T16_12_36_710Z-debug.log
```

**Comment by Kreyren** [comment]
Setting executable `code` that returns `exit 0` fixes the issue on vscode-rls

**Comment by Kreyren** [comment]
FWIW the rust-analyzer also fails with what i assume is interference from built-in extension

![image](https://user-images.githubusercontent.com/11302521/74458888-a8a41380-4e8a-11ea-9621-7833cda8c5ea.png)

**Comment by Kreyren** [comment]
FWIW: Rust analyzer is now available as official vscode extension

Tried to implement it with required datatype helper on https://github.com/RXT0112/Zernit/tree/6ceaff2979918b85654a9397072b8e97408cdab6

which results in:

```
[Error - 9:46:02 PM] Notify file events failed.
TypeError: vscode.languages.registerSelectionRangeProvider is not a function
    at SelectionRangeFeature.registerLanguageProvider (/tmp/vscode-extensions/matklad.rust-analyzer@0.1.20200217/extension/out/main.js:11669:34)
    at SelectionRangeFeature.register (/tmp/vscode-extensions/matklad.rust-analyzer@0.1.20200217/extension/out/main.js:9261:33)
    at SelectionRangeFeature.initialize (/tmp/vscode-extensions/matklad.rust-analyzer@0.1.20200217/extension/out/main.js:11647:14)
    at LanguageClient.initializeFeatures (/tmp/vscode-extensions/matklad.rust-analyzer@0.1.20200217/extension/out/main.js:11014:21)
    at connection.initialize.then (/tmp/vscode-extensions/matklad.rust-analyzer@0.1.20200217/extension/out/main.js:10699:18)
```

**Comment by Kreyren** [comment]
ping @JesterOrNot Can you take a look at this and approve for transfer if this is a theia bug so that i am not flooding their bug tracker with something that might be a gitpod bug? ^-^

**Comment by svenefftinge** [comment]
Yes, seems like we need to implement that API in Theia. Could you open a ticket there?

**Comment by leo-lb** [comment]
Another API missing: https://github.com/eclipse-theia/theia/issues/7608

**Comment by Kreyren** [comment]
It seems to be implemented now ^-^

![](https://i.imgur.com/UZ7VXk5.png)

Assuming solved
