### ISSUE TITLE
[ws-daemon] panics with `integer divide by zero` err

### ISSUE THREAD

**Issue by Pothulapati** [gitpod-io/gitpod#12295]
### Bug description

ws-daemon seems to have randomly panic'ed with the following logs

```
panic: runtime error: integer divide by zero

goroutine 20657432 [running]:
github.com/gitpod-io/gitpod/ws-daemon/pkg/iws.getCpuResourceInfoV2({0xc0002a9020?, 0xc1d919dd40?}, {0xc0926d0540?, 0x12bbdf3?})
	github.com/gitpod-io/gitpod/ws-daemon/pkg/iws/iws.go:1121 +0x1b2
github.com/gitpod-io/gitpod/ws-daemon/pkg/iws.getWorkspaceResourceInfo({0xc0002a9020, 0x11}, {0xc0926d0540, 0xbf}, 0x24?)
	github.com/gitpod-io/gitpod/ws-daemon/pkg/iws/iws.go:1055 +0x3a
github.com/gitpod-io/gitpod/ws-daemon/pkg/iws.(*InWorkspaceServiceServer).WorkspaceInfo(0xc135bde460, {0x2321520, 0xc02a409bf0}, 0xc02a409c20?)
	github.com/gitpod-io/gitpod/ws-daemon/pkg/iws/iws.go:1042 +0x8b6
github.com/gitpod-io/gitpod/ws-daemon/api._InWorkspaceService_WorkspaceInfo_Handler.func1({0x2321520, 0xc02a409bf0}, {0x1db82c0?, 0xc02a409c20})
	github.com/gitpod-io/gitpod/ws-daemon/api@v0.0.0-00010101000000-000000000000/workspace_daemon_grpc.pb.go:432 +0x78
github.com/gitpod-io/gitpod/ws-daemon/pkg/iws.ratelimitingInterceptor.UnaryInterceptor.func1({0x2321520, 0xc02a409bf0}, {0x1db82c0, 0xc02a409c20}, 0xc02f24c660, 0xc1f44fdbd8)
	github.com/gitpod-io/gitpod/ws-daemon/pkg/iws/iws.go:1349 +0x2e6
github.com/gitpod-io/gitpod/ws-daemon/api._InWorkspaceService_WorkspaceInfo_Handler({0x1ef5e20?, 0xc135bde460}, {0x2321520, 0xc02a409bf0}, 0xc1d919dce0, 0xc14c5d6600)
	github.com/gitpod-io/gitpod/ws-daemon/api@v0.0.0-00010101000000-000000000000/workspace_daemon_grpc.pb.go:434 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc01c29c540, {0x2329680, 0xc003f67040}, 0xc1a1b0d680, 0xc0b941f9e0, 0x32aba18, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc01c29c540, {0x2329680, 0xc003f67040}, 0xc1a1b0d680, 0x0)
	google.golang.org/grpc@v1.45.0/server.go:1619 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.45.0/server.go:919 +0x28a
```

### Steps to reproduce

https://gitpod.slack.com/archives/C01TNS8EVQT/p1661236784773649

**Comment by kylos101** [comment]
@Pothulapati :wave: I hope you are well! :bulb:  Tip: when creating issues, I recommend adding the team's related project. Why? This is a signal that the issue is being added to their inbox, and requires investigation. In the case of Team Workspace, we also have a Zapier Zap that notifies us via Slack when such issues are added to our inbox (which is super convenient for me as an EM).

**Comment by kylos101** [comment]
:wave: @Furisto do you have bandwidth to :eyes: at this today? It's a "nice to have" for `gen63`.
