### ISSUE TITLE
Opencv error

### ISSUE THREAD

**Issue by knshkp** [gitpod-io/gitpod#13062]
### Bug description

Yeah when i were installed opencv on gitpod and when I use it to some project by imported the cv2 so then it give me the imported error 

2022-09-19 03:11:38.703 Uncaught app exception
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "/workspace/VibeIt/music.py", line 4, in <module>
    import cv2
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory 

### Steps to reproduce

Yeah am reproducing by taking all the packages of open-cv and deploy in the gitpod repo so am resolving like this may I resolve this issue
 

### Workspace affected

https://knshkp-vibeit-w42vheg6nth.ws-us65.gitpod.io/

### Expected behavior

Yeah actually am want to see it installed it correctly and am installing both the type by opencv python and opencv-contrib-python

### Example repository

2022-09-19 03:11:38.703 Uncaught app exception
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "/workspace/VibeIt/music.py", line 4, in <module>
    import cv2
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/home/gitpod/.pyenv/versions/3.8.13/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### Anything else?

Plss as soon as possible resolve this issue bcoz i know github is very active organisation

**Comment by axonasif** [comment]
From your error logs, this is probably where it's all failing:
```
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

Gitpod does not provide GPUs for now. However, you might be able to workaround this by installing `libgl1`:

```bash
sudo apt install libgl1
```

Even if opencv works with it, remember that it's going to be software acceleration but not hardware, so the computation performance will be noticeably slow.
