### ISSUE TITLE
Can't connect. SSH closes connection.

### ISSUE THREAD

**Issue by julienmarie** [gitpod-io/gitpod#13266]
### Bug description

Can't connect via VS Code Desktop or SSH.

VSCode Logs:
```[11:53:30.558] SSH Resolver called for "ssh-remote+7b2275736572223a226a756c69656e6d617269652d626f6e6f626f6f6d2d6262316d39356164356268222c22686f73744e616d65223a226a756c69656e6d617269652d626f6e6f626f6f6d2d6262316d393561643562682e7373682e77732d757336382e676974706f642e696f227d", attempt 5, (Reconnection)
[11:53:30.560] SSH Resolver called for host: julienmarie-bonoboom-bb1m95ad5bh@julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io
[11:53:30.560] Setting up SSH remote "julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io"
[11:53:30.561] Acquiring local install lock: /var/folders/5g/bgymj_dd441d7r8plqj8dwp80000gn/T/vscode-remote-ssh-859c4d9b-install.lock
[11:53:30.562] Looking for existing server data file at /Users/julienmarie/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-859c4d9b-74b1f979648cc44d385a2286793c226e611f59e7-0.84.0/data.json
[11:53:30.562] Using commit id "74b1f979648cc44d385a2286793c226e611f59e7" and quality "stable" for server
[11:53:30.563] Install and start server if needed
[11:53:30.567] askpass server listening on /var/folders/5g/bgymj_dd441d7r8plqj8dwp80000gn/T/vscode-ssh-askpass-27a7459997255f9693f31433717094e20fd70636.sock
[11:53:30.568] Spawning local server with {"serverId":5,"ipcHandlePath":"/var/folders/5g/bgymj_dd441d7r8plqj8dwp80000gn/T/vscode-ssh-askpass-7db0d2d98a0865a76791ce9de2ec5ee213e87687.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52395","-o","ConnectTimeout=15","julienmarie-bonoboom-bb1m95ad5bh@julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/julienmarie/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-859c4d9b-74b1f979648cc44d385a2286793c226e611f59e7-0.84.0/data.json"}
[11:53:30.568] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.8SjVqJalVr/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/5g/bgymj_dd441d7r8plqj8dwp80000gn/T/vscode-ssh-askpass-27a7459997255f9693f31433717094e20fd70636.sock"}
[11:53:30.569] Spawned 96038
[11:53:30.695] > local-server-5> Spawned ssh, pid=96054
[11:53:30.745] stderr> OpenSSH_7.9p1, LibreSSL 2.7.3
[11:53:31.359] stderr> debug1: Server host key: ecdsa-sha2-nistp256 SHA256:N8Chm8YwSunjJ4KZVYHT4oq1uBFA8mXXLkxbl7wfpa0
[11:53:32.122] stderr> Authenticated to julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io ([35.247.61.45]:22).
[11:53:32.128] stderr> Connection to julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io closed by remote host.
[11:53:32.128] stderr> Transferred: sent 2680, received 1500 bytes, in 0.0 seconds
[11:53:32.128] stderr> Bytes per second: sent 474840.5, received 265769.0
[11:53:32.129] > local-server-5> ssh child died, shutting down
[11:53:32.136] Local server exit: 0
[11:53:32.136] Received install output: local-server-5> Spawned ssh, pid=96054
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:N8Chm8YwSunjJ4KZVYHT4oq1uBFA8mXXLkxbl7wfpa0
Authenticated to julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io ([35.247.61.45]:22).
Connection to julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io closed by remote host.
Transferred: sent 2680, received 1500 bytes, in 0.0 seconds
Bytes per second: sent 474840.5, received 265769.0
local-server-5> ssh child died, shutting down

[11:53:32.137] Failed to parse remote port from server output
[11:53:32.138] Resolver error: Error: 
	at g.Create (/Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:585222)
	at t.handleInstallOutput (/Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:583874)
	at Object.e [as tryInstallWithLocalServer] (/Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:624373)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:643506
	at async t.withShowDetailsEvent (/Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:647224)
	at async /Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622845
	at async T (/Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:619351)
	at async t.resolveWithLocalServer (/Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:622460)
	at async t.resolve (/Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:644834)
	at async /Users/julienmarie/.vscode/extensions/ms-vscode-remote.remote-ssh-0.84.0/out/extension.js:1:727082
[11:53:32.143] ------```


SSH Logs:
```ssh -v 'julienmarie-bonoboom-bb1m95ad5bh@julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io'
OpenSSH_7.9p1, LibreSSL 2.7.3
debug1: Reading configuration data /Users/julienmarie/.ssh/config
debug1: /Users/julienmarie/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 48: Applying options for *
debug1: Connecting to julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io [35.247.61.45] port 22.
debug1: Connection established.
debug1: identity file /Users/julienmarie/.ssh/id_rsa type 0
debug1: identity file /Users/julienmarie/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.9
debug1: Remote protocol version 2.0, remote software version GITPOD-GATEWAY
debug1: no match: GITPOD-GATEWAY
debug1: Authenticating to julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io:22 as 'julienmarie-bonoboom-bb1m95ad5bh'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:N8Chm8YwSunjJ4KZVYHT4oq1uBFA8mXXLkxbl7wfpa0
debug1: Host 'julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io' is known and matches the ECDSA host key.
debug1: Found key in /Users/julienmarie/.ssh/known_hosts:89
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: Will attempt key: /Users/julienmarie/.ssh/id_rsa RSA SHA256:2duKWmloM4BdKcpn/R9OFFfiQq9OjpFceoUT5dW6iEI explicit agent
debug1: Will attempt key: julienmarie@Juliens-iMac.lan RSA SHA256:6fF13q2qxgJ/vSDerQKnXdy6ouHy4tWW55f0RQ4rPxU agent
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: password,publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /Users/julienmarie/.ssh/id_rsa RSA SHA256:2duKWmloM4BdKcpn/R9OFFfiQq9OjpFceoUT5dW6iEI explicit agent
debug1: Server accepts key: /Users/julienmarie/.ssh/id_rsa RSA SHA256:2duKWmloM4BdKcpn/R9OFFfiQq9OjpFceoUT5dW6iEI explicit agent
debug1: Authentication succeeded (publickey).
Authenticated to julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io ([35.247.61.45]:22).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: channel 0: free: client-session, nchannels 1
Connection to julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io closed by remote host.
Connection to julienmarie-bonoboom-bb1m95ad5bh.ssh.ws-us68.gitpod.io closed.
Transferred: sent 2680, received 1500 bytes, in 0.0 seconds
Bytes per second: sent 638247.2, received 357227.9
debug1: Exit status -1```



### Steps to reproduce

Connect to Workspace

### Workspace affected

julienmarie-bonoboom-bb1m95ad5bh

### Expected behavior

It should connect.

### Example repository

_No response_

### Anything else?

_No response_

**Comment by csweichel** [comment]
Probably the same root cause as https://github.com/gitpod-io/gitpod/issues/13267. 
While investigating the logs I saw SSH key related errors (cannot write key).

**Comment by kylos101** [comment]
@julienmarie we've shifted traffic back to eu67 and us67 to avoid this issue, @aledbf confirmed it is an issue with shiftfs on eu68 and us68.

Please try restarting the workspace from the dashboard, it'll select us67, and you should be all set. If you continue to have this trouble, let us know and we'll reopen the issue.
