### ISSUE TITLE
`gp url` is broken (but not `gp url <port>`)

### ISSUE THREAD

**Issue by jankeromnes** [gitpod-io/gitpod#1333]
### Describe the bug
`gp url` is broken in Gitpod.

### Steps to reproduce
1. Open any repository in Gitpod
2. Try running `gp url`

### Expected behavior
It should print the workspace URL.

### Additional information
Instead, it fails with:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/typefox/gitpod/gitpod-cli/cmd.glob..func19(0xcfbf40, 0xd21c00, 0x0, 0x0)
        /tmp/build/components-gitpod-cli--app.8176a44aa14ed6721335b5e6087b8416bf085073/cmd/url.go:24 +0x221
github.com/spf13/cobra.(*Command).execute(0xcfbf40, 0xd21c00, 0x0, 0x0, 0xcfbf40, 0xd21c00)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xcfa640, 0x92cacd, 0x3, 0xc00000c300)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/typefox/gitpod/gitpod-cli/cmd.Execute()
        /tmp/build/components-gitpod-cli--app.8176a44aa14ed6721335b5e6087b8416bf085073/cmd/root.go:31 +0x2c4
main.main()
        /tmp/build/components-gitpod-cli--app.8176a44aa14ed6721335b5e6087b8416bf085073/main.go:13 +0x20
```

**Comment by csweichel** [comment]
fixed but not deployed yet

**Comment by svenefftinge** [comment]
deployed now
