### ISSUE TITLE
[Browser Extension] Inject Gitpod button is broken unless page reloads

### ISSUE THREAD

**Issue by andreafalzetti** [gitpod-io/gitpod#13609]
## Bug 
Currently, when using GitHub, the `Gitpod` button is not injected is the page is opened from a link inside another GitHub page. 

## Steps to reproduce
1. Open the Gitpod Pull requests page
2. Click a PR
3. Note how the button is not injected anymore
4. Reload the page
5. Note how the button now appears

**Comment by andreafalzetti** [comment]
@gtsiolis do you know/remember if this is a conscious decision or are we not intercepting the draft status?

**Comment by ShaunSHamilton** [comment]
Same for me. This is what I see in the console:

```console
gitpodify.bundle.js:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'prepend')
    at e.inject (gitpodify.bundle.js:1:15821)
    at e.injectButtons (gitpodify.bundle.js:1:25601)
    at t.<anonymous> (gitpodify.bundle.js:1:14691)
    at gitpodify.bundle.js:1:13276
    at Object.next (gitpodify.bundle.js:1:13381)
    at gitpodify.bundle.js:1:12293
    at new Promise (<anonymous>)
    at i (gitpodify.bundle.js:1:12038)
    at t.update (gitpodify.bundle.js:1:14619)
    at MutationObserver.<anonymous> (gitpodify.bundle.js:1:5773)
2command-palette-page-stack-element.ts:192 Uncaught TypeError: this.currentPage.fetch is not a function
    at CommandPalettePageStackElement.attributeChangedCallback (command-palette-page-stack-element.ts:192:28)
    at CatalystDelegate.attributeChangedCallback (core.js:54:38)
    at CatalystDelegate.a.attributeChangedCallback (core.js:20:22)
    at CatalystDelegate.connectedCallback (core.js:40:24)
    at CatalystDelegate.a.connectedCallback (core.js:12:22)
```

I have no idea if that second error at all relates 🤷‍♂️

**Comment by andreafalzetti** [comment]
I think I've found the problem, PR to fix it: https://github.com/gitpod-io/browser-extension/pull/68

cc @Siddhant-K-code @gtsiolis
