### ISSUE TITLE
gRPC error while updating credit limit during deployment rollout

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#15157]
Error below (from GCP logs) noticed when screen blanked while updating a (paid Stripe account) credit limit during a deployment rollout.

Would excpect that gRPC requests like this do not fail when services are updated.

(user-id obfuscated)
```json
{
  "insertId": "em8zq5f25wm2eho0",
  "jsonPayload": {
    "component": "server",
    "serviceContext": {
      "service": "server",
      "version": "main.5863"
    },
    "error": "ClientError: /usage.v1.BillingService/GetStripeCustomer NOT_FOUND: no team customer found for attribution_id: user:xxxxxx\n    at wrapClientError (/app/node_modules/nice-grpc/lib/client/wrapClientError.js:9:16)\n    at Object.callback (/app/node_modules/nice-grpc/lib/client/createUnaryMethod.js:27:66)\n    at Object.onReceiveStatus (/app/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/client.js:190:36)\n    at Object.onReceiveStatus (/app/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)\n    at Object.onReceiveStatus (/app/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)\n    at /app/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)",
    "loggedViaConsole": true,
    "stack_trace": "ClientError: /usage.v1.BillingService/GetStripeCustomer NOT_FOUND: no team customer found for attribution_id: user:xxxxxx\n    at wrapClientError (/app/node_modules/nice-grpc/lib/client/wrapClientError.js:9:16)\n    at Object.callback (/app/node_modules/nice-grpc/lib/client/createUnaryMethod.js:27:66)\n    at Object.onReceiveStatus (/app/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/client.js:190:36)\n    at Object.onReceiveStatus (/app/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:365:141)\n    at Object.onReceiveStatus (/app/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)\n    at /app/node_modules/nice-grpc/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78\n    at processTicksAndRejections (node:internal/process/task_queues:78:11)",
    "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent"
  },
  "resource": {
    "type": "k8s_container",
    "labels": {
      "project_id": "gitpod-xxxxxx",
      "cluster_name": "prod-meta-eu02",
      "namespace_name": "default",
      "location": "europe-west1",
      "pod_name": "server-5c7f76c7b-mg6rx",
      "container_name": "server"
    }
  },
  "timestamp": "2022-12-05T12:00:44.164Z",
  "severity": "ERROR",
  "labels": {
    "k8s-pod/component": "server",
    "compute.googleapis.com/resource_name": "gke-prod-meta-eu02-services-pool-1-b9de9bab-7132",
    "k8s-pod/pod-template-hash": "5c7f76c7b",
    "k8s-pod/app": "gitpod"
  },
  "logName": "projects/gitpod-xxxxxx/logs/stderr",
  "receiveTimestamp": "2022-12-05T12:00:45.594900646Z"
}
```

**Comment by svenefftinge** [comment]
This is actually a regular error the RPC method return in case no stripe customer exists for the given attributionid. 
The `server` doesn't handle it well, but simply logs it (using `console`). So this should either be handled properly or return nil in case no such customer exists, which I believe is a better protocol as it's not really an exceptional case.
