### ISSUE TITLE
[vscode] Cannot connect to workspace

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#15292]
When starting a workspace VS Code fails to connect to it with this error message:
```
ConnectError: [unknown] cannot decode message gitpod.experimental.v1.WorkspaceInstanceStatus from JSON: key "ports" is unknown
    at connectErrorFromReason (/Users/svenefftinge/.vscode/extensions/gitpod.gitpod-desktop-0.0.66/node_modules/@bufbuild/connect-web/dist/cjs/connect-error.js:142:16)
    at Object.unary (/Users/svenefftinge/.vscode/extensions/gitpod.gitpod-desktop-0.0.66/node_modules/@bufbuild/connect-web/dist/cjs/connect-transport.js:76:46)
    at process.response (node:internal/process/task_queues:96:5)
    at Object.getWorkspace (/Users/svenefftinge/.vscode/extensions/gitpod.gitpod-desktop-0.0.66/node_modules/@bufbuild/connect-web/dist/cjs/promise-client.js:39:15)
    at t.GitpodPublicApi.registeredSSHKeys [as getWorkspace] (/Users/svenefftinge/.vscode/extensions/gitpod.gitpod-desktop-0.0.66/src/publicApi.ts:40:9)
    at async Promise.all (index 0)
    at q.password [as getWorkspaceSSHDestination] (/Users/svenefftinge/.vscode/extensions/gitpod.gitpod-desktop-0.0.66/src/remoteConnector.ts:539:37)
    at q.handleUri (/Users/svenefftinge/.vscode/extensions/gitpod.gitpod-desktop-0.0.66/src/remoteConnector.ts:841:26)
```

**Comment by mustard-mh** [comment]
`0.0.67` released, upgrade should fix this problem 🙏
