### ISSUE TITLE
Extension "Blockman" is not working with GitPod

### ISSUE THREAD

**Issue by mmailaender** [gitpod-io/gitpod#16675]
### Bug description

I tried to install the [Blockman](https://open-vsx.org/extension/leodevbro/blockman) extension in Gitpod Browser VSCode. But it's not working and failing due activation. I created a bug report at the Repo of the creator of this extension:
https://github.com/leodevbro/vscode-blockman/issues/102#issuecomment-1452260952

He assumes that this is a bug with VSCode (Linux) itself. 

### Steps to reproduce

Open Github Browser
Install Extension `Blockman` and try to enable it `blockman.toggleEnableDisable`

### Expected behavior

Working Blockman extension
![image](https://user-images.githubusercontent.com/87228994/222890029-b90e785e-6e46-48c9-8557-252ee621028d.png)

**Comment by leodevbro** [comment]
One more thing:
`blockman.toggleEnableDisable` is not necessary. Blockman is enabled by default after installation.

Sometimes I faced such issue that Blockman was not working at all after installation, and I restarted VS Code, then waited about 10-20 seconds and it worked. Maybe you can try it.

I guess this issue occurs mostly on low-end devices, I mean the devices which don't have powerful CPU. Can you provide your system info? like CPU, GPU, RAM.

**Comment by leodevbro** [comment]
Or, sorry, I just realized that Gitpod is a cloud software. It basically uses VS Code web, not VS Code desktop. The thing is that Blockman is built with some components which works only on Node.js environment, and so it does not work on web browser environment.

**Comment by akosyakov** [comment]
cc @jeanp413 could you have a look please? 🙏

**Comment by jeanp413** [comment]
As @leodevbro it's because the extension tries to load some files from `node_modules.asar` which is only available in vscode desktop, for vscode server it should be just `node_modules`
Closing this as it should fixed in the extension itself
```
2023-03-13 16:25:01.136 [error] Activating extension leodevbro.blockman failed due to an error:
2023-03-13 16:25:01.136 [error] Error: Cannot find module '/ide/node_modules.asar/vscode-textmate'
Require stack:
- /workspace/.vscode-remote/extensions/leodevbro.blockman-1.7.1-universal/out/bracketAlgos/textMateLoader.js
- /workspace/.vscode-remote/extensions/leodevbro.blockman-1.7.1-universal/out/bracketAlgos/settings.js
- /workspace/.vscode-remote/extensions/leodevbro.blockman-1.7.1-universal/out/bracketAlgos/documentDecorationManager.js
- /workspace/.vscode-remote/extensions/leodevbro.blockman-1.7.1-universal/out/extension.js
- /ide/out/vs/loader.js
- /ide/out/bootstrap-amd.js
- /ide/out/bootstrap-fork.js
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
	at Function.Module._load (node:internal/modules/cjs/loader:778:27)
	at Function.l._load (/ide/out/vs/workbench/api/node/extensionHostProcess.js:124:14199)
	at Function.f._load (/ide/out/vs/workbench/api/node/extensionHostProcess.js:119:63015)
	at Function.C._load (/ide/out/vs/workbench/api/node/extensionHostProcess.js:119:62408)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at TextMateLoader.getNodeModule (/workspace/.vscode-remote/extensions/leodevbro.blockman-1.7.1-universal/out/bracketAlgos/textMateLoader.js:117:16)
	at TextMateLoader.loadTextMate (/workspace/.vscode-remote/extensions/leodevbro.blockman-1.7.1-universal/out/bracketAlgos/textMateLoader.js:120:21)
	at new TextMateLoader (/workspace/.vscode-remote/extensions/leodevbro.blockman-1.7.1-universal/out/bracketAlgos/textMateLoader.js:24:27)
	at new Settings (/workspace/.vscode-remote/extensions/leodevbro.blockman-1.7.1-universal/out/bracketAlgos/settings.js:10:31)
	at new DocumentDecorationManager (/workspace/.vscode-remote/extensions/leodevbro.blockman-1.7.1-universal/out/bracketAlgos/documentDecorationManager.js:12:25)
	at activate (/workspace/.vscode-remote/extensions/leodevbro.blockman-1.7.1-universal/out/extension.js:417:30)
	at Function.eb (/ide/out/vs/workbench/api/node/extensionHostProcess.js:110:14929)
	at Function.db (/ide/out/vs/workbench/api/node/extensionHostProcess.js:110:14625)
	at /ide/out/vs/workbench/api/node/extensionHostProcess.js:110:12641
	at async E.n (/ide/out/vs/workbench/api/node/extensionHostProcess.js:96:6581)
	at async E.m (/ide/out/vs/workbench/api/node/extensionHostProcess.js:96:6544)
	at async E.l (/ide/out/vs/workbench/api/node/extensionHostProcess.js:96:6001)
```
