### ISSUE TITLE
Prettier not able to run on commad npm run format

### ISSUE THREAD

**Issue by Yael95** [gitpod-io/gitpod#1912]
I installed prettier from npm then from the VS extensions view, but when I modified my package.json to add prettier to it through scripts property : {
  "name": "AdoptmeApp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
      "format" : "prettier \"src/**/*.{js,html}\" --write",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Yael95/AdoptmeApp.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/Yael95/AdoptmeApp/issues"
  },
  "homepage": "https://github.com/Yael95/AdoptmeApp#readme",
  "devDependencies": {
    "prettier": "^2.1.2"
  }
}
**********************************************
I get this when I run the npm run format
***************************************
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/gitpod/.nvm/versions/node/v12.18.3/bin/node',
1 verbose cli   '/home/gitpod/.nvm/versions/node/v12.18.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'format'
1 verbose cli ]
2 info using npm@6.14.7
3 info using node@v12.18.3
4 verbose run-script [ 'preformat', 'format', 'postformat' ]
5 info lifecycle AdoptmeApp@1.0.0~preformat: AdoptmeApp@1.0.0
6 info lifecycle AdoptmeApp@1.0.0~format: AdoptmeApp@1.0.0
7 verbose lifecycle AdoptmeApp@1.0.0~format: unsafe-perm in lifecycle true
8 verbose lifecycle AdoptmeApp@1.0.0~format: PATH: /home/gitpod/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/workspace/AdoptmeApp/node_modules/.bin:/home/gitpod/.nvm/versions/node/v12.18.3/bin:/home/gitpod/.cargo/bin:/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims:/home/gitpod/.pyenv/shims:/workspace/.cargo/bin:/workspace/.pip-modules/bin:/workspace/.rvm/bin:/home/gitpod/.cargo/bin:/home/gitpod/.sdkman/candidates/maven/current/bin:/home/gitpod/.sdkman/candidates/java/current/bin:/home/gitpod/.sdkman/candidates/gradle/current/bin:/home/gitpod/.cargo/bin:/home/gitpod/.rvm/gems/ruby-2.6.6/bin:/home/gitpod/.rvm/gems/ruby-2.6.6@global/bin:/home/gitpod/.rvm/rubies/ruby-2.6.6/bin:/home/gitpod/.pyenv/plugins/pyenv-virtualenv/shims:/home/gitpod/.pyenv/shims:/workspace/.cargo/bin:/workspace/.pip-modules/bin:/workspace/.rvm/bin:/home/gitpod/.pyenv/bin:/home/gitpod/.pyenv/shims:/workspace/go/bin:/home/gitpod/go/bin:/home/gitpod/go-packages/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin/:/home/gitpod/.nvm/versions/node/v12.18.3/bin:/home/gitpod/.rvm/bin:/home/gitpod/.rvm/bin:/home/gitpod/.rvm/bin
9 verbose lifecycle AdoptmeApp@1.0.0~format: CWD: /workspace/AdoptmeApp
10 silly lifecycle AdoptmeApp@1.0.0~format: Args: [ '-c', 'prettier "src/**/*.{js,html}" --write' ]
11 silly lifecycle AdoptmeApp@1.0.0~format: Returned: code: 2  signal: null
12 info lifecycle AdoptmeApp@1.0.0~format: Failed to exec format script
13 verbose stack Error: AdoptmeApp@1.0.0 format: `prettier "src/**/*.{js,html}" --write`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/home/gitpod/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/gitpod/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid AdoptmeApp@1.0.0
15 verbose cwd /workspace/AdoptmeApp/SRC
16 verbose Linux 4.14.174+
17 verbose argv "/home/gitpod/.nvm/versions/node/v12.18.3/bin/node" "/home/gitpod/.nvm/versions/node/v12.18.3/bin/npm" "run" "format"
18 verbose node v12.18.3
19 verbose npm  v6.14.7
20 error code ELIFECYCLE
21 error errno 2
22 error AdoptmeApp@1.0.0 format: `prettier "src/**/*.{js,html}" --write`
22 error Exit status 2
23 error Failed at the AdoptmeApp@1.0.0 format script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by Yael95** [comment]
I actually solved the issue through manual install of the extension on vs for the whole user, and then writing a config file for prettier called : .prettierrc
