### ISSUE TITLE
error creating Bitbucket.org workspace from self-hosted gitpod

### ISSUE THREAD

**Issue by adorokhin70** [gitpod-io/gitpod#1969]
### Describe the bug
the "Error: Couldn't parse context 'https://bitbucket.org/gitpod/spring-petclinic/src/master/'." message appears ons elf-hosted gitpod (gcp) upon trying to create workspace bitbucket project. Please note that the same works for gitpod.io

### Steps to reproduce

1. have self-hosted gitpod
2. type https://<self-hosted-url>/#https://bitbucket.org/gitpod/spring-petclinic/src/master/
3. observe the issue

### Expected behavior
the workspace have to be imported (the same as for gitpod.io)

### Additional information
stacktrace:
 "Error: Couldn't parse context 'https://bitbucket.org/chawkshaw/petclinic/src/master/'.
    at ContextParser.<anonymous> (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:166:35)
    at step (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:47:23)
    at Object.next (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:28:53)
    at /app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:18:12)
    at ContextParser.handle (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:122:16)
    at Proxy.<anonymous> (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:963:61)
    at step (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:58:23)
    at Object.next (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:39:53)
    at /app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:33:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:29:12)
    at Proxy.GitpodServerImpl.createWorkspace (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:940:16)
    at JsonRpcProxyFactory.<anonymous> (/app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:209:73)
    at step (/app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:39:23)
    at Object.next (/app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:20:53)
    at /app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:10:12)
    at JsonRpcProxyFactory.onRequest (/app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:202:16)
    at /app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:165:48
    at handleRequest (/app/node_modules/vscode-jsonrpc/lib/main.js:380:27)
    at processMessageQueue (/app/node_modules/vscode-jsonrpc/lib/main.js:270:17)
    at Immediate.<anonymous> (/app/node_modules/vscode-jsonrpc/lib/main.js:260:13)
    at processImmediate (internal/timers.js:456:21)", "component": "server", "error": "Error: Couldn't parse context 'https://bitbucket.org/chawkshaw/petclinic/src/master/'.
    at ContextParser.<anonymous> (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:166:35)
    at step (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:47:23)
    at Object.next (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:28:53)
    at /app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:18:12)
    at ContextParser.handle (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:122:16)
    at Proxy.<anonymous> (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:963:61)
    at step (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:58:23)
    at Object.next (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:39:53)
    at /app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:33:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:29:12)
    at Proxy.GitpodServerImpl.createWorkspace (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:940:16)
    at JsonRpcProxyFactory.<anonymous> (/app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:209:73)
    at step (/app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:39:23)
    at Object.next (/app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:20:53)
    at /app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:10:12)
    at JsonRpcProxyFactory.onRequest (/app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:202:16)
    at /app/node_modules/@gitpod/gitpod-protocol/lib/messaging/proxy-factory.js:165:48
    at handleRequest (/app/node_modules/vscode-jsonrpc/lib/main.js:380:27)
    at processMessageQueue (/app/node_modules/vscode-jsonrpc/lib/main.js:270:17)
    at Immediate.<anonymous> (/app/node_modules/vscode-jsonrpc/lib/main.js:260:13)
    at processImmediate (internal/timers.js:456:21)"

### Example repository
https://github.com/gitpod-io/gitpod

**Comment by svenefftinge** [comment]
Did you add the Bitbucket auth provider configuration?
You need to [create an auth app on bitbucket.org](https://support.atlassian.com/bitbucket-cloud/docs/integrate-another-application-through-oauth/) and then configure your gitpod self-hosted version accordingly.

```
  - id: "Public-Bitbucket"
    host: "bitbucket.org"
    type: "Bitbucket"
    description: "Login with Bitbucket"
    icon: ""
    requireTOS: true
    oauth:
      callBackUrl: "https://<REPLACE-WITH-GITPOD-SELF-HOSTED-DOMAIN>/auth/bitbucket/callback"
      clientId: "<REPLACE>"
      clientSecret: "<REPLACE>"
```

**Comment by AlexTugarev** [comment]
The configuration ☝️ should work. Just one note: this should go into the `values.yaml` 

```yaml
gitpod:
  authProviders:
  - id: "Public-Bitbucket"
    ...
```
