### ISSUE TITLE
pyright extension fails to start

### ISSUE THREAD

**Issue by tekumara** [gitpod-io/gitpod#1992]
### Describe the bug

The Pyright server crashed 5 times in the last 3 minutes. The server will not be restarted.

### Steps to reproduce
Add the pyright extension (v1.1.48) to a repo

### Expected behavior
pyright should work

### Additional information
```
internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:116028)
    at n (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:172)
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:21:23357)
    at n (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:172)
    at /tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:964
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:974)
[Info  - 11:42:26 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:116028)
    at n (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:172)
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:21:23357)
    at n (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:172)
    at /tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:964
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:974)
[Info  - 11:42:26 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:116028)
    at n (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:172)
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:21:23357)
    at n (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:172)
    at /tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:964
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:974)
[Info  - 11:42:27 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:116028)
    at n (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:172)
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:21:23357)
    at n (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:172)
    at /tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:964
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:974)
[Info  - 11:42:27 PM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:584
    throw err;
    ^
Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:116028)
    at n (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:172)
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:21:23357)
    at n (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:172)
    at /tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:964
    at Object.<anonymous> (/tmp/vscode-extensions/ms-pyright.pyright@1.1.48/extension/server/server.bundle.js:1:974)
[Error - 11:42:27 PM] Connection to server got closed. Server will not be restarted.
```

### Example repository

https://github.com/seek-oss/aec

**Comment by akosyakov** [comment]
It is requiring Node.j 12. Theia on gitpod.io is running on Node.js 10 still. We fixed it already on staging env.

**Comment by jankeromnes** [comment]
We've deployed the fix to production this morning.

However, the Pyright extension still fails to activate. The new error is:

<img width="502" alt="Screenshot 2020-12-04 at 08 33 18" src="https://user-images.githubusercontent.com/599268/101135280-e33e8e80-360b-11eb-80d8-75f1257b68a7.png">

**Comment by akosyakov** [comment]
brrr, we need another upgrade, it was already bumped up in Theia. We will do it within next 2 weeks.

Alternatively you can add `export VSCODE_API_VERSION=1.50.0` in your docker image, but it is a hack.
