### ISSUE TITLE
vim not working on vscode

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#20347]
### Bug description

vim not working

### Steps to reproduce

install vim extension. not working in any repo.

### Anything else?

worker log
```
2024-11-06 14:21:07.819 [info] Extension host started
2024-11-06 14:21:07.819 [info] Eager extensions activated
2024-11-06 14:21:42.359 [info] ExtensionService#_doActivateExtension vscodevim.vim, startup: false, activationEvent: 'onStartupFinished'
```

remote log
```
2024-11-06 06:21:16.237 [info] Extension host with pid 330 started
2024-11-06 06:21:16.243 [info] Lock '/workspace/.vscode-remote/data/User/workspaceStorage/-49f2570c/vscode.lock': Lock acquired.
2024-11-06 06:21:16.917 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2024-11-06 06:21:16.918 [info] ExtensionService#_doActivateExtension gitpod.gitpod-web, startup: true, activationEvent: '*'
2024-11-06 06:21:17.394 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2024-11-06 06:21:17.394 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2024-11-06 06:21:17.903 [info] Eager extensions activated
2024-11-06 06:21:17.903 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2024-11-06 06:21:17.903 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2024-11-06 06:21:17.904 [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onStartupFinished', root cause: GitHub.vscode-pull-request-github
2024-11-06 06:21:18.314 [info] ExtensionService#_doActivateExtension GitHub.vscode-pull-request-github, startup: false, activationEvent: 'onStartupFinished'
2024-11-06 06:21:18.436 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2024-11-06 06:21:43.544 [info] ExtensionService#_doActivateExtension vadimcn.vscode-lldb, startup: false, activationEvent: 'onStartupFinished'
2024-11-06 06:21:53.786 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:json'
2024-11-06 06:21:53.786 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:json'
2024-11-06 06:21:53.786 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:json'
2024-11-06 06:21:53.786 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onLanguage:json'
2024-11-06 06:21:56.177 [info] ExtensionService#_doActivateExtension WakaTime.vscode-wakatime, startup: false, activationEvent: '*'
2024-11-06 06:22:02.255 [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode, startup: false, activationEvent: 'onStartupFinished'
2024-11-06 06:22:08.136 [info] ExtensionService#_doActivateExtension firsttris.vscode-jest-runner, startup: false, activationEvent: '*'
2024-11-06 06:22:11.188 [info] ExtensionService#_doActivateExtension ms-vscode.test-adapter-converter, startup: false, activationEvent: '*', root cause: hbenl.vscode-test-explorer
2024-11-06 06:22:11.549 [info] ExtensionService#_doActivateExtension hbenl.vscode-test-explorer, startup: false, activationEvent: '*'
2024-11-06 06:22:12.281 [info] ExtensionService#_doActivateExtension hbenl.test-adapter-converter, startup: false, activationEvent: 'onCommand:testExplorerConverter.activate'
2024-11-06 06:22:12.637 [error] Activating extension hbenl.test-adapter-converter failed due to an error:
2024-11-06 06:22:12.637 [error] Error: command 'testExplorerConverter.activate' already exists
	at Z0.registerCommand (file:///ide/out/vs/workbench/api/node/extensionHostProcess.js:114:31677)
	at Object.registerCommand (file:///ide/out/vs/workbench/api/node/extensionHostProcess.js:156:36491)
	at G (/workspace/.vscode-remote/extensions/hbenl.test-adapter-converter-0.1.6-universal/out/extension.js:2:806)
	at gw.kb (file:///ide/out/vs/workbench/api/node/extensionHostProcess.js:118:15214)
	at gw.jb (file:///ide/out/vs/workbench/api/node/extensionHostProcess.js:118:14921)
	at file:///ide/out/vs/workbench/api/node/extensionHostProcess.js:118:13079
	at async _0.n (file:///ide/out/vs/workbench/api/node/extensionHostProcess.js:114:4447)
	at async _0.m (file:///ide/out/vs/workbench/api/node/extensionHostProcess.js:114:4410)
	at async _0.l (file:///ide/out/vs/workbench/api/node/extensionHostProcess.js:114:3866)
```

**Comment by axonasif** [comment]
Hi @gengjiawen, did you try an older version?

**Comment by gengjiawen** [comment]
> Hi @gengjiawen, did you try an older version?

I didn't see vscode provide an option to downgrade extension. download a older version to test it ?

**Comment by axonasif** [comment]
Yep

**Comment by gengjiawen** [comment]
downgrade to 1.27.2 (Dec 23, 2023) not working. Can I download vscode for gitpod ?

**Comment by gengjiawen** [comment]
gitpod provide vscode and vscode-canary and jetbrains IDE. so maybe a older version vscode ?

**Comment by gengjiawen** [comment]
upstream bug: https://github.com/VSCodeVim/Vim/issues/8794

**Comment by axonasif** [comment]
@gengjiawen you can pin an older vscode version from this page: https://gitpod.io/settings/policy (scroll down)

**Comment by gengjiawen** [comment]
One weird thing is that the extension load time is -1ms. The extension itself works on github workspace. So maybe it's gitpdo bug @axonasif 

![image](https://github.com/user-attachments/assets/45233cf7-a9f7-47c2-b337-4bfcf891e428)

**Comment by gengjiawen** [comment]
working now.
