### ISSUE TITLE
[self-hosted] GitHub API Error. Status: 500

### ISSUE THREAD

**Issue by jgallucci32** [gitpod-io/gitpod#2285]
### Describe the bug
When attempting to launch a workspace on a self-hosted instance connected to GitHub, certain repositories fail with the following error
```
We are having trouble parsing your context
Error: GitHub API Error. Status: 500
```
Here is the detailed error from the `server` pod logs
```
{"component":"server","severity":"INFO","time":"2020-11-25T03:17:48.716Z","environment":"production","region":"local","context":{"userId":"608ecfa8-bbd2-4de5-ac0f-880b10b4c12a"},"message":"createWorkspace","payload":{"mode":"select-if-running"}}
{"component":"server","severity":"INFO","time":"2020-11-25T03:17:48.751Z","environment":"production","region":"local","context":{"userId":"608ecfa8-bbd2-4de5-ac0f-880b10b4c12a"},"message":"getLoggedInUser"}
{"component":"server","severity":"INFO","time":"2020-11-25T03:17:48.752Z","environment":"production","region":"local","context":{"userId":"608ecfa8-bbd2-4de5-ac0f-880b10b4c12a"},"message":"getWorkspaces"}
{"component":"server","severity":"INFO","time":"2020-11-25T03:17:48.854Z","environment":"production","region":"local","context":{"userId":"608ecfa8-bbd2-4de5-ac0f-880b10b4c12a"},"message":"updateLoggedInUser"}
{"component":"server","severity":"DEBUG","time":"2020-11-25T03:17:49.377Z","environment":"production","region":"local","context":{"userId":"608ecfa8-bbd2-4de5-ac0f-880b10b4c12a"},"message":"Looking for prebuilt workspace: ","payload":{"mode":"select-if-running","cloneUrl":"https://github.com/goharbor/harbor.git","commit":"039722c518963175dc2a37ccd837db1a06952467"}}
{"component":"server","severity":"DEBUG","time":"2020-11-25T03:17:54.417Z","environment":"production","region":"local","message":"GitHub request took 5029 ms"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"server","version":"0.5.0"},"stack_trace":"GitHubApiError: GitHub API Error. Status: 500
    at new GitHubApiError (/app/node_modules/@gitpod/server/dist/src/github/api.js:78:28)
    at GitHubRestApi.<anonymous> (/app/node_modules/@gitpod/server/dist/src/github/api.js:278:35)
    at step (/app/node_modules/@gitpod/server/dist/src/github/api.js:60:23)
    at Object.throw (/app/node_modules/@gitpod/server/dist/src/github/api.js:41:53)
    at rejected (/app/node_modules/@gitpod/server/dist/src/github/api.js:33:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)","component":"server","severity":"ERROR","time":"2020-11-25T03:17:54.420Z","environment":"production","region":"local","context":{"userId":"608ecfa8-bbd2-4de5-ac0f-880b10b4c12a"},"error":"GitHubApiError: GitHub API Error. Status: 500
    at new GitHubApiError (/app/node_modules/@gitpod/server/dist/src/github/api.js:78:28)
    at GitHubRestApi.<anonymous> (/app/node_modules/@gitpod/server/dist/src/github/api.js:278:35)
    at step (/app/node_modules/@gitpod/server/dist/src/github/api.js:60:23)
    at Object.throw (/app/node_modules/@gitpod/server/dist/src/github/api.js:41:53)
    at rejected (/app/node_modules/@gitpod/server/dist/src/github/api.js:33:65)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}
{"component":"server","severity":"INFO","time":"2020-11-25T03:17:54.421Z","environment":"production","region":"local","message":"Request createWorkspace unsuccessful: 460/\"GitHub API Error. Status: 500\"","payload":{"method":"createWorkspace","args":[{"contextUrl":"https://github.com/goharbor/harbor","mode":"select-if-running"},{"_isCancelled":false}]}}
{"component":"server","severity":"INFO","time":"2020-11-25T03:17:54.535Z","environment":"production","region":"local","context":{"userId":"608ecfa8-bbd2-4de5-ac0f-880b10b4c12a"},"message":"getLoggedInUser"}
```

### Steps to reproduce
1. Deploy Gitpod self-hosted on K8s
2. Configure oauth integration with Github
3. Launch workspace

### Expected behavior
Workspace launches correctly

### Additional information
It seems to work on some repositories, but seem to be only those which are related to Gitpod itself. For example, the `demo-apps/go-gin-app` and `gitpod-io/gitpod` projects are of the few that work and it could be because pre-built workspaces exist or some other reason I've yet to figure out. Any new project or existing project which does not seem Gitpod-ready does not work.

### Example repository
https://github.com/goharbor/harbor.git

**Comment by meysholdt** [comment]
We should try if this is reproducible with the provided example repo. If it is not, it may have been a temporary problem with service quality on the Github side.
