### ISSUE TITLE
'Error: Invalid key length' When Logging Into Gitpod at master.248

### ISSUE THREAD

**Issue by jimmybrancaccio** [gitpod-io/gitpod#2448]
**Before I get into things, please let me know if this is a good place to report issues with master builds. If it's not please let me know where I can. I definitely want to report these issues so they can get fixed and so other people don't have them!** 😄 

I also understand support isn't really supported for master but this could be a bug that other could potentially experience so it may be worth looking into and fixing.

### Describe the bug

When using `master.248` and logging in using GitHub Enterprise (it may affect GitHub.com as well) it fails with the error of:

> Error: Invalid key length

I know there was [a recent merged PR](https://github.com/gitpod-io/gitpod/pull/2375) where there was some concerns if GitHub would break, perhaps it could be related? Though, I would assume if there was you guys would have heard about it from gitpod.io customers?

### Steps to reproduce

1. Clone the [gitpod repository](https://github.com/gitpod-io/gitpod) - `git clone https://github.com/gitpod-io/gitpod`.
2. Move into the `charts` directory - `cd gitpod/charts/`.
3. Edit the `Charts.yml` file and set the `version:` value to `master.248`. It should read `version: master.248`. Save and exit the file.
4. Edit the `values.yaml` file. Change `version` to also be `master.248`. It should read `version: master.248`.
5. Make sure you have a GitHub auth provider configured. I am using GitHub Enterprise, I have not tested with GitHub.com though. Save and exit the file.
6. Run `helm upgrade --install gitpod ./ --timeout 60m --values values.yaml -n gitpod` from the `charts` directory. It may take a minute for everything to spin up.
7. Visit your Gitpod instance in your web browser and attempt to login.
8. Assert that login failed and you see a Sorry page in the browser.

### Expected behavior

I would expect that login is successful.

### Additional information

It's worth noting that I am using an external registry, external MySQL DB, and external MinIO instance. Though I would think the only thing that _possibly_ could cause this issue is the external MySQL database but I am doubtful.

I am by no means someone who is familiar with Javascript/TypeScript/NodeJS but I feel like I've narrowed the issue down to happening [around here](https://github.com/gitpod-io/gitpod/blob/c263553c45911128abbb29161b793a6ca3695925/components/server/src/auth/generic-auth-provider.ts#L480). I feel like the key value which is being send to the [crypto.createCipheriv](https://github.com/gitpod-io/gitpod/blob/c263553c45911128abbb29161b793a6ca3695925/components/gitpod-protocol/src/encryption/encryption-engine.ts#L42) is empty or something.

Here's some logs I've collected from the server pod:

```json
{
    "component": "server",
    "severity": "INFO",
    "time": "2020-12-07T15:06:00.597Z",
    "environment": "production",
    "region": "local",
    "message": "Request getFeaturedRepositories unsuccessful: 401/\"User is not authenticated. Please login.\"",
    "payload": {
        "method": "getFeaturedRepositories",
        "args": [
            null,
            {
                "_isCancelled": false
            }
        ]
    }
}

{
    "component": "server",
    "severity": "INFO",
    "time": "2020-12-07T15:06:01.485Z",
    "environment": "production",
    "region": "local",
    "context": {
        "sessionId": "181dfefb-a37c-4476-9930-5d03b0741bd7"
    },
    "message": "(Auth) User started the login process",
    "payload": {
        "login-flow": true,
        "clientInfo": {
            "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15",
            "fingerprint": "0456dc1556b6b6b3204cc46d39497a4384cfd1334d87c2e81505ca0525a87dcf"
        }
    }
}

{
    "component": "server",
    "severity": "INFO",
    "time": "2020-12-07T15:06:02.627Z",
    "environment": "production",
    "region": "local",
    "message": "Auth Provider Callback. Path: /auth/github/callback"
}

{
    "component": "server",
    "severity": "INFO",
    "time": "2020-12-07T15:06:03.496Z",
    "environment": "production",
    "region": "local",
    "message": "(Auth-With-octocat.ninja) Verify for authName: jimmybrancaccio",
    "payload": {
        "authorize-flow": false,
        "login-flow": true,
        "clientInfo": {
            "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15",
            "fingerprint": "0456dc1556b6b6b3204cc46d39497a4384cfd1334d87c2e81505ca0525a87dcf"
        },
        "authProviderId": "GitHub-Enterprise",
        "authUser": {
            "authId": "4",
            "authName": "jimmybrancaccio",
            "avatarUrl": "https://avatars.octocat.ninja/u/4?",
            "name": "Jimmy B.",
            "primaryEmail": "jimmybrancaccio@*****.com"
        }
    }
}

{
    "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
    "serviceContext": {
        "service": "server",
        "version": "master.248"
    },
    "stack_trace": "Error: Invalid key length\n    at Cipheriv.createCipherBase (internal/crypto/cipher.js:103:19)\n    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)\n    at new Cipheriv (internal/crypto/cipher.js:225:22)\n    at Object.createCipheriv (crypto.js:119:10)\n    at EncryptionEngineImpl.encrypt (/app/node_modules/@gitpod/gitpod-protocol/lib/encryption/encryption-engine.js:31:29)\n    at EncryptionServiceImpl.encrypt (/app/node_modules/@gitpod/gitpod-protocol/lib/encryption/encryption-service.js:39:41)\n    at Object.to (/app/node_modules/@gitpod/gitpod-db/lib/typeorm/transformer.js:48:52)\n    at CompositeValueTransformer.to (/app/node_modules/@gitpod/gitpod-db/lib/typeorm/transformer.js:65:27)\n    at MysqlDriver.preparePersistentValue (/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:273:48)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:433:71\n    at Array.forEach (<anonymous>)\n    at SubjectOperationExecutor.collectColumnsAndValues (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:427:30)\n    at SubjectOperationExecutor.<anonymous> (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:363:42)\n    at step (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)\n    at Object.next (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:3:12)\n    at SubjectOperationExecutor.insert (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:342:16)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:167:116\n    at Array.map (<anonymous>)\n    at SubjectOperationExecutor.<anonymous> (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:167:78)\n    at step (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)\n    at Object.next (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:3:12)\n    at SubjectOperationExecutor.executeInsertOperations (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:157:16)\n    at SubjectOperationExecutor.<anonymous> (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:97:51)\n    at step (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)\n    at Object.next (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)\n    at fulfilled (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:4:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "component": "server",
    "severity": "ERROR",
    "time": "2020-12-07T15:06:03.615Z",
    "environment": "production",
    "region": "local",
    "message": "(Auth-With-octocat.ninja) Exception in verify function",
    "error": "Error: Invalid key length\n    at Cipheriv.createCipherBase (internal/crypto/cipher.js:103:19)\n    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)\n    at new Cipheriv (internal/crypto/cipher.js:225:22)\n    at Object.createCipheriv (crypto.js:119:10)\n    at EncryptionEngineImpl.encrypt (/app/node_modules/@gitpod/gitpod-protocol/lib/encryption/encryption-engine.js:31:29)\n    at EncryptionServiceImpl.encrypt (/app/node_modules/@gitpod/gitpod-protocol/lib/encryption/encryption-service.js:39:41)\n    at Object.to (/app/node_modules/@gitpod/gitpod-db/lib/typeorm/transformer.js:48:52)\n    at CompositeValueTransformer.to (/app/node_modules/@gitpod/gitpod-db/lib/typeorm/transformer.js:65:27)\n    at MysqlDriver.preparePersistentValue (/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:273:48)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:433:71\n    at Array.forEach (<anonymous>)\n    at SubjectOperationExecutor.collectColumnsAndValues (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:427:30)\n    at SubjectOperationExecutor.<anonymous> (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:363:42)\n    at step (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)\n    at Object.next (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:3:12)\n    at SubjectOperationExecutor.insert (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:342:16)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:167:116\n    at Array.map (<anonymous>)\n    at SubjectOperationExecutor.<anonymous> (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:167:78)\n    at step (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)\n    at Object.next (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:3:12)\n    at SubjectOperationExecutor.executeInsertOperations (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:157:16)\n    at SubjectOperationExecutor.<anonymous> (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:97:51)\n    at step (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)\n    at Object.next (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)\n    at fulfilled (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:4:58)\nat processTicksAndRejections (internal/process/task_queues.js:97:5)",
    "payload": {
        "authorize-flow": false,
        "login-flow": true,
        "clientInfo": {
            "ua": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15",
            "fingerprint": "0456dc1556b6b6b3204cc46d39497a4384cfd1334d87c2e81505ca0525a87dcf"
        },
        "authProviderId": "GitHub-Enterprise",
        "err": "Error: Invalid key length\n    at Cipheriv.createCipherBase (internal/crypto/cipher.js:103:19)\n    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:121:20)\n    at new Cipheriv (internal/crypto/cipher.js:225:22)\n    at Object.createCipheriv (crypto.js:119:10)\n    at EncryptionEngineImpl.encrypt (/app/node_modules/@gitpod/gitpod-protocol/lib/encryption/encryption-engine.js:31:29)\n    at EncryptionServiceImpl.encrypt (/app/node_modules/@gitpod/gitpod-protocol/lib/encryption/encryption-service.js:39:41)\n    at Object.to (/app/node_modules/@gitpod/gitpod-db/lib/typeorm/transformer.js:48:52)\n    at CompositeValueTransformer.to (/app/node_modules/@gitpod/gitpod-db/lib/typeorm/transformer.js:65:27)\n    at MysqlDriver.preparePersistentValue (/app/node_modules/typeorm/driver/mysql/MysqlDriver.js:273:48)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:433:71\n    at Array.forEach (<anonymous>)\n    at SubjectOperationExecutor.collectColumnsAndValues (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:427:30)\n    at SubjectOperationExecutor.<anonymous> (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:363:42)\n    at step (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)\n    at Object.next (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:3:12)\n    at SubjectOperationExecutor.insert (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:342:16)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:167:116\n    at Array.map (<anonymous>)\n    at SubjectOperationExecutor.<anonymous> (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:167:78)\n    at step (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)\n    at Object.next (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)\n    at /app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:3:12)\n    at SubjectOperationExecutor.executeInsertOperations (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:157:16)\n    at SubjectOperationExecutor.<anonymous> (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:97:51)\n    at step (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:32:23)\n    at Object.next (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:13:53)\n    at fulfilled (/app/node_modules/typeorm/persistence/SubjectOperationExecutor.js:4:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    }
}
```

### Example repository

N/A

**Comment by svenefftinge** [comment]
> Before I get into things, please let me know if this is a good place to report issues with master builds

This is the perfect place for filing such issues. Thanks for all the details.

**Comment by jimmybrancaccio** [comment]
After some research and investigation it appears the value of `material` inside `chart/secrets/encryption-key.json` needs to be set to either a 44 character base 64 string or 64 character hex string ([source](https://crypto.stackexchange.com/a/34886)).

This is definitely something that we should get documented 😁  So if anything this case could be used as a reminder to document that.
