### ISSUE TITLE
VS Code extension doesn't work for some reason 

### ISSUE THREAD

**Issue by vymarkov** [gitpod-io/gitpod#2640]
### Describe the bug

I can't use this extension due to issue with code editor [GitLab: Configure access to GitLab NPM Registry
](https://open-vsx.org/extension/vymarkov/add-gitlab-npm-token). This extension works as expected on VS Code from Microsoft (version 1.49.3)

### Steps to reproduce

1. Go to settings and set code as default editor.
2. Open repo https://gitlab.com/gitlab-org/gitlab-vscode-extension (it could be any repo, doesn't matter)
3. Go to extensions and type `vymarkov` to find extension [GitLab: Configure access to GitLab NPM Registry
](https://open-vsx.org/extension/vymarkov/add-gitlab-npm-token)
![image](https://user-images.githubusercontent.com/1110697/103400303-49f09280-4b4d-11eb-905c-d199e3eb3503.png)
4. Install this extension then reload workspace.
5. Open command palate and type `Gitlab NPM Registry: Open User Settings to add a personal access token`
![image](https://user-images.githubusercontent.com/1110697/103400749-f3845380-4b4e-11eb-97fc-995a6b3c45f4.png)
6. Extension fails for some reason.
![image](https://user-images.githubusercontent.com/1110697/103400788-144ca900-4b4f-11eb-97c3-01733728fd3d.png)

### Expected behavior

VS Code is able to find needed command from extension without any issues.

### Additional information

Version: 1.49.0
Commit: 20ded0d97c41cb686098d14b9e1f0533177300d1
Date: 2020-12-17T09:27:27.064Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36 OPR/73.0.3856.284

![image](https://user-images.githubusercontent.com/1110697/103401079-385cba00-4b50-11eb-8043-df51af7e5d67.png)

I found out that code does't install `node_modules` for some reason for this extension that lead to issue during extension activation.

```log
[2020-12-31 07:59:11.090] [exthost] [error] Activating extension vymarkov.add-gitlab-npm-token failed due to an error:
[2020-12-31 07:59:11.096] [exthost] [error] Error: Cannot find module 'execa'
Require stack:
- /home/gitpod/.gitpod-code/extensions/vymarkov.add-gitlab-npm-token-0.0.9/out/commands.js
- /home/gitpod/.gitpod-code/extensions/vymarkov.add-gitlab-npm-token-0.0.9/out/extension.js
- /ide/out/vs/loader.js
- /ide/out/bootstrap-amd.js
- /ide/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
	at Function.Module._load (internal/modules/cjs/loader.js:686:27)
	at Function.Module._load (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:60829:33)
	at Function.load (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:58951:37)
	at Function.load [as _load] (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:58794:37)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Object.<anonymous> (/home/gitpod/.gitpod-code/extensions/vymarkov.add-gitlab-npm-token-0.0.9/out/commands.js:13:15)
	at Module._compile (internal/modules/cjs/loader.js:955:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
	at Module.load (internal/modules/cjs/loader.js:811:32)
	at Function.Module._load (internal/modules/cjs/loader.js:723:14)
	at Function.Module._load (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:60829:33)
	at Function.load (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:58951:37)
	at Function.load [as _load] (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:58794:37)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Object.<anonymous> (/home/gitpod/.gitpod-code/extensions/vymarkov.add-gitlab-npm-token-0.0.9/out/extension.js:17:20)
	at Module._compile (internal/modules/cjs/loader.js:955:30)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
	at Module.load (internal/modules/cjs/loader.js:811:32)
	at Function.Module._load (internal/modules/cjs/loader.js:723:14)
	at Function.Module._load (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:60829:33)
	at Function.load (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:58951:37)
	at Function.load [as _load] (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:58794:37)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.nodeRequire [as __$__nodeRequire] (/ide/out/vs/loader.js:1820:32)
	at ExtHostExtensionService._loadCommonJSModule (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:59002:29)
	at ExtHostExtensionService._doActivateExtension (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:53965:22)
	at ExtHostExtensionService._activateExtension (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:53939:25)
	at Object.actualActivateExtension (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:53816:33)
	at ExtensionsActivator._activateExtension (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40598:57)
	at /ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40583:58
	at Array.map (<anonymous>)
	at ExtensionsActivator._activateExtensions (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40583:42)
	at ExtensionsActivator.activateByEvent (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:40474:25)
	at ExtHostExtensionService._activateByEvent (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:53863:36)
	at /ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:54248:33
	at processTicksAndRejections (internal/process/task_queues.js:94:5)

```

### Example repository

https://gitlab.com/gitlab-org/gitlab-vscode-extension

**Comment by vymarkov** [comment]
I found the issue that lead to this error, `package-lock.json` was not included for some reason on package stage.

**Comment by akosyakov** [comment]
Are you sure that this extensions is properly published to open vsx? Meaning that vsxi file should contain all required node modules, Code does not do it magically on install

**Comment by sr229** [comment]
This doesn't look like Gitpod's fault so you might want to consult with the addon author to fix their OpenVSX extension.

**Comment by vymarkov** [comment]
I've fixed this issue, from my point of view, it's not obvious that node_modules must be included into vsxi file.

**Comment by svenefftinge** [comment]
I understood this is resolved now?
