### ISSUE TITLE
How to properly setup configuration to start gitpod server? 

### ISSUE THREAD

**Issue by vymarkov** [gitpod-io/gitpod#2992]
I've opened this repo by using Gitpod and Theia editor, then I run command `yarn start` from `./components/server`, but faced with issue that some of envs were missed. It looks like I have to do before to start server. I need help with that.

workspace id: **b39a2056-6778-444a-952c-9e2aa0b5e5f1**

```bash
gitpod /workspace/gitpod/components/server $ yarn start
yarn run v1.22.10
$ node ./dist/src/main.js
{"component":"server","severity":"INFO","time":"2021-01-22T13:36:30.426Z","message":"Initializing Jaeger Tracer with RemoteReporter and RemoteSampler(serviceName=server)","loggedViaConsole":true}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"server","version":"<ts-not-set>"},"stack_trace":"Error: Environment variable undefined or empty: KUBE_STAGE\n    at getEnvVar (/workspace/gitpod/components/gitpod-protocol/lib/env.js:45:15)\n    at getEnvVarParsed (/workspace/gitpod/components/gitpod-protocol/lib/env.js:58:19)\n    at new AbstractComponentEnv (/workspace/gitpod/components/gitpod-protocol/lib/env.js:24:26)\n    at new Env (/workspace/gitpod/components/server/dist/src/env.js:25:13)\n    at Object.resolveInstance (/workspace/gitpod/node_modules/inversify/lib/resolution/instantiation.js:45:18)\n    at /workspace/gitpod/node_modules/inversify/lib/resolution/resolver.js:72:42\n    at Array.map (<anonymous>)\n    at _injectProperties (/workspace/gitpod/node_modules/inversify/lib/resolution/instantiation.js:11:57)\n    at Object.resolveInstance (/workspace/gitpod/node_modules/inversify/lib/resolution/instantiation.js:42:18)\n    at /workspace/gitpod/node_modules/inversify/lib/resolution/resolver.js:72:42\n    at Object.resolve (/workspace/gitpod/node_modules/inversify/lib/resolution/resolver.js:96:12)\n    at /workspace/gitpod/node_modules/inversify/lib/container/container.js:319:37\n    at Container._get (/workspace/gitpod/node_modules/inversify/lib/container/container.js:310:44)\n    at Container.get (/workspace/gitpod/node_modules/inversify/lib/container/container.js:230:21)\n    at Object.<anonymous> (/workspace/gitpod/components/server/dist/src/init.js:72:34)\n    at Generator.next (<anonymous>)","component":"server","severity":"ERROR","time":"2021-01-22T13:36:30.433Z","message":"Error during startup or operation. Exiting.","error":"Error: Environment variable undefined or empty: KUBE_STAGE\n    at getEnvVar (/workspace/gitpod/components/gitpod-protocol/lib/env.js:45:15)\n    at getEnvVarParsed (/workspace/gitpod/components/gitpod-protocol/lib/env.js:58:19)\n    at new AbstractComponentEnv (/workspace/gitpod/components/gitpod-protocol/lib/env.js:24:26)\n    at new Env (/workspace/gitpod/components/server/dist/src/env.js:25:13)\n    at Object.resolveInstance (/workspace/gitpod/node_modules/inversify/lib/resolution/instantiation.js:45:18)\n    at /workspace/gitpod/node_modules/inversify/lib/resolution/resolver.js:72:42\n    at Array.map (<anonymous>)\n    at _injectProperties (/workspace/gitpod/node_modules/inversify/lib/resolution/instantiation.js:11:57)\n    at Object.resolveInstance (/workspace/gitpod/node_modules/inversify/lib/resolution/instantiation.js:42:18)\n    at /workspace/gitpod/node_modules/inversify/lib/resolution/resolver.js:72:42\n    at Object.resolve (/workspace/gitpod/node_modules/inversify/lib/resolution/resolver.js:96:12)\n    at /workspace/gitpod/node_modules/inversify/lib/container/container.js:319:37\n    at Container._get (/workspace/gitpod/node_modules/inversify/lib/container/container.js:310:44)\n    at Container.get (/workspace/gitpod/node_modules/inversify/lib/container/container.js:230:21)\n    at Object.<anonymous> (/workspace/gitpod/components/server/dist/src/init.js:72:34)\n    at Generator.next (<anonymous>)"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
![image](https://user-images.githubusercontent.com/1110697/105497933-30fc7c80-5cc8-11eb-8da0-b1e8ca2a3065.png)

**Comment by csweichel** [comment]
At this moment unfortunately, the Gitpod server does not run outside well its Kubernetes pod/deployment, that includes Gitpod workspaces. During development we'll usually have a Gitpod installation deployed in a development cluster, and then use the Node debugger or telepresence to work with that deployment.

For everyone without access to such a development cluster, we don't have a good contributor story yet unfortunately :/
