### ISSUE TITLE
Java Dependencies not displayed for a Java project

### ISSUE THREAD

**Issue by bhadreshdesai** [gitpod-io/gitpod#3244]
### Describe the bug
Java Dependencies not displayed for a Java project

### Steps to reproduce
Open the [spring-petclinic](https://github.com/spring-projects/spring-petclinic) github project using gitpod.

https://gitpod.io/#https://github.com/spring-projects/spring-petclinic

### Expected behavior
Java Dependencies is displayed correctly

### Additional information
I believe the built-in extension redhat.java should be updated to the latest version 0.75.0 and vscjava.vscode-java-dependency should be updated to 0.18.0

Language Support for Java error log
```Picked up JAVA_TOOL_OPTIONS: -Xmx1879m
[Error - 9:22:43 PM] Feb 19, 2021, 9:22:43 PM Failed to load extension bundles 
Load bundle list
org.eclipse.core.runtime.CoreException: Load bundle list
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:169)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:77)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:64)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:228)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:123)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Contains: Cannot extract bundle symbolicName or version /tmp/vscode-extensions/vscjava.vscode-java-dependency@0.9.0/extension/server/com.microsoft.jdtls.ext.core-0.9.0.jar
java.nio.file.NoSuchFileException: /tmp/vscode-extensions/vscjava.vscode-java-dependency@0.9.0/extension/server/com.microsoft.jdtls.ext.core-0.9.0.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1253)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:746)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:863)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:261)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:319)
	at java.base/java.util.jar.JarFile.<init>(JarFile.java:258)
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.getBundleInfo(BundleUtils.java:302)
	at org.eclipse.jdt.ls.core.internal.handlers.BundleUtils.loadBundles(BundleUtils.java:116)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler.handleInitializationOptions(InitHandler.java:77)
	at org.eclipse.jdt.ls.core.internal.handlers.BaseInitHandler.initialize(BaseInitHandler.java:64)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.initialize(JDTLanguageServer.java:228)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.jdt.ls.core.internal.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:123)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Example repository
https://github.com/spring-projects/spring-petclinic

### Workaround
Add redhat.java and vscjava.vscode-java-dependency to your .gitpod.yml

Refresh the browser after opening the workspace.

See the following forked repo as an example

https://gitpod.io/#https://github.com/bhadreshdesai/spring-petclinic

**Comment by bhadreshdesai** [comment]
Am I correct in assuming that the builtin plugin versions can be updated by updating the following file.

https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-protocol/data/builtin-theia-plugins.json

If someone can confirm I can create a PR.

Thanks

**Comment by geropl** [comment]
> I am not sure how to test my changes. If someone could help me, I could test and create a PR.

Unfortunately, there is now way to for non-Gitpod employees to test this easily, yet (cannot find the issue atm).

The best way to go forward with this is to create the PR, then we can test and approve.

**Comment by bhadreshdesai** [comment]
@geropl I have created the PR. https://github.com/gitpod-io/gitpod/pull/3281

Thanks.

**Comment by geropl** [comment]
Tested and merged. Thx!

**Comment by akosyakov** [comment]
It was resolved by https://github.com/gitpod-io/gitpod/pull/3281
