### ISSUE TITLE
[docker-in-ws] Starting a docker image pulled during prebuild doesn't work

### ISSUE THREAD

**Issue by svenefftinge** [gitpod-io/gitpod#3434]
### Bug description

For [this repo](https://github.com/svenefftinge/try-jetbrains-projektor), I can start the docker without problems when I run this without a prebuild.
But when I use prebuilds (main branch is prebuilt). I get file permission issues:

```
+ cd /projector/ide/bin
+ ./ide-projector-launcher.sh
Found IDE: idea
/bin/mktemp: failed to create file via template '/tmp/java.version.log.XXXXXX': Permission denied
idea-projector.sh: line 153: : No such file or directory
grep: : No such file or directory
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[DEBUG] :: IdeState :: Starting attempts to attach IJ injector agent
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.jetbrains.projector.server.ProjectorServer$Companion.startServer(ProjectorServer.kt:746)
        at org.jetbrains.projector.server.ProjectorLauncher.runProjectorServer(ProjectorLauncher.kt:68)
        at org.jetbrains.projector.server.ProjectorLauncher.main(ProjectorLauncher.kt:38)
Caused by: java.io.IOException: Permission denied
        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
```

### Steps to reproduce

 - start workspace on https://gitpod.io/#https://github.com/svenefftinge/try-jetbrains-projektor and see how the command task fails.
 - create a fork of the same repo and push a change to invalidate the prebuild. See how the same task succeeds.

### Example repository

https://github.com/svenefftinge/try-jetbrains-projektor

**Comment by svenefftinge** [comment]
It works in staging already
