### ISSUE TITLE
Terminals aren't reconnected on Code reload

### ISSUE THREAD

**Issue by AlexTugarev** [gitpod-io/gitpod#3461]
### Bug description

When working with Code, and loosing the connection (for unknown reason,) you will be asked to reload the window. Once done, it reloads but without reconnecting to terminals. If you've started any long running processes, they are "hidden" in background now, and potentially blocking ports.

### Steps to reproduce

1. run a dev server
2. try to provoke a reconnect (don't know how to do so)
3. after reload try to restart the dev server, see the port is blocked.

### Expected behavior

After reload, the terminals are reconnected properly, and surfacing the control over previously started processes.

/cc. @akosyakov

**Comment by akosyakov** [comment]
A workaround:
```
/.supervisor/supervisor terminal list
/.supervisor/supervisor terminal attach -ir ${alias}
```

**Comment by akosyakov** [comment]
```
{"alias":"48b0897e-19e1-461d-a995-389df277bdfd","level":"info","message":"terminal client left","serviceContext":{"service":"supervisor","version":""},"severity":"INFO","time":"2021-03-19T13:05:20Z"}
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","error":"rpc error: code = Internal desc = rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called","grpc.code":"Internal","grpc.method":"Listen","grpc.service":"supervisor.TerminalService","grpc.start_time":"2021-03-19T13:05:20Z","grpc.time_ms":1.862,"level":"error","message":"finished streaming call with code Internal","serviceContext":{"service":"supervisor","version":""},"severity":"ERROR","span.kind":"server","system":"grpc","time":"2021-03-19T13:05:20Z"}
[90m[main 2021-03-19T13:05:20.427Z][0m [bb09635a-ba84-49e8-b720-6296e74bd5c3] Extension host is started.
[91m[main 2021-03-19T13:05:20.442Z][0m code server: 3:48b0897e-19e1-461d-a995-389df277bdfd terminal: listening failed: Error: 13 INTERNAL: transport: transport: the stream is done or WriteHeader was already called
    at Object.callErrorFromStatus (/ide/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/ide/node_modules/@grpc/grpc-js/build/src/client.js:327:49)
    at Object.onReceiveStatus (/ide/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:297:181)
    at /ide/node_modules/@grpc/grpc-js/build/src/call-stream.js:130:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 13,
  details: 'transport: transport: the stream is done or WriteHeader was already called',
  metadata: Metadata { internalRepr: Map {}, options: {} }
}
```

From logs then Gitpod Code Server fails listening to the supervisor terminal,  probably we should retry listening.

**Comment by akosyakov** [comment]
oh, that's simply a typo 😬 : https://github.com/gitpod-io/vscode/blob/gp-code/src/vs/gitpod/node/supervisorTerminalProcess.ts#L206 It always returns true, should be `=== 'number'` instead
