### ISSUE TITLE
[server] Unexpected error - WorkspaceStarter.startWorkspace

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#3544]
### Bug description
```console
"TypeError: Cannot read property 'filter' of null
    at WorkspaceStarter.<anonymous> (/app/node_modules/@gitpod/server/dist/src/workspace/workspace-starter.js:245:85)
    at Generator.next (<anonymous>)
    at /app/node_modules/@gitpod/server/dist/src/workspace/workspace-starter.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@gitpod/server/dist/src/workspace/workspace-starter.js:18:12)
    at WorkspaceStarter.newInstance (/app/node_modules/@gitpod/server/dist/src/workspace/workspace-starter.js:228:20)
    at WorkspaceStarter.<anonymous> (/app/node_modules/@gitpod/server/dist/src/workspace/workspace-starter.js:85:100)
    at Generator.next (<anonymous>)
    at /app/node_modules/@gitpod/server/dist/src/workspace/workspace-starter.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@gitpod/server/dist/src/workspace/workspace-starter.js:18:12)
    at WorkspaceStarter.startWorkspace (/app/node_modules/@gitpod/server/dist/src/workspace/workspace-starter.js:55:20)
    at Proxy.<anonymous> (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:395:56)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/@gitpod/server/dist/src/workspace/gitpod-server-impl.js:19:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
```
### Steps to reproduce

-

### Expected behavior

No error

### Example repository

-

**Comment by aledbf** [comment]
Closing. I cannot reproduce anymore.
