### ISSUE TITLE
ws-manager-bridge keeps crashing after restart

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#3555]
After `ws-manager-bridge` (or `messagebus`?) restarted, bridge often gets stuck in a crash-restart-loop with the following error:

```
Error: Operation failed: ExchangeBind; 404 (NOT-FOUND) with message "NOT_FOUND - no exchange 'gitpod.ws.local' in vhost '/'"
    at reply (/app/node_modules/amqplib/lib/channel.js:127:17)
    at ConfirmChannel.C.accept (/app/node_modules/amqplib/lib/channel.js:401:7)
    at Connection.mainAccept [as accept] (/app/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/app/node_modules/amqplib/lib/connection.js:477:48)
    at Socket.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:555:12)
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

**Comment by meysholdt** [comment]
Potential solution: Refactor the following lines

https://github.com/gitpod-io/gitpod/blob/6e48d216724194e09e9e56b7fc52aa7eda394c0b/components/gitpod-messagebus/configure.sh#L7-L15


To make use of a `definitions.json` as described in
* https://stackoverflow.com/q/58266688
* https://devops.datenkollektiv.de/creating-a-custom-rabbitmq-container-with-preconfigured-queues.html
