### ISSUE TITLE
Personal Fork Workspace Encounters Errors

### ISSUE THREAD

**Issue by ShaunSHamilton** [gitpod-io/gitpod#3655]
### Bug description

I have been using GitPod to develop on freeCodeCamp, for a long time. We recently did a lot of upgrades, and, one day, my workspaces stopped working as expected. Just my workspaces attached to my fork - I have opened instances on others' forks, and not experienced the issue.

Something appears to prevent webpack from accessing a file.

<details>
  
  <summary>Error</summary>

```console
success Building development bundle - 99.732s

Couldn't read the file /workspace/freeCodeCamp/client, possibly due to source maps failing
original error Error: ENOENT: no such file or directory, open '//public/webpack.stats.json'
    at Object.openSync (fs.js:476:3)
    at Object.fs [as readFileSync] (fs.js:377:35)
    at /workspace/freeCodeCamp/client/public/webpack:/@freecodecamp/client/.cache/ssr-develop-static-entry.js:24:3
    at /workspace/freeCodeCamp/client/public/render-page.js:410321:3
    at Object.<anonymous> (/workspace/freeCodeCamp/client/public/render-page.js:410326:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '//public/webpack.stats.json'
Failed to validate error [Error [ValidationError]: "type" must be one of
[GRAPHQL, CONFIG, WEBPACK, PLUGIN]] {
  _original: {
    '0': 'E',
    '1': 'N',
    '2': 'O',
    '3': 'E',
    '4': 'N',
    '5': 'T',
    '6': ':',
    '7': ' ',
    '8': 'n',
    '9': 'o',
    '10': ' ',
    '11': 's',
    '12': 'u',
    '13': 'c',
    '14': 'h',
    '15': ' ',
    '16': 'f',
    '17': 'i',
    '18': 'l',
    '19': 'e',
    '20': ' ',
    '21': 'o',
    '22': 'r',
    '23': ' ',
    '24': 'd',
    '25': 'i',
    '26': 'r',
    '27': 'e',
    '28': 'c',
    '29': 't',
    '30': 'o',
    '31': 'r',
    '32': 'y',
    '33': ',',
    '34': ' ',
    '35': 'o',
    '36': 'p',
    '37': 'e',
    '38': 'n',
    '39': ' ',
    '40': "'",
    '41': '/',
    '42': '/',
    '43': 'p',
    '44': 'u',
    '45': 'b',
    '46': 'l',
    '47': 'i',
    '48': 'c',
    '49': '/',
    '50': 'w',
    '51': 'e',
    '52': 'b',
    '53': 'p',
    '54': 'a',
    '55': 'c',
    '56': 'k',
    '57': '.',
    '58': 's',
    '59': 't',
    '60': 'a',
    '61': 't',
    '62': 's',
    '63': '.',
    '64': 'j',
    '65': 's',
    '66': 'o',
    '67': 'n',
    '68': "'",
    context: {},
    type: 'Error',
    stack: [],
    filename: '',
    message: "ENOENT: no such file or directory, open
'//public/webpack.stats.json'",
    text: 'There was an error',
    level: 'ERROR',
    docsUrl: 'https://gatsby.dev/issue-how-to'
  },
  details: [
    {
      message: '"type" must be one of [GRAPHQL, CONFIG, WEBPACK, PLUGIN]',
      path: [Array],
      type: 'any.only',
      context: [Object]
    }
  ]
}

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @freecodecamp/client@0.0.1 develop: `gatsby develop --inspect=9230 "-H" "0.0.0.0"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @freecodecamp/client@0.0.1 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitpod/.npm/_logs/2021-03-29T19_10_58_229Z-debug.log
```

</details>

Related Issue: https://github.com/freeCodeCamp/freeCodeCamp/issues/41581

I have tried on Feature Preview, and with it turned off. Same result.

### Steps to reproduce

1) Open any instance off fCC GitPod off of my fork: https://github.com/ShaunSHamilton/freeCodeCamp
2) Wait for client to finish developing
3) Open browser preview of app
4) See client crash with above error

### Expected behavior

Expected behaviour occurs on any other fork of the repo: https://github.com/freeCodeCamp/freeCodeCamp

This is just an issue with my fork, and we cannot explain it. My next debug step, if I cannot get help here, is to delete and refork the repo.

### Example repository

Base repo (works on GitPod): https://github.com/freeCodeCamp/freeCodeCamp
My fork (has bug): https://github.com/ShaunSHamilton/freeCodeCamp

**Comment by ShaunSHamilton** [comment]
GitPod team,

Apologies for any time wasted. The issue was caused by a Gatsby feature I was opted into.

Thank you, for your work on this product.
