### ISSUE TITLE
Server/Content Service fail when deleting non-existing workspace backup (which is a regular case)

### ISSUE THREAD

**Issue by geropl** [gitpod-io/gitpod#3772]
### Bug description

Server throws:
```
Error: 2 UNKNOWN: storage: object doesn't exist
    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/app/node_modules/grpc/src/client_interceptors.js:847:24)
```
`content-service` throws: `error deleting workspace backup: workspaces/green-gecko-zxdk2tuh/full.tar`

This is caused by a missing workspace backup. This itself is an error case for the workspace, but a regular case for the workspace GC. It should just happily move on instead.

### Steps to reproduce

---

### Expected behavior

`content-service` should happily return without throwing an error.

**Comment by csweichel** [comment]
A single workspace can then block the remainder of the GC run?
