### ISSUE TITLE
Unable to add tests for findAllWorkspaceAndInstances

### ISSUE THREAD

**Issue by mads-hartmann** [gitpod-io/gitpod#4122]
### Bug description

I was trying to write a test for my changes to `components/gitpod-db/src/typeorm/workspace-db-impl.ts`  in https://github.com/gitpod-io/gitpod/pull/4111. The specific method I'm modifying doesn't have any existing tests and when I added one it appeared to be failing for reasons unrelated to my code changes. I verified by creating a fresh branch off main to reproduce the problem (see [draft PR here](https://github.com/gitpod-io/gitpod/pull/4120) description for more details) 

### Steps to reproduce

To reproduce

1. Open a workspace from my draft PR that reproduces the issue: https://gitpod.io/#https://github.com/gitpod-io/gitpod/pull/4120
2. In one terminal `kubectl port-forward statefulset/mysql 23306:3306`
3. In another terminal `cd components/gitpod-db` and `yarn db-test`

### Expected behavior

I would have expected my new test to pass, or at least fail on the assertion rather than having an underlying exception being thrown

**Comment by mads-hartmann** [comment]
This is the output

```
gitpod /workspace/gitpod/components/gitpod-db $ yarn db-test
yarn run v1.22.10
$ r(){ export DB_ENCRYPTION_KEYS='[{"name":"general","version":1,"primary":true,"material":"5vRrp0H4oRgdkPnX1qQcS54Q0xggr6iyho42IQ1rO+c="}]';export DB_HOST=127.0.0.1;export DB_PORT=23306;export DB_USER=root;export DB_PASSWORD=test; yarn db-test-run; };r

$ mocha --opts mocha.opts '**/*.spec.db.ts'
Loading TypeORM entities and migrations from /workspace/gitpod/components/gitpod-db/src/typeorm
Using DB: 127.0.0.1:23306/gitpod


  CodeSyncResourceDBSpec
    ✓ insert (335ms)
    ✓ getResources (89ms)
    ✓ getManifest (89ms)
    ✓ roundRobinInsert (166ms)

  UserDBSpec
    ✓ createUserAndFindById (99ms)
    ✓ createUserAndNotFindByWrongId (57ms)
    ✓ createUserAndFindByIdentity (64ms)
    ✓ findUsersByEmail_multiple_users_identities (285ms)
    ✓ findUserByIdentity_after_moving_identity (144ms)

  UserMessageViewsDBSpec
    ✓ testSimple11
    ✓ testSimple2

  WorkspaceDBSpec
    ✓ testFindInstancesLast (78ms)
    1) testFindPrebuildsForGC_oldPrebuildNoUsage
    2) testFindPrebuildsForGC_newPrebuildNoUsage
    3) testFindPrebuildsForGC_oldPrebuildOldUsage
    4) testFindPrebuildsForGC_oldPrebuildNewUsage
    ✓ testFindWorkspacesForGarbageCollection
    ✓ testFindWorkspacesForGarbageCollection_no_instance
    ✓ testFindWorkspacesForGarbageCollection_latelyUsed
    5) testFindAllWorkspaceAndInstances_contextUrl


  15 passing (2s)
  5 failing

  1) WorkspaceDBSpec
       testFindPrebuildsForGC_oldPrebuildNoUsage:
     QueryFailedError: ER_BAD_NULL_ERROR: Column 'creationTime' cannot be null
      at new QueryFailedError (/workspace/gitpod/src/error/QueryFailedError.ts:7:9)
      at Query.<anonymous> (/workspace/gitpod/src/driver/mysql/MysqlQueryRunner.ts:202:37)
      at Query.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:502:10)
      at Query._callback (/workspace/gitpod/node_modules/mysql/lib/Connection.js:468:16)
      at Query.Sequence.end (/workspace/gitpod/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
      at Query.ErrorPacket (/workspace/gitpod/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
      at Protocol._parsePacket (/workspace/gitpod/node_modules/mysql/lib/protocol/Protocol.js:278:23)
      at Parser.write (/workspace/gitpod/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/workspace/gitpod/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:91:28)
      at Socket.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:502:10)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

  2) WorkspaceDBSpec
       testFindPrebuildsForGC_newPrebuildNoUsage:
     QueryFailedError: ER_BAD_NULL_ERROR: Column 'creationTime' cannot be null
      at new QueryFailedError (/workspace/gitpod/src/error/QueryFailedError.ts:7:9)
      at Query.<anonymous> (/workspace/gitpod/src/driver/mysql/MysqlQueryRunner.ts:202:37)
      at Query.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:502:10)
      at Query._callback (/workspace/gitpod/node_modules/mysql/lib/Connection.js:468:16)
      at Query.Sequence.end (/workspace/gitpod/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
      at Query.ErrorPacket (/workspace/gitpod/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
      at Protocol._parsePacket (/workspace/gitpod/node_modules/mysql/lib/protocol/Protocol.js:278:23)
      at Parser.write (/workspace/gitpod/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/workspace/gitpod/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:91:28)
      at Socket.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:502:10)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

  3) WorkspaceDBSpec
       testFindPrebuildsForGC_oldPrebuildOldUsage:
     QueryFailedError: ER_BAD_NULL_ERROR: Column 'creationTime' cannot be null
      at new QueryFailedError (/workspace/gitpod/src/error/QueryFailedError.ts:7:9)
      at Query.<anonymous> (/workspace/gitpod/src/driver/mysql/MysqlQueryRunner.ts:202:37)
      at Query.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:502:10)
      at Query._callback (/workspace/gitpod/node_modules/mysql/lib/Connection.js:468:16)
      at Query.Sequence.end (/workspace/gitpod/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
      at Query.ErrorPacket (/workspace/gitpod/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
      at Protocol._parsePacket (/workspace/gitpod/node_modules/mysql/lib/protocol/Protocol.js:278:23)
      at Parser.write (/workspace/gitpod/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/workspace/gitpod/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:91:28)
      at Socket.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:502:10)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

  4) WorkspaceDBSpec
       testFindPrebuildsForGC_oldPrebuildNewUsage:
     QueryFailedError: ER_BAD_NULL_ERROR: Column 'creationTime' cannot be null
      at new QueryFailedError (/workspace/gitpod/src/error/QueryFailedError.ts:7:9)
      at Query.<anonymous> (/workspace/gitpod/src/driver/mysql/MysqlQueryRunner.ts:202:37)
      at Query.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:502:10)
      at Query._callback (/workspace/gitpod/node_modules/mysql/lib/Connection.js:468:16)
      at Query.Sequence.end (/workspace/gitpod/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
      at Query.ErrorPacket (/workspace/gitpod/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
      at Protocol._parsePacket (/workspace/gitpod/node_modules/mysql/lib/protocol/Protocol.js:278:23)
      at Parser.write (/workspace/gitpod/node_modules/mysql/lib/protocol/Parser.js:76:12)
      at Protocol.write (/workspace/gitpod/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:91:28)
      at Socket.<anonymous> (/workspace/gitpod/node_modules/mysql/lib/Connection.js:502:10)
      at addChunk (_stream_readable.js:295:12)
      at readableAddChunk (_stream_readable.js:271:9)
      at Socket.Readable.push (_stream_readable.js:212:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:186:23)

  5) WorkspaceDBSpec
       testFindAllWorkspaceAndInstances_contextUrl:
     TypeError: Cannot read property 'databaseName' of undefined
      at /workspace/gitpod/src/query-builder/SelectQueryBuilder.ts:1765:99
      at Array.map (<anonymous>)
      at SelectQueryBuilder.createOrderByCombinedWithSelectExpression (/workspace/gitpod/src/query-builder/SelectQueryBuilder.ts:1760:14)
      at SelectQueryBuilder.<anonymous> (/workspace/gitpod/src/query-builder/SelectQueryBuilder.ts:1682:46)
      at step (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:42:23)
      at Object.next (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:23:53)
      at /workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:17:71
      at new Promise (<anonymous>)
      at __awaiter (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:13:12)
      at SelectQueryBuilder.executeEntitiesAndRawResults (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:1236:16)
      at SelectQueryBuilder.<anonymous> (/workspace/gitpod/src/query-builder/SelectQueryBuilder.ts:1004:31)
      at step (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:42:23)
      at Object.next (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:23:53)
      at /workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:17:71
      at new Promise (<anonymous>)
      at __awaiter (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:13:12)
      at SelectQueryBuilder.getRawAndEntities (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:592:16)
      at SelectQueryBuilder.<anonymous> (/workspace/gitpod/src/query-builder/SelectQueryBuilder.ts:1044:36)
      at step (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:42:23)
      at Object.next (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:23:53)
      at /workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:17:71
      at new Promise (<anonymous>)
      at __awaiter (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:13:12)
      at SelectQueryBuilder.getMany (/workspace/gitpod/node_modules/typeorm/query-builder/SelectQueryBuilder.js:650:16)
      at TransactionalWorkspaceDbImpl.<anonymous> (src/typeorm/workspace-db-impl.ts:1252:49)
      at step (src/typeorm/workspace-db-impl.ts:71:23)
      at Object.next (src/typeorm/workspace-db-impl.ts:52:53)
      at fulfilled (src/typeorm/workspace-db-impl.ts:43:58)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
