### ISSUE TITLE
Ports panel is stuck displaying "detecting..."

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#4572]
### Bug description

I never saw this problem before; I think if I'll re-open the workspace it will be fine.
But I wanted to report it -
![image](https://user-images.githubusercontent.com/22901/122932164-80101180-d33b-11eb-9539-91aa137a4fcf.png)

* update: *
The vscode IDE opened without my dark theme or my settings.
I cannot select `Gitpod: Stop workspace" from the main menu.
Here's the workspace url -
https://blue-loon-e0uhk1e2.ws-us08.gitpod.io/

### Steps to reproduce

I don't think opening this repo again will reproduce the problem, but here's the URL I used to access the repo -

https://gitpod.io/#DP_PROJECT_NAME=drupal,DP_ISSUE_FORK=drupal-3042417,DP_ISSUE_BRANCH=3042417-accessible-dropdown-for,DP_PROJECT_TYPE=project_core,DP_CORE_VERSION=9.2.0,DP_INSTALL_PROFILE=demo_umami/https://github.com/shaal/drupalpod

### Expected behavior

Normally the ports panel would display all the ports available.
(I am not running the Gitpod Local Companion)

### Anything else?

These messages were displayed in the browser's console, after I refreshed the page -
```
/start: started workspace instance: a1955d6b-fbec-4dd0-9046-c603c694401e
DevTools failed to load source map: Could not load content for https://blue-loon-e0uhk1e2.ws-us08.gitpod.io/node_modules/@gitpod/local-app-api-grpcweb/lib/localapp.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
manifest.json:1 Manifest: property 'start_url' ignored, should be same origin as document.
workbench.ts:371 GET https://blue-loon-e0uhk1e2.ws-us08.gitpod.io/_supervisor/v1/token/gitpod/gitpod.io/function:accessCodeSyncStorage 404
doStart @ workbench.ts:371
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
workbench.ts:378 Getting Gitpod token failed: 
doStart @ workbench.ts:378
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
reconnecting-websocket-mjs.js:482 WebSocket connection to 'ws://localhost:63100/localapp.LocalApp/TunnelStatus' failed: 
(anonymous) @ reconnecting-websocket-mjs.js:482
workbench.ts:518 cannot maintain connection to local app {code: 2, details: "Response closed without headers", metadata: e}
(anonymous) @ workbench.ts:518
async function (async)
(anonymous) @ workbench.ts:470
observeTunneled @ workbench.ts:524
doStart @ workbench.ts:535
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
reconnecting-websocket-mjs.js:482 WebSocket connection to 'ws://localhost:63100/localapp.LocalApp/TunnelStatus' failed: 
(anonymous) @ reconnecting-websocket-mjs.js:482
workbench.ts:518 cannot maintain connection to local app {code: 2, details: "Response closed without headers", metadata: e}
(anonymous) @ workbench.ts:518
async function (async)
(anonymous) @ workbench.ts:470
observeTunneled @ workbench.ts:524
doStart @ workbench.ts:535
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
reconnecting-websocket-mjs.js:482 WebSocket connection to 'ws://localhost:63100/localapp.LocalApp/TunnelStatus' failed: 
(anonymous) @ reconnecting-websocket-mjs.js:482
workbench.ts:518 cannot maintain connection to local app {code: 2, details: "Response closed without headers", metadata: e}
(anonymous) @ workbench.ts:518
async function (async)
(anonymous) @ workbench.ts:470
observeTunneled @ workbench.ts:524
doStart @ workbench.ts:535
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
console.ts:137 [Extension Host] connecting to notification service (at /ide/extensions/gitpod/dist/extension.js:18:332880)
console.ts:137 [Extension Host] Failed an initial GitHub login: Error: 5 NOT_FOUND: no token available
	at Object.t.callErrorFromStatus (/ide/extensions/gitpod/dist/extension.js:33:216636)
	at Object.onReceiveStatus (/ide/extensions/gitpod/dist/extension.js:18:195860)
	at Object.onReceiveStatus (/ide/extensions/gitpod/dist/extension.js:18:203834)
	at Object.onReceiveStatus (/ide/extensions/gitpod/dist/extension.js:18:203279)
	at /ide/extensions/gitpod/dist/extension.js:18:12662
	at processTicksAndRejections (internal/process/task_queues.js:75:11) (at /ide/extensions/gitpod/dist/extension.js:18:331515)
log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
(anonymous) @ browserSocketFactory.ts:178
fire @ event.ts:622
BrowserWebSocket._fileReader.onload @ browserSocketFactory.ts:62
load (async)
BrowserWebSocket @ browserSocketFactory.ts:58
create @ browserSocketFactory.ts:162
create @ workbench.ts:614
connect @ browserSocketFactory.ts:211
createSocket @ remoteAgentConnection.ts:191
connectToRemoteExtensionHostAgent @ remoteAgentConnection.ts:232
connectToRemoteExtensionHostAgentAndReadOneMessage @ remoteAgentConnection.ts:309
doConnectRemoteAgentExtensionHost @ remoteAgentConnection.ts:351
connectRemoteAgentExtensionHost @ remoteAgentConnection.ts:420
async function (async)
connectRemoteAgentExtensionHost @ remoteAgentConnection.ts:419
(anonymous) @ remoteExtensionHost.ts:128
Promise.then (async)
start @ remoteExtensionHost.ts:104
ExtensionHostManager @ extensionHostManager.ts:68
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
(anonymous) @ abstractExtensionService.ts:526
_startExtensionHosts @ abstractExtensionService.ts:525
_initialize @ abstractExtensionService.ts:429
(anonymous) @ extensionService.ts:78
async function (async)
(anonymous) @ extensionService.ts:77
Promise.then (async)
ExtensionService @ extensionService.ts:76
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
get @ instantiationService.ts:54
initLayout @ layout.ts:252
(anonymous) @ workbench.ts:141
invokeFunction @ instantiationService.ts:61
startup @ workbench.ts:134
open @ web.main.ts:96
async function (async)
open @ web.main.ts:87
main @ web.main.ts:378
create @ workbench.web.api.ts:512
doStart @ workbench.ts:606
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
reconnecting-websocket-mjs.js:482 WebSocket connection to 'ws://localhost:63100/localapp.LocalApp/TunnelStatus' failed: 
(anonymous) @ reconnecting-websocket-mjs.js:482
workbench.ts:518 cannot maintain connection to local app {code: 2, details: "Response closed without headers", metadata: e}
(anonymous) @ workbench.ts:518
async function (async)
(anonymous) @ workbench.ts:470
observeTunneled @ workbench.ts:524
doStart @ workbench.ts:535
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error: 5 NOT_FOUND: no token available (at /ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:67347:41)
log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
(anonymous) @ browserSocketFactory.ts:178
fire @ event.ts:622
BrowserWebSocket._fileReader.onload @ browserSocketFactory.ts:62
load (async)
BrowserWebSocket @ browserSocketFactory.ts:58
create @ browserSocketFactory.ts:162
create @ workbench.ts:614
connect @ browserSocketFactory.ts:211
createSocket @ remoteAgentConnection.ts:191
connectToRemoteExtensionHostAgent @ remoteAgentConnection.ts:232
connectToRemoteExtensionHostAgentAndReadOneMessage @ remoteAgentConnection.ts:309
doConnectRemoteAgentExtensionHost @ remoteAgentConnection.ts:351
connectRemoteAgentExtensionHost @ remoteAgentConnection.ts:420
async function (async)
connectRemoteAgentExtensionHost @ remoteAgentConnection.ts:419
(anonymous) @ remoteExtensionHost.ts:128
Promise.then (async)
start @ remoteExtensionHost.ts:104
ExtensionHostManager @ extensionHostManager.ts:68
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
(anonymous) @ abstractExtensionService.ts:526
_startExtensionHosts @ abstractExtensionService.ts:525
_initialize @ abstractExtensionService.ts:429
(anonymous) @ extensionService.ts:78
async function (async)
(anonymous) @ extensionService.ts:77
Promise.then (async)
ExtensionService @ extensionService.ts:76
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
get @ instantiationService.ts:54
initLayout @ layout.ts:252
(anonymous) @ workbench.ts:141
invokeFunction @ instantiationService.ts:61
startup @ workbench.ts:134
open @ web.main.ts:96
async function (async)
open @ web.main.ts:87
main @ web.main.ts:378
create @ workbench.web.api.ts:512
doStart @ workbench.ts:606
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
console.ts:137 [Extension Host] stack trace: Error: 5 NOT_FOUND: no token available	at Object.t.callErrorFromStatus (/ide/extensions/gitpod/dist/extension.js:33:216636)	at Object.onReceiveStatus (/ide/extensions/gitpod/dist/extension.js:18:195860)	at Object.onReceiveStatus (/ide/extensions/gitpod/dist/extension.js:18:203834)	at Object.onReceiveStatus (/ide/extensions/gitpod/dist/extension.js:18:203279)	at /ide/extensions/gitpod/dist/extension.js:18:12662	at processTicksAndRejections (internal/process/task_queues.js:75:11) (at /ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:67349:45)
log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
(anonymous) @ browserSocketFactory.ts:178
fire @ event.ts:622
BrowserWebSocket._fileReader.onload @ browserSocketFactory.ts:62
load (async)
BrowserWebSocket @ browserSocketFactory.ts:58
create @ browserSocketFactory.ts:162
create @ workbench.ts:614
connect @ browserSocketFactory.ts:211
createSocket @ remoteAgentConnection.ts:191
connectToRemoteExtensionHostAgent @ remoteAgentConnection.ts:232
connectToRemoteExtensionHostAgentAndReadOneMessage @ remoteAgentConnection.ts:309
doConnectRemoteAgentExtensionHost @ remoteAgentConnection.ts:351
connectRemoteAgentExtensionHost @ remoteAgentConnection.ts:420
async function (async)
connectRemoteAgentExtensionHost @ remoteAgentConnection.ts:419
(anonymous) @ remoteExtensionHost.ts:128
Promise.then (async)
start @ remoteExtensionHost.ts:104
ExtensionHostManager @ extensionHostManager.ts:68
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
(anonymous) @ abstractExtensionService.ts:526
_startExtensionHosts @ abstractExtensionService.ts:525
_initialize @ abstractExtensionService.ts:429
(anonymous) @ extensionService.ts:78
async function (async)
(anonymous) @ extensionService.ts:77
Promise.then (async)
ExtensionService @ extensionService.ts:76
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
get @ instantiationService.ts:54
initLayout @ layout.ts:252
(anonymous) @ workbench.ts:141
invokeFunction @ instantiationService.ts:61
startup @ workbench.ts:134
open @ web.main.ts:96
async function (async)
open @ web.main.ts:87
main @ web.main.ts:378
create @ workbench.web.api.ts:512
doStart @ workbench.ts:606
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
mainThreadExtensionService.ts:61 [[object Object]]5 NOT_FOUND: no token available
$onExtensionRuntimeError @ mainThreadExtensionService.ts:61
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
(anonymous) @ browserSocketFactory.ts:178
fire @ event.ts:622
BrowserWebSocket._fileReader.onload @ browserSocketFactory.ts:62
load (async)
BrowserWebSocket @ browserSocketFactory.ts:58
create @ browserSocketFactory.ts:162
create @ workbench.ts:614
connect @ browserSocketFactory.ts:211
createSocket @ remoteAgentConnection.ts:191
connectToRemoteExtensionHostAgent @ remoteAgentConnection.ts:232
connectToRemoteExtensionHostAgentAndReadOneMessage @ remoteAgentConnection.ts:309
doConnectRemoteAgentExtensionHost @ remoteAgentConnection.ts:351
connectRemoteAgentExtensionHost @ remoteAgentConnection.ts:420
async function (async)
connectRemoteAgentExtensionHost @ remoteAgentConnection.ts:419
(anonymous) @ remoteExtensionHost.ts:128
Promise.then (async)
start @ remoteExtensionHost.ts:104
ExtensionHostManager @ extensionHostManager.ts:68
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
(anonymous) @ abstractExtensionService.ts:526
_startExtensionHosts @ abstractExtensionService.ts:525
_initialize @ abstractExtensionService.ts:429
(anonymous) @ extensionService.ts:78
async function (async)
(anonymous) @ extensionService.ts:77
Promise.then (async)
ExtensionService @ extensionService.ts:76
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
get @ instantiationService.ts:54
initLayout @ layout.ts:252
(anonymous) @ workbench.ts:141
invokeFunction @ instantiationService.ts:61
startup @ workbench.ts:134
open @ web.main.ts:96
async function (async)
open @ web.main.ts:87
main @ web.main.ts:378
create @ workbench.web.api.ts:512
doStart @ workbench.ts:606
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
mainThreadExtensionService.ts:62 Error: 5 NOT_FOUND: no token available
	at Object.t.callErrorFromStatus (/ide/extensions/gitpod/dist/extension.js:33)
	at Object.onReceiveStatus (/ide/extensions/gitpod/dist/extension.js:18)
	at Object.onReceiveStatus (/ide/extensions/gitpod/dist/extension.js:18)
	at Object.onReceiveStatus (/ide/extensions/gitpod/dist/extension.js:18)
	at /ide/extensions/gitpod/dist/extension.js:18
	at processTicksAndRejections (/internal/process/task_queues.js:75)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:62
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
(anonymous) @ browserSocketFactory.ts:178
fire @ event.ts:622
BrowserWebSocket._fileReader.onload @ browserSocketFactory.ts:62
load (async)
BrowserWebSocket @ browserSocketFactory.ts:58
create @ browserSocketFactory.ts:162
create @ workbench.ts:614
connect @ browserSocketFactory.ts:211
createSocket @ remoteAgentConnection.ts:191
connectToRemoteExtensionHostAgent @ remoteAgentConnection.ts:232
connectToRemoteExtensionHostAgentAndReadOneMessage @ remoteAgentConnection.ts:309
doConnectRemoteAgentExtensionHost @ remoteAgentConnection.ts:351
connectRemoteAgentExtensionHost @ remoteAgentConnection.ts:420
async function (async)
connectRemoteAgentExtensionHost @ remoteAgentConnection.ts:419
(anonymous) @ remoteExtensionHost.ts:128
Promise.then (async)
start @ remoteExtensionHost.ts:104
ExtensionHostManager @ extensionHostManager.ts:68
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
(anonymous) @ abstractExtensionService.ts:526
_startExtensionHosts @ abstractExtensionService.ts:525
_initialize @ abstractExtensionService.ts:429
(anonymous) @ extensionService.ts:78
async function (async)
(anonymous) @ extensionService.ts:77
Promise.then (async)
ExtensionService @ extensionService.ts:76
_createInstance @ instantiationService.ts:110
_createServiceInstance @ instantiationService.ts:230
_createServiceInstanceWithOwner @ instantiationService.ts:219
_createAndCacheServiceInstance @ instantiationService.ts:208
_safeCreateAndCacheServiceInstance @ instantiationService.ts:151
_getOrCreateServiceInstance @ instantiationService.ts:135
get @ instantiationService.ts:54
initLayout @ layout.ts:252
(anonymous) @ workbench.ts:141
invokeFunction @ instantiationService.ts:61
startup @ workbench.ts:134
open @ web.main.ts:96
async function (async)
open @ web.main.ts:87
main @ web.main.ts:378
create @ workbench.web.api.ts:512
doStart @ workbench.ts:606
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
reconnecting-websocket-mjs.js:482 WebSocket connection to 'ws://localhost:63100/localapp.LocalApp/TunnelStatus' failed: 
(anonymous) @ reconnecting-websocket-mjs.js:482
workbench.ts:518 cannot maintain connection to local app {code: 2, details: "Response closed without headers", metadata: e}code: 2details: "Response closed without headers"metadata: e {headersMap: {…}}__proto__: Object
(anonymous) @ workbench.ts:518
async function (async)
(anonymous) @ workbench.ts:470
observeTunneled @ workbench.ts:524
doStart @ workbench.ts:535
async function (async)
doStart @ workbench.ts:239
start @ workbench.ts:221
start @ workbench.ts:720
c @ ide-frontend-service-impl.js:31
start @ ide-frontend-service-impl.js:63
(anonymous) @ index.js:122
(anonymous) @ index.js:38
(anonymous) @ index.js:19
s @ index.js:10
Promise.then (async)
u @ index.js:12
s @ index.js:10
Promise.then (async)
u @ index.js:12
(anonymous) @ index.js:13
r @ index.js:9
(anonymous) @ index.js:83
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ main.js:1
workbench.ts:459 could not connect to local app 5 times, giving up, use 'Gitpod: Connect to Local App' command to retry
```

**Comment by akosyakov** [comment]
From logs it looks like Gitpod components within your workspace gets unresponsive, so setting sync timeout. About ports it can happen from time to time that k8s receive to many requests and cannot serve all of them, then detecting ports will hang. We introduce ability to refresh port exposure for individual ports in June release: https://github.com/gitpod-io/gitpod/pull/4565

**Comment by shaal** [comment]
I'd like to reopen this issue.

I've seen this problem many times, as well as for other users, where Gitpod workspace open, VSCode interface is displayed, but the menu is missing all the Gitpod actions, and the terminal is unusable.

The workaround is simply refreshing the browser tab and everything goes back to normal.
This problem is unpredictable and very confusing for users.
What kind of information would be helpful, the next time I see it? (I think I see it at least once a day)

**Comment by akosyakov** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/7863
