### ISSUE TITLE
Fail to install pelican using pip3

### ISSUE THREAD

**Issue by dclong** [gitpod-io/gitpod#460]
**Describe the bug**
Fail to install the Python package pelican using pip3.

**To Reproduce**
1. Open a workspace with Gitpod's office image. 

2. Run the following command.  
```
pip3 install pelican
```
which generates the following error messages.
```
/home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pip/_internal/commands/install.py:207: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting pelican
  Downloading https://files.pythonhosted.org/packages/ac/16/7d3e5cef02c16c0a8ce5fb3a8790f0d193e954743b1177eb582107c3196d/pelican-4.0.1.tar.gz (411kB)
    100% |████████████████████████████████| 419kB 5.0MB/s
Collecting feedgenerator>=1.9 (from pelican)
  Downloading https://files.pythonhosted.org/packages/eb/02/7069b3dbc6ea92f034e07f9f9adc2193cd02d1aedf2cf9ec71150102a964/feedgenerator-1.9.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 2.5MB/s
Collecting jinja2>=2.7 (from pelican)
  Downloading https://files.pythonhosted.org/packages/93/ea/d884a06f8c7f9b7afbc8138b762e80479fb17aedbbe2b06515a12de9378d/Jinja2-2.10.1.tar.gz (260kB)
    100% |████████████████████████████████| 266kB 15.4MB/s
Collecting pygments (from pelican)
  Downloading https://files.pythonhosted.org/packages/64/69/413708eaf3a64a6abb8972644e0f20891a55e621c6759e2c3f3891e05d63/Pygments-2.3.1.tar.gz (3.1MB)
    100% |████████████████████████████████| 3.1MB 3.4MB/s
Collecting docutils (from pelican)
  Downloading https://files.pythonhosted.org/packages/84/f4/5771e41fdf52aabebbadecc9381d11dea0fa34e4759b4071244fa094804c/docutils-0.14.tar.gz (1.7MB)
    100% |████████████████████████████████| 1.7MB 5.9MB/s
Collecting pytz>=0a (from pelican)
  Downloading https://files.pythonhosted.org/packages/af/be/6c59e30e208a5f28da85751b93ec7b97e4612268bb054d0dff396e758a90/pytz-2018.9.tar.gz (310kB)
    100% |████████████████████████████████| 317kB 16.5MB/s
Collecting blinker (from pelican)
  Downloading https://files.pythonhosted.org/packages/1b/51/e2a9f3b757eb802f61dc1f2b09c8c99f6eb01cf06416c0671253536517b6/blinker-1.4.tar.gz (111kB)
    100% |████████████████████████████████| 112kB 31.5MB/s
Collecting unidecode (from pelican)
  Downloading https://files.pythonhosted.org/packages/9b/d8/c1b658ed7ff6e63a745eda483d7d917eb63a79c59fcb422469b85ff47e94/Unidecode-1.0.23.tar.gz (210kB)
    100% |████████████████████████████████| 215kB 29.6MB/s
Collecting six>=1.4 (from pelican)
  Downloading https://files.pythonhosted.org/packages/dd/bf/4138e7bfb757de47d1f4b6994648ec67a51efe58fa907c1e11e350cddfca/six-1.12.0.tar.gz
Collecting python-dateutil (from pelican)
  Downloading https://files.pythonhosted.org/packages/ad/99/5b2e99737edeb28c71bcbec5b5dda19d0d9ef3ca3e92e3e925e7c0bb364c/python-dateutil-2.8.0.tar.gz (327kB)
    100% |████████████████████████████████| 327kB 32.0MB/s
  Installing build dependencies ... error
  Complete output from command /home/gitpod/.pyenv/versions/3.7.2/bin/python3.7 /home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-aflsmxfb/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- "setuptools; python_version != '3.3'" "setuptools<40.0; python_version == '3.3'" wheel setuptools_scm:
  Ignoring setuptools: markers 'python_version == "3.3"' don't match your environment
  Collecting setuptools
    Downloading https://files.pythonhosted.org/packages/ed/69/c805067de1feedbb98c53174b0f2df44cc05e0e9ee73bb85eebc59e508c6/setuptools-41.0.0.zip (848kB)
  Collecting wheel
    Downloading https://files.pythonhosted.org/packages/b7/cf/1ea0f5b3ce55cacde1e84cdde6cee1ebaff51bd9a3e6c7ba4082199af6f6/wheel-0.33.1.tar.gz
  Collecting setuptools_scm
    Downloading https://files.pythonhosted.org/packages/54/85/514ba3ca2a022bddd68819f187ae826986051d130ec5b972076e4f58a9f3/setuptools_scm-3.2.0.tar.gz
  Installing collected packages: setuptools, wheel, setuptools-scm
    Running setup.py install for setuptools: started
      Running setup.py install for setuptools: finished with status 'error'
      Complete output from command /home/gitpod/.pyenv/versions/3.7.2/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-fhagshtv/setuptools/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1r9akx_6/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-aflsmxfb/overlay --compile --install-scripts=/workspace/.pip-global/bin --home=/tmp/pip-target-30bzn6ja:
      running install
      error: must supply either home or prefix/exec-prefix -- not both

      ----------------------------------------
  /home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pip/_internal/commands/install.py:207: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
    cmdoptions.check_install_build_global(options)
  Command "/home/gitpod/.pyenv/versions/3.7.2/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-fhagshtv/setuptools/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1r9akx_6/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-aflsmxfb/overlay --compile --install-scripts=/workspace/.pip-global/bin --home=/tmp/pip-target-30bzn6ja" failed with error code 1 in /tmp/pip-install-fhagshtv/setuptools/

  ----------------------------------------
Command "/home/gitpod/.pyenv/versions/3.7.2/bin/python3.7 /home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-aflsmxfb/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- "setuptools; python_version != '3.3'" "setuptools<40.0; python_version == '3.3'" wheel setuptools_scm" failed with error code 1 in None
```
**Expected behavior**
The Python package `pelican` should be installed without any issue.

**Comment by akosyakov** [comment]
cc @AlexTugarev

**Comment by AlexTugarev** [comment]
`python-dateutil` is the problematic package here. I'm checking what's wrong with it.

**Comment by AlexTugarev** [comment]
Apparently using custom `install-options` to move build scripts below `/workspace` directory disables wheels, cf. output:

> Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.

Because of that the `setup.py` is running instead of simply pulling the `whl`s. When it comes to the `wheel` dependency it fails with this:

```
  Traceback (most recent call last):
    File "/home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 179, in main
      status = self.run(options, args)
    File "/home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 401, in run
      isolated=options.isolated_mode,
    File "/home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 529, in get_lib_location_guesses
      scheme = distutils_scheme('', *args, **kwargs)
    File "/home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/site-packages/pip/_internal/locations.py", line 180, in distutils_scheme
      i.finalize_options()
    File "/home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/distutils/command/install.py", line 248, in finalize_options
      "must supply either home or prefix/exec-prefix -- not both")
```

It seems to be caused by this kind of commands:

```
Running command /home/gitpod/.pyenv/versions/3.7.2/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ecyla7qo/setuptools-scm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-7xxmw8n7/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-qj0blfib/overlay --compile --install-scripts=/workspace/.pip-global/bin --prefix= --home=/tmp/pip-target-pxvk0058
```

I have no idea why it includes both, `home` and `prefix`. Also setting `--prefix=` – as suggested on on SO posts – didn't work either, as it seems to be appended instead fo being replaced.

I verified that it works in general by disabling the script options:
`OPTS=$PIP_INSTALL_OPTION; unset PIP_INSTALL_OPTION; pip3 install pelican; export PIP_INSTALL_OPTION=$OPTS`

**Comment by AlexTugarev** [comment]
For completenesses, here is the underlying issue which caused the introduction of custom install options: https://github.com/pypa/pip/issues/3934. Unfortunately, the PR https://github.com/pypa/pip/pull/5983 hasn't been updated for a while.

**Comment by dclong** [comment]
@AlexTugarev You solution works as a temporary fix.

**Comment by AlexTugarev** [comment]
@dclong, we're currently testing a proper solution for this.
