### ISSUE TITLE
Cannot create python venv

### ISSUE THREAD

**Issue by iksaif** [gitpod-io/gitpod#468]
**Describe the bug**

Creating a python 3 venv fails.

**To Reproduce**
```
$ virtualenv venv -p python3.7
Running virtualenv with interpreter /home/gitpod/.pyenv/shims/python3.7
Using base prefix '/home/gitpod/.pyenv/versions/3.7.2'
New python executable in /workspace/flacon/venv/bin/python3.7
Also creating executable in /workspace/flacon/venv/bin/python
Installing setuptools, pip, wheel...

  Complete output from command /workspace/flacon/venv/bin/python3.7 - setuptools pip wheel:
  Looking in links: /home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv_support
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/ed/69/c805067de1feedbb98c53174b0f2df44cc05e0e9ee73bb85eebc59e508c6/setuptools-41.0.0.zip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/36/fa/51ca4d57392e2f69397cd6e5af23da2a8d37884a605f9e3f2d3bfdc48397/pip-19.0.3.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'error'
  Complete output from command /workspace/flacon/venv/bin/python3.7 /home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-semx_z8z/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple --find-links /home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv_support -- setuptools wheel:
  Looking in links: /home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv_support, /home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv_support
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/ed/69/c805067de1feedbb98c53174b0f2df44cc05e0e9ee73bb85eebc59e508c6/setuptools-41.0.0.zip
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/b7/cf/1ea0f5b3ce55cacde1e84cdde6cee1ebaff51bd9a3e6c7ba4082199af6f6/wheel-0.33.1.tar.gz
      Complete output from command python setup.py egg_info:
      /home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
        warnings.warn(msg)
      /home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'extras_require'
        warnings.warn(msg)
      /home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'include_package_data'
        warnings.warn(msg)
      /home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'zip_safe'
        warnings.warn(msg)
      /home/gitpod/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'entry_points'
        warnings.warn(msg)
      usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
         or: -c --help [cmd1 cmd2 ...]
         or: -c --help-commands
         or: -c cmd --help

      error: invalid command 'egg_info'

      ----------------------------------------
  /home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/commands/install.py:207: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-8p_76zfw/wheel/

  ----------------------------------------
/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/commands/install.py:207: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
Command "/workspace/flacon/venv/bin/python3.7 /home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-semx_z8z/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple --find-links /home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv_support -- setuptools wheel" failed with error code 1 in None
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv.py", line 2567, in <module>
    main()
  File "/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv.py", line 793, in main
    symlink=options.symlink,
  File "/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv.py", line 1088, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv.py", line 935, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv.py", line 1025, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/home/gitpod/.pyenv/versions/2.7.15/lib/python2.7/site-packages/virtualenv.py", line 886, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /workspace/flacon/venv/bin/python3.7 - setuptools pip wheel failed with error code 1
```

**Comment by iksaif** [comment]
Up to date versions of `setuptools`, `pip` and `virtualenv` would likely fix the issue, but I'm hitting a bug similar to https://github.com/gitpod-io/gitpod/issues/460

**Comment by AlexTugarev** [comment]
@iksaif, you are right about #460! 

Just tested `virtualenv venv -p python3.7` on staging, and the fix for #460 will solve this issue too. :-)

We're going to deploy soon.

**Comment by AlexTugarev** [comment]
@iksaif, please try again! it should work now 😃

**Comment by iksaif** [comment]
I think I broke my local pyenv trying a few things yesterday, I'll try to fix it and double check that everything is working now :)
