### ISSUE TITLE
reverting last db-migration fails

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#4796]
Reverting [this db-migration](https://github.com/gitpod-io/gitpod/blob/main/components/gitpod-db/src/typeorm/migration/1625759714856-IdentityTokensToEmails.ts) fails with the following error.

```
$ typeorm -f lib/typeorm/ormconfig migrations:revert
Loading TypeORM entities and migrations from /app/node_modules/@gitpod/gitpod-db/lib/typeorm
Using DB: localhost:3306/gitpod
2021/07/13 10:36:38 New connection for "gitpod-staging:us-east4:gitpod-staging-us05"
94 migrations are already loaded in the database.
IdentityTokensToEmails1625759714856 is the last executed migration. It was executed on Tue Apr 10 53488 08:47:36 GMT+0000 (Coordinated Universal Time).
Now reverting it...
2021/07/13 10:36:39 Instance gitpod-staging:us-east4:gitpod-staging-us05 closed connection
Error during migration revert:
QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(16777215) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL' at line 1
    at new QueryFailedError (/app/node_modules/typeorm/error/QueryFailedError.js:27:28)
    at Query.<anonymous> (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:207:45)
    at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:502:10)
    at Query._callback (/app/node_modules/mysql/lib/Connection.js:468:16)
    at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/app/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:91:28) {
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(16777215) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL' at line 1",
  sqlState: '42000',
  index: 0,
  sql: 'ALTER TABLE `gitpod`.`d_b_identity` CHANGE `additionalEmails` `tokens` mediumtext(16777215) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL',
  query: 'ALTER TABLE `gitpod`.`d_b_identity` CHANGE `additionalEmails` `tokens` mediumtext(16777215) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL',
  parameters: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

to reproduce, run 
```
#/bin/bash

# CMDs:
#  migrations:run       Runs all pending migrations.
#  migrations:revert    Reverts last executed migration.

IMG=eu.gcr.io/gitpod-core-dev/build/db-migrations:commit-ffb22c36d81d8db14b8f46a304fa6b8c09d1dddb

function typeorm() {
    DB=$1
    docker run --rm \
            --env GOOGLE_APPLICATION_CREDENTIALS_DATA="$(cat $GOOGLE_APPLICATION_CREDENTIALS)" \
            --env GCP_DATABASE=$DB \
            --env DB_PASSWORD=$PWD \
            $IMG /app/typeorm_gcp.sh "$CMD"
}

PWD="..."
CMD="migrations:revert"
typeorm gitpod-staging:europe-west1:gitpod-staging-eu05
typeorm gitpod-staging:us-east4:gitpod-staging-us05

**Comment by meysholdt** [comment]
Here is what we observed:
* renaming the column from `tokens` to `additionalEmails` (or from `additionalEmails` to `tokens`) changes the sql column type from `TEXT` to `MEDIUMTEXT`.
* renaming a column that has type `MEDIUMTEXT` fails.

Hypothesis: TypeORM started mapping the `simple-json` to `MEDIUMTEXT`: https://github.com/k-pindev-j/typeorm/commit/4f48d0e053a3c5f0ecff1aa649eff226f087e6cb

**Comment by corneliusludmann** [comment]
Can be closed, right? If not, please re-open.
