### ISSUE TITLE
[ws-manager] nil pointer dereference

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#5012]
### Bug description

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x196cba6]

goroutine 397 [running]:
github.com/gitpod-io/gitpod/ws-manager/pkg/manager.(*Manager).isWorkspaceTimedOut(0xc0006e8580, 0xc001c4dc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/gitpod-io/gitpod/ws-manager/pkg/manager/status.go:791 +0xf06
github.com/gitpod-io/gitpod/ws-manager/pkg/manager.(*Monitor).markTimedoutWorkspaces(0xc00049b5e0, 0x21197b0, 0xc0019784e0, 0x0, 0x0)
        github.com/gitpod-io/gitpod/ws-manager/pkg/manager/monitor.go:1023 +0x728
github.com/gitpod-io/gitpod/ws-manager/pkg/manager.(*Monitor).doHousekeeping(0xc00049b5e0, 0x2119740, 0xc0019784b0)
        github.com/gitpod-io/gitpod/ws-manager/pkg/manager/monitor.go:381 +0xc6
github.com/gitpod-io/gitpod/ws-manager/pkg/manager.(*Monitor).Start.func1(0xc00049b5e0)
        github.com/gitpod-io/gitpod/ws-manager/pkg/manager/monitor.go:122 +0x7c
created by github.com/gitpod-io/gitpod/ws-manager/pkg/manager.(*Monitor).Start
        github.com/gitpod-io/gitpod/ws-manager/pkg/manager/monitor.go:120 +0x27c
```

### Steps to reproduce

-

**Comment by ArthurSens** [comment]
Duplicated of https://github.com/gitpod-io/gitpod/issues/5011 :)
