### ISSUE TITLE
Can't start the electron application: `cannot open display: :0`

### ISSUE THREAD

**Issue by kittaakos** [gitpod-io/gitpod#504]
**Describe the bug**
Perhaps, this is not a bug but a lack of electron experience in Gitpod.
First, I did not see the electron application started from Gitpod when I tried to start for the second time, it failed with an error.

**To Reproduce**
- `yarn rebuild:electron`
- `yarn --cwd ./examples/electron start`
- <kbd>Ctrl</kbd>+<kbd>C</kbd> and start it again. 

My full console output from Gitpod:
```
gitpod /workspace/theia $ yarn run rebuild:electron
yarn run v1.15.2
$ theia rebuild:electron
Processing @theia/node-pty
Processing nsfw
Processing native-keymap
Processing find-git-repositories
✔ Rebuild Complete
Done in 14.16s.
gitpod /workspace/theia $ yarn --cwd ./examples/electron/ start
yarn run v1.15.2
$ theia start --plugins=local-dir:../../plugins
root WARN The directory referenced by local-dir:../../plugins does not exist.
root INFO Theia app listening on http://localhost:39999.
root INFO Git askpass helper is listening on http://127.0.0.1:33397.
root INFO Using Git [2.19.1] from the PATH. (/usr/bin/git)
root INFO [nsfw-watcher: 2747] Started watching: /home/gitpod/.theia
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"}
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 240.60000000008586 ms
^C
root ERROR Uncaught Exception:  Error: Connection is closed.
root ERROR Error: Connection is closed.
    at new ConnectionError (/workspace/theia/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/workspace/theia/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendRequest (/workspace/theia/node_modules/vscode-jsonrpc/lib/main.js:715:13)
    at /workspace/theia/packages/core/lib/common/messaging/proxy-factory.js:310:72
    at new Promise (<anonymous>)
    at /workspace/theia/packages/core/lib/common/messaging/proxy-factory.js:303:24
gitpod /workspace/theia $ ^C
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 6950 requests (6950 known processed) with 0 events remaining.
[1]+  Exit 1                  jwm
gitpod /workspace/theia $ ^C
gitpod /workspace/theia $ yarn --cwd ./examples/electron/ start
yarn run v1.15.2
$ theia start --plugins=local-dir:../../plugins

(electron:2987): Gtk-WARNING **: 12:42:40.236: cannot open display: :0
Done in 0.79s.
gitpod /workspace/theia $ yarn --cwd ./examples/electron/ start
yarn run v1.15.2
$ theia start --plugins=local-dir:../../plugins

(electron:3069): Gtk-WARNING **: 12:42:45.312: cannot open display: :0
Done in 0.75s.
gitpod /workspace/theia $
```

Note: before `root ERROR Uncaught Exception:  Error: Connection is closed.` I did not see the electron application in Gitpod.

**Comment by kittaakos** [comment]
> * Ctrl+C and start it again.

Maybe this is related: https://github.com/gitpod-io/gitpod/issues/476

**Comment by svenefftinge** [comment]
Does your Docker image use `workspace-fill-vnc`?

**Comment by kittaakos** [comment]
> Does your Docker image use `workspace-full-vnc`?

Yes, it uses it: https://github.com/theia-ide/theia/blob/6366cda738bc2b63f5b4e9e74336fa847635f581/.gitpod.dockerfile#L1

**Comment by geropl** [comment]
@kittaakos Yes, reads like #476

**Comment by kittaakos** [comment]
> @kittaakos Yes, reads like #476

OK. Thanks for checking!
