### ISSUE TITLE
Segfault in blobserve 

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5232]
we see this [segfault](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-08-17T07:00:14.408204001Z;query=%22invalid%20memory%20address%20or%20nil%20pointer%20dereference%22%0Atimestamp%3D%222021-08-17T02:10:40.594956268Z%22%0AinsertId%3D%22vr01v4rb29c9f9ng%22;summaryFields=resource%252Flabels%252Fcluster_name:false:32:beginning;timeRange=P1D?project=gitpod-191109) in prod. 

```
2021/08/17 02:10:40 http: panic serving 10.44.0.17:59352: runtime error: invalid memory address or nil pointer dereference
goroutine 8822 [running]:
net/http.(*conn).serve.func1(0xc0001c2000)
	net/http/server.go:1824 +0x153
panic(0xb2c9e0, 0x10ecb20)
	runtime/panic.go:971 +0x499
net/http.(*timeoutHandler).ServeHTTP(0xc000448340, 0xcf9b00, 0xc000e3c0e0, 0xc0000be100)
	net/http/server.go:3321 +0x949
net/http.serverHandler.ServeHTTP(0xc0004680e0, 0xcf9b00, 0xc000e3c0e0, 0xc0000be100)
	net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0001c2000, 0xcfb1d8, 0xc001906000)
	net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:3013 +0x39b
```

**Comment by corneliusludmann** [comment]
With #5241 deployed, we see now the following stack trace:

```
message: "panic in blobserve request handling: runtime error: invalid memory address or nil pointer dereference
goroutine 392427 [running]:
runtime/debug.Stack(0xc0003faa80, 0xc0002230c0, 0xc0000b98f0)
	runtime/debug/stack.go:24 +0x9f
github.com/gitpod-io/gitpod/blobserve/pkg/blobserve.(*Server).serve.func1(0xc001b88900, 0xcf9bf0, 0xc0033005a0)
	github.com/gitpod-io/gitpod/blobserve/pkg/blobserve/blobserve.go:141 +0x199
panic(0xb2c9c0, 0x10ecb30)
	runtime/panic.go:965 +0x1b9
github.com/gitpod-io/gitpod/blobserve/pkg/blobserve.(*Server).serve(0xc0003517c0, 0xcf9bf0, 0xc0033005a0, 0xc001b88900)
	github.com/gitpod-io/gitpod/blobserve/pkg/blobserve/blobserve.go:202 +0xc75
net/http.HandlerFunc.ServeHTTP(0xc00011c310, 0xcf9bf0, 0xc0033005a0, 0xc001b88900)
	net/http/server.go:2049 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000f6180, 0xcf9bf0, 0xc0033005a0, 0xc001b88700)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
net/http.(*timeoutHandler).ServeHTTP.func1(0xc003300600, 0xc000030740, 0xc0033005a0, 0xc001b88700, 0xc0015a4c60)
	net/http/server.go:3296 +0x7f
created by net/http.(*timeoutHandler).ServeHTTP
	net/http/server.go:3290 +0x22e
"
path: "/eu.gcr.io/gitpod-core-dev/build/ide/theia:commit-695fb785ee80246376558be48be583727a73bfc3/"
```
