### ISSUE TITLE
Segfault in Supervisor

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#5233]
We see [this segfault](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-08-17T00:39:31.409283310Z;query=%22invalid%20memory%20address%20or%20nil%20pointer%20dereference%22%0Atimestamp%3D%222021-08-16T15:41:56.480483589Z%22%0AinsertId%3D%222k5kg35brlxs9md8%22;summaryFields=resource%252Flabels%252Fcluster_name:false:32:beginning;timeRange=P1D?project=gitpod-191109) in prod several times:

```
invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4ef8fb]

goroutine 42 [running]:
os.(*Process).signal(0x0, 0xf40bf0, 0x13d54b0, 0x0, 0x0)
	os/exec_unix.go:63 +0x3b
os.(*Process).Signal(...)
	os/exec.go:135
github.com/gitpod-io/gitpod/supervisor/pkg/supervisor.startAndWatchIDE(0xf48fc8, 0xc000274080, 0xc000330580, 0xc00017c2a0, 0xc0001743e0)
	github.com/gitpod-io/gitpod/supervisor/pkg/supervisor/supervisor.go:547 +0x7bc
created by github.com/gitpod-io/gitpod/supervisor/pkg/supervisor.Run
	github.com/gitpod-io/gitpod/supervisor/pkg/supervisor/supervisor.go:231 +0x1a12
```

**Comment by meysholdt** [comment]
Thank you for the fix! Unfortunately after today's deployment I'm still seeing segfaults in prod with that stacktrace.  Could you take another look? See [here](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-08-17T18:21:45.089600007Z;query=%22invalid%20memory%20address%22%0Aresource.labels.cluster_name%3D%2528%22gp-prod-ws-eu14-eu-west1%22%20OR%20%22gp-prod-ws-us14-us-west1%22%2529%0Atimestamp%3D%222021-08-17T18:21:45.089600007Z%22%0AinsertId%3D%227bnuuog3i4iabz25%22;summaryFields=resource%252Flabels%252Fcluster_name:false:32:beginning;timeRange=PT6H?project=gitpod-191109) and [here](https://console.cloud.google.com/logs/query;cursorTimestamp=2021-08-17T18:21:45.089600007Z;query=%22invalid%20memory%20address%22%0Aresource.labels.cluster_name%3D%2528%22gp-prod-ws-eu14-eu-west1%22%20OR%20%22gp-prod-ws-us14-us-west1%22%2529%0Atimestamp%3D%222021-08-17T18:21:45.089600007Z%22%0AinsertId%3D%227bnuuog3i4iabz25%22;summaryFields=resource%252Flabels%252Fcluster_name:false:32:beginning;timeRange=PT6H?project=gitpod-191109).

**Comment by meysholdt** [comment]
My Bad. The PR got merged right after the deployment and thus the fix has not been deployed yet.
