### ISSUE TITLE
Upgrade to VS Code 1.60.0

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5515]
Please follow to upgrade: https://www.notion.so/gitpod/Gitpod-VS-Code-1aa1dfcfdc5147869ec5ffcf86f430a6

**Comment by roboquat** [comment]
@akosyakov: Cannot schedule issue - no configuration for the IDE team available.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5515#issuecomment-912288504):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - no configuration for the IDE team available.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5515#issuecomment-912297264):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - no configuration for the IDE team available.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5515#issuecomment-912301841):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - no configuration for the IDE team available.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5515#issuecomment-912302712):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - no configuration for the IDE team available.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5515#issuecomment-912303276):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Cannot schedule issue - no configuration for the IDE team available.

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5515#issuecomment-912304899):

>/schedule
>


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5515#issuecomment-912305375):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
web-server branch was rebased to 1.60. We need to fix some issues in Open VSX before updating gp-code:
- python extension cannot be installed, because latest jupyter extension cannot be published
- vim extension is not installed as web extension anymore (generally handling of web extensions is broken)

**Comment by gengjiawen** [comment]
> vim extension is not installed as web extension anymore (generally handling of web extensions is broken)

Hope this get fixed soon. Really painful for heavy-vim user.

**Comment by akosyakov** [comment]
> Hope this get fixed soon. Really painful for heavy-vim user.

@gengjiawen In production it runs in web worker already. Nothing changed. It is only about fixing for upcoming release.

**Comment by gengjiawen** [comment]
> @gengjiawen It is unrelated to production, but for upcoming release. 

I am pretty positive vsvim already broken on production. 

```console
[2021-09-08 14:12:01.207] [window] [info] Installing extension: vscodevim.vim
[2021-09-08 14:12:01.869] [window] [error] Error while installing the extension: vscodevim.vim
[2021-09-08 14:12:01.876] [window] [error] Error: Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
    at m.toWebExtensionFromLocation (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:126836)
    at async m.addExtensionFromGallery (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:124705)
    at async h.doRun (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:116925)
[2021-09-08 14:12:01.884] [window] [error] Failed to install extension: vscodevim.vim Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
[2021-09-08 14:12:01.894] [window] [error] Error: Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
    at m.toWebExtensionFromLocation (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:126836)
    at async m.addExtensionFromGallery (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:124705)
    at async h.doRun (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:116925)
[2021-09-08 14:12:01.898] [window] [error] Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch: Error: Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
    at m.toWebExtensionFromLocation (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:126836)
    at async m.addExtensionFromGallery (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:124705)
    at async h.doRun (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:116925)
[2021-09-08 14:12:07.347] [window] [info] Installing extension: vscodevim.vim
[2021-09-08 14:12:07.646] [window] [error] Error while installing the extension: vscodevim.vim
[2021-09-08 14:12:07.665] [window] [error] Error: Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
    at m.toWebExtensionFromLocation (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:126836)
    at async m.addExtensionFromGallery (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:124705)
    at async h.doRun (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:116925)
[2021-09-08 14:12:07.672] [window] [error] Failed to install extension: vscodevim.vim Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
```

**Comment by akosyakov** [comment]
I agree, i just said that it is irrelevant to this issue.

**Comment by gengjiawen** [comment]
@akosyakov Is this got reverted, I am still seeing 1.59 in production.

**Comment by akosyakov** [comment]
It is available if you switch to latest VS Code in settings: https://gitpod.io/preferences But it is turned out that debugging is broken in upstream for web targets. We are awaiting 1.60.2 recovery release to make it stable.

**Comment by gengjiawen** [comment]
> It is available if you switch to latest VS Code in settings: [gitpod.io/preferences](https://gitpod.io/preferences) But it is turned out that debugging is broken in upstream for web targets. We are awaiting 1.60.2 recovery release to make it stable.

Thanks. I will wait 1.60.2 is ready :)
