### ISSUE TITLE
[code] Error: Unexpected SIGPIPE as ide/out/bootstrap.js:1:370

### ISSUE THREAD

**Issue by akosyakov** [gitpod-io/gitpod#5536]
### Bug description

```
Error: Unexpected SIGPIPE
    at process.<anonymous> (/ide/out/bootstrap.js:1:370)
    at process.emit (events.js:400:28)
```

There are many such errors. We should figure out what is the cause and impact.
<img width="1904" alt="Screenshot 2021-09-06 at 08 16 19" src="https://user-images.githubusercontent.com/3082655/132169730-0fadda35-c803-42b9-b155-d32dad9cb489.png">

### Steps to reproduce

See above

**Comment by akosyakov** [comment]
Removing if from the groundwork for now.

**Comment by akosyakov** [comment]
We switched to upstream server, so it is not under control anymore.
