### ISSUE TITLE
prettier extension load failed

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#5571]
```console
[2021-09-07 11:21:02.375] [exthost] [info] ExtensionService#_doActivateExtension esbenp.prettier-vscode {"startup":false,"extensionId":{"value":"esbenp.prettier-vscode","_lower":"esbenp.prettier-vscode"},"activationEvent":"onStartupFinished"}
[2021-09-07 11:21:02.376] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/gitpod/.gitpod-code/extensions/esbenp.prettier-vscode-8.1.0/dist/extension
[2021-09-07 11:21:02.379] [exthost] [error] Activating extension esbenp.prettier-vscode failed due to an error:
[2021-09-07 11:21:02.379] [exthost] [error] Error: Cannot find module '/home/gitpod/.gitpod-code/extensions/esbenp.prettier-vscode-8.1.0/dist/extension'
Require stack:
- /ide/out/vs/loader.js
- /ide/out/bootstrap-amd.js
- /ide/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
	at Function.Module._load (internal/modules/cjs/loader.js:745:27)
	at Function.n._load (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:28060)
	at Function.A._load (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:24648)
	at Function.l._load (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:59608)
	at Module.require (internal/modules/cjs/loader.js:961:19)
	at Module.require (/ide/extensions/git/dist/main.js:2:516148)
	at require (internal/modules/cjs/helpers.js:92:18)
	at Function.t [as __$__nodeRequire] (/ide/out/vs/loader.js:5:101)
	at v._loadCommonJSModule (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:26057)
	at v._doActivateExtension (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12603)
	at v._activateExtension (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11704)
	at Object.actualActivateExtension (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:9245)
	at d._activateExtension (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:86446)
	at /ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:86128
	at Array.map (<anonymous>)
	at d._activateExtensions (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:86116)
	at d.activateById (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:85:83746)
	at v._activateById (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:10247)
	at v.$activate (/ide/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:20155)
```

**Comment by akosyakov** [comment]
@gengjiawen Unfortunately I cannot reproduce. Do you have a workspace id for which it happened and when? Could you use `Open Window Log File` in such workspace and collect logs for the session when it happened? You can send them to anton@gitpod.io

**Comment by gengjiawen** [comment]
Repo: https://github.com/gengjiawen/ts-scaffold
ID: https://apricot-bonobo-gzwejvag.ws-us15.gitpod.io/

Window Log File

<details>

```console
[2021-09-08 09:28:32.898] [window] [info] Using settings sync service https://gitpod.io/code-sync for initialization
[2021-09-08 09:28:33.607] [window] [info] Initialized UI State
[2021-09-08 09:28:33.649] [window] [info] Initialized Settings
[2021-09-08 09:28:42.123] [window] [info] Remote content does not exist. keybindings
[2021-09-08 09:28:42.146] [window] [info] Initialized Keyboard Shortcuts
[2021-09-08 09:28:42.192] [window] [info] Remote content does not exist. snippets
[2021-09-08 09:28:42.196] [window] [info] Initialized User Snippets
[2021-09-08 09:28:57.249] [window] [info] Installing extension: vscodevim.vim
[2021-09-08 09:28:57.260] [window] [info] Installing the extension without checking dependencies and pack vscodevim.vim
[2021-09-08 09:28:57.504] [window] [error] Error while installing the extension: vscodevim.vim
[2021-09-08 09:28:57.515] [window] [error] Error: Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
    at m.toWebExtensionFromLocation (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:126836)
    at async m.addExtensionFromGallery (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:124705)
    at async h.doRun (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:116925)
[2021-09-08 09:28:57.527] [window] [error] Failed to install extension: vscodevim.vim Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
[2021-09-08 09:29:03.395] [window] [info] Installing extension: vscodevim.vim
[2021-09-08 09:29:03.924] [window] [error] Error while installing the extension: vscodevim.vim
[2021-09-08 09:29:03.935] [window] [error] Error: Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
    at m.toWebExtensionFromLocation (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:126836)
    at async m.addExtensionFromGallery (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:124705)
    at async h.doRun (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:116925)
[2021-09-08 09:29:03.940] [window] [error] Failed to install extension: vscodevim.vim Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
[2021-09-08 09:30:49.599] [window] [warning] Settings pattern "telemetry.*" doesn't match any settings
[2021-09-08 09:30:49.609] [window] [warning] Settings pattern "security.workspace.*" doesn't match any settings
```

</details>

**Comment by akosyakov** [comment]
I was able reproduce it sometimes.

**Comment by gengjiawen** [comment]
Bit of off-topic, should I create an issue for vim extension issue in https://github.com/gitpod-io/gitpod/issues/5515.

**Comment by akosyakov** [comment]
@gengjiawen For now not, I think it maybe related to some general Open VSX incident.

**Comment by akosyakov** [comment]
https://www.gitpodstatus.com/incidents/vyf7zqrxvldv

**Comment by akosyakov** [comment]
@gengjiawen Let's file another issue for VIM. I don't think it is related. But I can now install/uninstall prettier extensions after Open VSX was scaled up. Could you try?

**Comment by gengjiawen** [comment]
Everything works now.

**Comment by maksimr** [comment]
@akosyakov I have tried to download the latest version of VIM extension from **VS Code marketplace** and install it manually, but it still doesn't work.

**Comment by gengjiawen** [comment]
> @gengjiawen Let's file another issue for VIM. I don't think it is related. 

https://github.com/gitpod-io/gitpod/issues/5590

**Comment by akosyakov** [comment]
@maksimr yes, the format of extension was changed, and now our VS Code cannot understand format of latest VIM published although it is engine compatible 🙈 Could you open a new issue please?

**Comment by maksimr** [comment]
@akosyakov Done #5592
