### ISSUE TITLE
vim broken

### ISSUE THREAD

**Issue by gengjiawen** [gitpod-io/gitpod#5590]
cc @akosyakov 

This works yesterday.

Log

```console
[2021-09-08 14:12:01.207] [window] [info] Installing extension: vscodevim.vim
[2021-09-08 14:12:01.869] [window] [error] Error while installing the extension: vscodevim.vim
[2021-09-08 14:12:01.876] [window] [error] Error: Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
    at m.toWebExtensionFromLocation (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:126836)
    at async m.addExtensionFromGallery (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:124705)
    at async h.doRun (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:116925)
[2021-09-08 14:12:01.884] [window] [error] Failed to install extension: vscodevim.vim Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
[2021-09-08 14:12:01.894] [window] [error] Error: Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
    at m.toWebExtensionFromLocation (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:126836)
    at async m.addExtensionFromGallery (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:124705)
    at async h.doRun (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:116925)
[2021-09-08 14:12:01.898] [window] [error] Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch: Error: Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
    at m.toWebExtensionFromLocation (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:126836)
    at async m.addExtensionFromGallery (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:124705)
    at async h.doRun (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:116925)
[2021-09-08 14:12:07.347] [window] [info] Installing extension: vscodevim.vim
[2021-09-08 14:12:07.646] [window] [error] Error while installing the extension: vscodevim.vim
[2021-09-08 14:12:07.665] [window] [error] Error: Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
    at m.toWebExtensionFromLocation (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:126836)
    at async m.addExtensionFromGallery (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:124705)
    at async h.doRun (https://blobserve.ws-us15.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-59f277ba0a7795afe2cc4ca4509c718cd4013f29/__files__/out/vs/workbench/workbench.web.api.js:2871:116925)
[2021-09-08 14:12:07.672] [window] [error] Failed to install extension: vscodevim.vim Cannot find the package.json from the location 'https://open-vsx.org/vscode/asset/vscodevim/vim/1.21.6/Microsoft.VisualStudio.Code.WebResources/extension'. Failed to fetch
```

**Comment by roboquat** [comment]
@JanKoehnlein: Issue scheduled in the IDE team (WIP: 0)

<details>

In response to [this](https://github.com/gitpod-io/gitpod/issues/5590#issuecomment-915032427):

>/schedule


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by akosyakov** [comment]
I think it is the issue on Open VSX side which breaks downloading of web extensions' resources.

**Comment by akosyakov** [comment]
Please follow this Open VSX issue for updates: https://github.com/EclipseFdn/open-vsx.org/issues/633

**Comment by maksimr** [comment]
@akosyakov I have tried and now it works so looks like the problem is gone after updating CORS headers. Thanks a lot

**Comment by gengjiawen** [comment]
Works on my side too.
