### ISSUE TITLE
[code] server writes on closed web socket

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#5649]
### Bug description

~If there is any connection issue, the workspace tries to reconnect constantly.~ See https://github.com/gitpod-io/gitpod/issues/5649#issuecomment-916905123

```
[main 2021-09-10T12:46:25.084Z] Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
[main 2021-09-10T12:46:25.085Z] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at afterWrite (internal/streams/writable.js:470:24)
    at onwrite (internal/streams/writable.js:446:7)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:89:12) {
  code: 'ERR_STREAM_DESTROYED'
}
[main 2021-09-10T12:46:25.085Z] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at afterWrite (internal/streams/writable.js:470:24)
    at onwrite (internal/streams/writable.js:446:7)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:89:12) {
  code: 'ERR_STREAM_DESTROYED'
}
```

### Steps to reproduce

-

**Comment by akosyakov** [comment]
We already have back-off again both Gitpod and Code servers. How can I reproduce these errors?

**Comment by akosyakov** [comment]
Looking at logs, client closed the websocket, but VS Code still tried to push some messages through them and Node.js complains.

**Comment by akosyakov** [comment]
Removing if from the groundwork, and add later when we have more capacity. It maybe has the same cause like https://github.com/gitpod-io/gitpod/issues/5536
