### ISSUE TITLE
in workspace, the own dns-name should resolve to an IP suitable for listening

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#597]
Some examples in https://github.com/tensorflow/tfjs-examples/pull/281 use [parcel-bundler](https://www.npmjs.com/package/parcel-bundler) to launch their dev server. 

I'm trying to make parcel aware of my workspace's DNS name by adding the `--host` parameter:
```
node_modules/parcel-bundler/bin/cli.js serve index.html -d dist --open --no-hmr \
--host 1236-d41cae65-b66f-4dcd-b2b4-821a0eb87264.ws-eu0.gitpod.io --public-url / -p 1236
```

I get this error message:
```
{ Error: listen EADDRNOTAVAIL: address not available 34.76.156.35:1236
    at Server.setupListenHandle [as _listen2] (net.js:1253:19)
    at listenInCluster (net.js:1318:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1451:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:61:10)
  code: 'EADDRNOTAVAIL',
  errno: 'EADDRNOTAVAIL',
  syscall: 'listen',
  address: '34.76.156.35',
  port: 1236 }
/workspace/tfjs-examples/iris/node_modules/parcel-bundler/src/Server.js:141
      logger.error(new Error(serverErrors(err, server.address().port)));
```

Parcel resolves the hostname to an IP and tries to listen on a port on *that* IP address. 

That fails because the workspace container doesn't own the IP because the IP belongs to Gitpod's NAT/LoadBalancer.

Todo: It would be awesome if a workspace's DNS name would be resolved to the workspace's container IP address. 

I'm not aware of a workaround since Kubernetes requires root permission to modify `/etc/hosts` from inside the container and changing filesystem permissions via Dockerfile doesn't work. It needs to be modified via Kubernetes YAML.

Not sure how to do this exactly, since the Domain is port-specific: `1236-d41cae65-b66f-4dcd-b2b4-821a0eb87264.ws-eu0.gitpod.io` and the common denominator `*-d41cae65-b66f-4dcd-b2b4-821a0eb87264.ws-eu0.gitpod.io` can *not* be a subdomain because then we'd need a new SSL cert for every workspace. 
A good start would be to list the domain names for all ports that are listed in `.gitpod.yml`.

**Comment by meysholdt** [comment]
On the other hand, `parcel` should not assume it's hostname resolves to the IP it's running on: https://github.com/parcel-bundler/parcel/issues/3113

**Comment by meysholdt** [comment]
I assume I was using parcel wrong: `--host` is supposed the to be IP that parcel can bind to and the *hostname* that the served site puts into hyperlinks needs to be configured independently.  

Please reopen if I missed something.
