### ISSUE TITLE
No connection established 

### ISSUE THREAD

**Issue by goodking-bq** [gitpod-io/gitpod#6141]
same issue ,have any  suggest？

_Originally posted by @goodking-bq in https://github.com/gitpod-io/gitpod/issues/4218#issuecomment-939640801_

**Comment by ghuntley** [comment]
Howdy @goodking-bq, 

We don’t have any service interruptions AFAIK; I’m investigating. 

Can you please share with me the workspace name/URL?

Regards,
Geoff

**Comment by goodking-bq** [comment]
thanks your time @ghuntley 
i'm running gitpod self-hosted in k8s cluster.  when i create a workspace by visit [https://gitpod.xxx.com/#https://gitlab.xxx.com/golden/stock/-/tree/master/](https://gitpod.xxx.com/#https://gitlab.xxx.com/golden/stock/-/tree/master/). out put that error . and server pod print a error log : 
```json
{"@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent","serviceContext":{"service":"server","version":"0.10.0"},"stack_trace":"Error: 14 UNAVAILABLE: No connection established\n    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:176:52)\n    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)","component":"server","severity":"ERROR","time":"2021-10-11T06:23:09.383Z","environment":"production","region":"local","message":"Request startWorkspace failed with internal server error","error":"Error: 14 UNAVAILABLE: No connection established\n    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:176:52)\n    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78\n    at processTicksAndRejections (internal/process/task_queues.js:79:11)","payload":{"method":"startWorkspace","args":["moccasin-zebra-xb39y2np",{"forceDefaultImage":false},{"_isCancelled":false}]}}

```
