### ISSUE TITLE
Self hosted install via helm chart not functioning

### ISSUE THREAD

**Issue by shanehughes1990** [gitpod-io/gitpod#6191]
### Bug description

Where do I start, Running on GKE trying to install the helm chart, I have db-migrations pods erroring
```
yarn run v1.22.4
$ node ./lib/wait-for-db.js
Using DB: db:3306/gitpod
DB is available
Done in 0.35s.
yarn run v1.22.4
$ typeorm -f lib/typeorm/ormconfig migrations:run
Loading TypeORM entities and migrations from /app/node_modules/@gitpod/gitpod-db/lib/typeorm
Using DB: db:3306/gitpod
Error during migration run:
Error: New migration found: AddProjectIdToPrebuiltWorkspace1624962141719, however this migration's timestamp is not valid. Migration's timestamp should not be older then migrations already executed in the database.
    at /app/node_modules/typeorm/migration/MigrationExecutor.js:91:39
    at Array.filter (<anonymous>)
    at MigrationExecutor.<anonymous> (/app/node_modules/typeorm/migration/MigrationExecutor.js:84:59)
    at step (/app/node_modules/typeorm/migration/MigrationExecutor.js:32:23)
    at Object.next (/app/node_modules/typeorm/migration/MigrationExecutor.js:13:53)
    at fulfilled (/app/node_modules/typeorm/migration/MigrationExecutor.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
ws-daemon never gets past init 
```
  Warning  FailedMount  0s (x9 over 2m8s)  kubelet, gke-development-cluster-default-pool-eef090e3-hrm2  MountVolume.SetUp failed for volume "node-fs1" : hostPath type check failed: /run/containerd/io.containerd.runtime.v1.linux/k8s.io is not a directory
```
I followed the gitpod docs on generic kubernetes install via helm chart, did the https-certificate and created the k8s secret. for whatever reason I just can't seem to get this chart deployed in a state where I can actually start using it.

### Steps to reproduce

Follow these instructions, running on GKE version 1.21.4-gke.1801 (I am on RAPID updates) https://www.gitpod.io/docs/self-hosted/latest/installation/on-kubernetes

### Expected behavior

state of helm release after helm times out
```
agent-smith-4j2n7                    2/2     Running    0          4m14s
agent-smith-k8qhq                    2/2     Running    0          4m10s
agent-smith-sgr79                    2/2     Running    0          3m42s
agent-smith-sttxz                    2/2     Running    0          3m51s
agent-smith-vgft9                    2/2     Running    0          4m21s
agent-smith-x7qd4                    2/2     Running    0          4m30s
blobserve-9977cffcf-wcf6m            2/2     Running    0          4m39s
content-service-5b8d6fdf66-c7dd5     1/1     Running    0          4m39s
dashboard-c68664d8-9svlj             1/1     Running    0          4m39s
db-migrations-4jd68                  0/1     Error      0          4m33s
db-migrations-h4fss                  0/1     Error      0          2m2s
db-migrations-pvmxh                  0/1     Error      0          4m23s
db-migrations-tfjcg                  0/1     Error      0          3m22s
db-migrations-v6cnq                  0/1     Error      0          4m3s
db-migrations-zdwpk                  0/1     Error      0          4m37s
image-builder-658466768f-7drwl       3/3     Running    0          4m39s
messagebus-0                         1/1     Running    0          12m
minio-5894c767f8-wxd84               1/1     Running    0          12m
mysql-0                              1/1     Running    0          12m
proxy-5cbd6cb76f-z24qv               1/1     Running    0          4m39s
registry-6f9d8847c5-hqtkd            1/1     Running    0          12m
registry-facade-4fl6t                0/2     Pending    0          4m39s
registry-facade-84bkr                2/2     Running    0          12m
registry-facade-dwm4x                2/2     Running    0          4m30s
registry-facade-gh9h9                2/2     Running    0          12m
registry-facade-j8phs                2/2     Running    0          12m
registry-facade-v7kq7                2/2     Running    0          12m
server-5cb447dcc-wxmbk               2/2     Running    0          4m38s
ws-daemon-2jh8p                      0/2     Init:0/2   0          4m37s
ws-daemon-78mtt                      0/2     Init:0/2   0          4m31s
ws-daemon-bv8r7                      0/2     Init:0/2   0          4m34s
ws-daemon-dg46d                      0/2     Pending    0          4m39s
ws-daemon-dq4zg                      0/2     Pending    0          4m39s
ws-daemon-qlr7t                      0/2     Init:0/2   0          4m30s
ws-manager-5cfd9d7fbf-hqqf9          2/2     Running    0          4m38s
ws-manager-bridge-74f6954d9f-8jw7t   1/1     Running    0          4m38s
ws-proxy-7f488d6467-f6jkr            1/1     Running    0          4m38s
ws-scheduler-65cfc4c4df-dd26m        2/2     Running    0          4m38s
```

**Comment by ghuntley** [comment]
Hey @shanehughes1990, I would love to figure out what's going on here. Out of interest is there any reason why the 1-click GKE installer hasn't being used? Have you tried it?

https://github.com/gitpod-io/gitpod-gke-guide

**Comment by shanehughes1990** [comment]
So the one click installer I ended up using but I had to modify the preemtable flags out of the Dockerfile for it to work properly. It was a few days ago now sorry I don't have the exact error any longer. But i essentially commented that part out of the script and build that container changed the make file to point to that image.
