### ISSUE TITLE
[Installer] support auth config passed in via config.yaml

### ISSUE THREAD

**Issue by MrSimonEmms** [gitpod-io/gitpod#6401]
GitHub config entered from the webpage works fine, but putting the same config into the `config.yaml` causes the server to break. Example error below:

```json
{
  "@type":"type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
  "serviceContext":{
    "service":"server",
    "version":"main.1640"
  },
  "stack_trace":"Error: No matching bindings found for serviceIdentifier: Symbol(AuthProvider)\n    at _validateActiveBindingCount (/app/node_modules/inversify/lib/planning/planner.js:62:23)\n    at _getActiveBindings (/app/node_modules/inversify/lib/planning/planner.js:48:5)\n    at _createSubRequests (/app/node_modules/inversify/lib/planning/planner.js:91:26)\n    at /app/node_modules/inversify/lib/planning/planner.js:115:17\n    at Array.forEach (<anonymous>)\n    at /app/node_modules/inversify/lib/planning/planner.js:114:26\n    at Array.forEach (<anonymous>)\n    at _createSubRequests (/app/node_modules/inversify/lib/planning/planner.js:94:20)\n    at Object.plan (/app/node_modules/inversify/lib/planning/planner.js:136:9)\n    at /app/node_modules/inversify/lib/container/container.js:317:37\n    at Container._get (/app/node_modules/inversify/lib/container/container.js:310:44)\n    at Container.get (/app/node_modules/inversify/lib/container/container.js:230:21)\n    at Function.createHostContext (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:147:26)\n    at Object.createHostContext (/app/node_modules/@gitpod/server/dist/src/container-module.js:147:93)\n    at HostContextProviderImpl.createFixedHosts (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:76:44)\n    at HostContextProviderImpl.<anonymous> (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:52:18)\n    at Generator.next (<anonymous>)\n    at /app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:22:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:18:12)\n    at HostContextProviderImpl.ensureInitialized (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:48:16)\n    at HostContextProviderImpl.<anonymous> (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:44:24)",
  "component":"server",
  "severity":"ERROR",
  "time":"2021-10-26T11:05:03.089Z",
  "message":"Error during startup or operation. Exiting.",
  "error":"Error: No matching bindings found for serviceIdentifier: Symbol(AuthProvider)\n    at _validateActiveBindingCount (/app/node_modules/inversify/lib/planning/planner.js:62:23)\n    at _getActiveBindings (/app/node_modules/inversify/lib/planning/planner.js:48:5)\n    at _createSubRequests (/app/node_modules/inversify/lib/planning/planner.js:91:26)\n    at /app/node_modules/inversify/lib/planning/planner.js:115:17\n    at Array.forEach (<anonymous>)\n    at /app/node_modules/inversify/lib/planning/planner.js:114:26\n    at Array.forEach (<anonymous>)\n    at _createSubRequests (/app/node_modules/inversify/lib/planning/planner.js:94:20)\n    at Object.plan (/app/node_modules/inversify/lib/planning/planner.js:136:9)\n    at /app/node_modules/inversify/lib/container/container.js:317:37\n    at Container._get (/app/node_modules/inversify/lib/container/container.js:310:44)\n    at Container.get (/app/node_modules/inversify/lib/container/container.js:230:21)\n    at Function.createHostContext (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:147:26)\n    at Object.createHostContext (/app/node_modules/@gitpod/server/dist/src/container-module.js:147:93)\n    at HostContextProviderImpl.createFixedHosts (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:76:44)\n    at HostContextProviderImpl.<anonymous> (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:52:18)\n    at Generator.next (<anonymous>)\n    at /app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:22:71\n    at new Promise (<anonymous>)\n    at __awaiter (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:18:12)\n    at HostContextProviderImpl.ensureInitialized (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:48:16)\n    at HostContextProviderImpl.<anonymous> (/app/node_modules/@gitpod/server/dist/src/auth/host-context-provider-impl.js:44:24)"
}
```

**Comment by csweichel** [comment]
@AlexTugarev @geropl 
is setting the auth providers using the configuration/env var still supported?

**Comment by geropl** [comment]
@csweichel @MrSimonEmms It is, as we use that in production: https://github.com/gitpod-io/ops/blob/main/charts/gitpod_io/values.production.yaml#L95

Maybe we're just using that in the EE scenario or so. Happy to sync on this.
