### ISSUE TITLE
[ide] gp command doesn't work in gitpod-desktop 

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#7126]
### Bug description

How to reproduce:
1. Open a workspace in vscode desktop
2. Try running a gp command in console
```
 ERR [Extension Host] failed to update ipc hook cli: Error: Bad status code: 400: 
	at IncomingMessage.<anonymous> (/home/gitpod/.vscode-server-insiders/extensions/gitpod.gitpod-remote-ssh-0.0.27/dist/extension.js:2:774945)
	at IncomingMessage.emit (events.js:327:22)
	at endReadableNT (internal/streams/readable.js:1327:12)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

### Steps to reproduce

see above

**Comment by jeanp413** [comment]
We published a new version with @akosyakov to the marketplace. Tested the new version manually and it's working now.
Closing this.
