### ISSUE TITLE
[chargebee] webhook failure when updating expired credit card

### ISSUE THREAD

**Issue by JanKoehnlein** [gitpod-io/gitpod#7171]
### Bug description

Chargebee reported a webhook fauilure on an "Payment Source Expiring" event.

Our `payment-endpoint` logs 
```
"QueryFailedError: ER_DUP_ENTRY: Duplicate entry '<payment ref redacted>-<resourceVersion redacted> for key 'PRIMARY'
    at QueryFailedError.TypeORMError [as constructor] (/app/node_modules/typeorm/error/TypeORMError.js:9:28)
    at new QueryFailedError (/app/node_modules/typeorm/error/QueryFailedError.js:13:28)
    at Query.<anonymous> (/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:222:57)
    at Query.<anonymous> (/app/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/app/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/app/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/app/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/app/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/app/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/app/node_modules/mysql/lib/protocol/Parser.js:43:10)"
```

### Steps to reproduce

It looks like this was the first time a user used a credit card in the same month in which it was expiring.

**Comment by JanKoehnlein** [comment]
We use `paymentSource` (`VARCHAR`) and `resourceVersion` (`BIGINT`) as primary keys in the `d_b_paymnet_source_info`. When starting a subscription with an expiring creditcard, Chargebee sends events of type "payment source added" and "payment source expiring" with the same `resourceVersion` (usually this is icremented between events). 

Looks like TypeORM doesn't correctly deal with primary keys of number types, so it fails to find the current entry but fails to add a new one on `save`.

**Comment by JanKoehnlein** [comment]
Maybe related to https://github.com/typeorm/typeorm/issues/6060 or https://github.com/typeorm/typeorm/issues/2930

**Comment by jankeromnes** [comment]
@JanKoehnlein Random after-thought: Wouldn't `repo.update(primaryKey, shape)` have resolved the problem of duplicate entry that `repo.save(shape)` has?
