### ISSUE TITLE
Build fails when trying to add a new dashboard

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/gitpod#7256]
### Bug description

While trying to add a new dashboard, PR build fails with [following error](https://werft.gitpod-dev.com/job/gitpod-build-prs-cluster-autoscaler-dashboard.6/raw):
```

/workspace/.werft/util/shell.ts:34
            throw new Error(`${cmd} exit with non-zero status code`);
                  ^
Error: cd observability && hack/deploy-satellite.sh exit with non-zero status code
    at handleResult (/workspace/.werft/util/shell.ts:34:19)
    at exec (/workspace/.werft/util/shell.ts:52:9)
    at /workspace/.werft/observability/monitoring-satellite.ts:69:9
    at step (/workspace/.werft/observability/monitoring-satellite.ts:33:23)
    at Object.next (/workspace/.werft/observability/monitoring-satellite.ts:14:53)
    at /workspace/.werft/observability/monitoring-satellite.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/workspace/.werft/observability/monitoring-satellite.ts:4:12)
    at ensureCorrectInstallationOrder (/workspace/.werft/observability/monitoring-satellite.ts:88:12)
    at /workspace/.werft/observability/monitoring-satellite.ts:61:5
npm notice 
npm notice New minor version of npm available! 8.1.0 -> 8.3.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.3.0>
npm notice Run `npm install -g npm@8.3.0` to update!
npm notice 
```

### Steps to reproduce

Refer to [this PR](https://github.com/gitpod-io/gitpod/pull/7228) for the changes. 

### Expected behavior

Build should pass

**Comment by princerachit** [comment]
Closing this as the issue was with the branch not rebased on top of local changes.
