### ISSUE TITLE
Install gitpod-eks in China Ningxia region failed: Message returned: Error: b'Release "aws-load-balancer-controller" does not exist. Installing it now.\nError: timed out waiting for the condition\n' #37

### ISSUE THREAD

**Issue by chenzhipei** [gitpod-io/gitpod#7277]
### Bug description

![image](https://user-images.githubusercontent.com/15027092/146471462-37c6a78a-6802-4f24-9e7a-6adfa634ff5a.png)

aws region: cn-northwest-1
eks version: 1.21

### Steps to reproduce

make install

```
Starting install process...
Using eksctl configuration file: eks-cluster.yaml
Missing (optional) AWS profile.
Missing (optional) ROUTE53_ZONEID environment variable.
Please configure the CNAME with the URL of the load balancer manually.
 ⏳  Bootstrapping environment aws://318804062415/cn-northwest-1...
Trusted accounts for deployment: (none)
Trusted accounts for lookup: (none)
Using default execution policy of 'arn:aws-cn:iam::aws:policy/AdministratorAccess'. Pass '--cloudformation-execution-policies' to customize.
 ✅  Environment aws://318804062415/cn-northwest-1 bootstrapped (no changes).
****************************************************
*** Newer version of CDK is available [2.2.0]    ***
*** Upgrade recommended (npm install -g aws-cdk) ***
****************************************************
2021-12-16 05:06:48 [ℹ]  eksctl version 0.78.0-dev+8d2eec00.2021-12-15T10:48:00Z
2021-12-16 05:06:48 [ℹ]  using region cn-northwest-1
2021-12-16 05:06:48 [✔]  saved kubeconfig as ".kubeconfig"
daemonset.apps/aws-node patched (no change)
configmap/calico-config unchanged
customresourcedefinition.apiextensions.k8s.io/bgpconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/bgppeers.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/blockaffinities.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/caliconodestatuses.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/clusterinformations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/felixconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/globalnetworkpolicies.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/globalnetworksets.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/hostendpoints.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamblocks.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamconfigs.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipamhandles.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ippools.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/ipreservations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/kubecontrollersconfigurations.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/networkpolicies.crd.projectcalico.org configured
customresourcedefinition.apiextensions.k8s.io/networksets.crd.projectcalico.org configured
clusterrole.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-kube-controllers unchanged
clusterrole.rbac.authorization.k8s.io/calico-node unchanged
clusterrolebinding.rbac.authorization.k8s.io/calico-node unchanged
daemonset.apps/calico-node configured
serviceaccount/calico-node unchanged
deployment.apps/calico-kube-controllers unchanged
serviceaccount/calico-kube-controllers unchanged
Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
poddisruptionbudget.policy/calico-kube-controllers configured
2021-12-16 05:07:08 [ℹ]  eksctl version 0.78.0-dev+8d2eec00.2021-12-15T10:48:00Z
2021-12-16 05:07:08 [ℹ]  using region cn-northwest-1
2021-12-16 05:07:10 [ℹ]  nodegroup "workspaces" will use "ami-01ecefd03fc7c65bd" [AmazonLinux2/1.21]
2021-12-16 05:07:10 [ℹ]  nodegroup "services" will use "ami-01ecefd03fc7c65bd" [AmazonLinux2/1.21]
2021-12-16 05:07:11 [!]  retryable error (Throttling: Rate exceeded
        status code: 400, request id: 6cb875c4-0a94-453b-b257-2241592a9462) from cloudformation/DescribeStacks - will retry after delay of 8.019468838s
2021-12-16 05:07:20 [ℹ]  2 existing nodegroup(s) (services,workspaces) will be excluded
2021-12-16 05:07:20 [ℹ]  
2 sequential tasks: { fix cluster compatibility, no tasks 
}
2021-12-16 05:07:20 [ℹ]  checking cluster stack for missing resources
2021-12-16 05:07:21 [ℹ]  cluster stack has all required resources
2021-12-16 05:07:21 [ℹ]  no tasks
2021-12-16 05:07:21 [✔]  created 0 nodegroup(s) in cluster "gitpod"
2021-12-16 05:07:21 [✔]  created 0 managed nodegroup(s) in cluster "gitpod"
2021-12-16 05:07:22 [ℹ]  checking security group configuration for all nodegroups
2021-12-16 05:07:22 [ℹ]  all nodegroups have up-to-date cloudformation templates
[Warning at /Services/RDS/Gitpod/SecurityGroup] Ignoring Egress rule since 'allowAllOutbound' is set to true; To add customize rules, set allowAllOutbound=false on the SecurityGroup
Setup
Setup: deploying...

 ✅  Setup (no changes)

Outputs:
Setup.ClusterName = gitpod
Setup.OpenIdConnectProviderArn = arn:aws-cn:iam::318804062415:oidc-provider/oidc.eks.cn-northwest-1.amazonaws.com/id/D563E80E60861A769E8C85FA12DFA49E

Stack ARN:
arn:aws-cn:cloudformation:cn-northwest-1:318804062415:stack/Setup/11479e00-5ccd-11ec-8f5e-0655b24bb2fc
Addons
Addons: deploying...
[0%] start: Publishing 43079f879513e0d85eeb42ddfe71e5ead66edf1ee02c33bb165d7c2f926030c4:current
[9%] success: Published 43079f879513e0d85eeb42ddfe71e5ead66edf1ee02c33bb165d7c2f926030c4:current
[9%] start: Publishing 4129bbca38164ecb28fee8e5b674f0d05e5957b4b8ed97d9c950527b5cc4ce10:current
[18%] success: Published 4129bbca38164ecb28fee8e5b674f0d05e5957b4b8ed97d9c950527b5cc4ce10:current
[18%] start: Publishing e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68:current
[27%] success: Published e9882ab123687399f934da0d45effe675ecc8ce13b40cb946f3e1d6141fe8d68:current
[27%] start: Publishing ea17febe6d04c66048f3e8e060c71685c0cb53122abceff44842d27bc0d4a03e:current
[36%] success: Published ea17febe6d04c66048f3e8e060c71685c0cb53122abceff44842d27bc0d4a03e:current
[36%] start: Publishing c691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49c:current
[45%] success: Published c691172cdeefa2c91b5a2907f9d81118e47597634943344795f1a844192dd49c:current
[45%] start: Publishing 5d1f4d13388f418bc16c1def9b7b5bd5caa086c65d6ef83aa3a03eef62bc164f:current
[54%] success: Published 5d1f4d13388f418bc16c1def9b7b5bd5caa086c65d6ef83aa3a03eef62bc164f:current
[54%] start: Publishing f9e76121b6184d2613051d4ab85d393c07ea61775e315cad1bc7eb3a473dd021:current
[63%] success: Published f9e76121b6184d2613051d4ab85d393c07ea61775e315cad1bc7eb3a473dd021:current
[63%] start: Publishing 7989dd382e8c481d2fcbe1e0a516a5fd6b908cd340290c713dfb9af022b2a4c9:current
[72%] success: Published 7989dd382e8c481d2fcbe1e0a516a5fd6b908cd340290c713dfb9af022b2a4c9:current
[72%] start: Publishing 9c4fad835ec9c5ce50e9b3aabeed61375ecc0445ea689b82b13cd943e03ced9f:current
[81%] success: Published 9c4fad835ec9c5ce50e9b3aabeed61375ecc0445ea689b82b13cd943e03ced9f:current
[81%] start: Publishing 5993e242d5720bb39d492adef76a8a6c945b5326e88bbce414b75a9c68652b52:current
[90%] success: Published 5993e242d5720bb39d492adef76a8a6c945b5326e88bbce414b75a9c68652b52:current
[90%] start: Publishing 4723e10b8fcfa0fbc4dedaa75f4b87be39ea7618cf01021b9af496de07d23ae4:current
[100%] success: Published 4723e10b8fcfa0fbc4dedaa75f4b87be39ea7618cf01021b9af496de07d23ae4:current
Addons: creating CloudFormation changeset...
5:15:27 AM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | awsloadbalancerBas...ollerChart6F04131E
Received response status [FAILED] from custom resource. Message returned: Error: b'Release "aws-load-balancer-controller" does not exist. Installing it now.\nError: timed out waiting for the condition\n'

Logs: /aws/lambda/Addons-AddonsawsloadbalancerBaseCl-Handler886CB40B-6JNtn9RUNYFX

at invokeUserFunction (/var/task/framework.js:95:19)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async onEvent (/var/task/framework.js:19:27)
at async Runtime.handler (/var/task/cfn-response.js:48:13) (RequestId: a8169fee-a9c7-4a04-a2aa-fa01aaf3a566)

        new CustomResource (/gitpod/node_modules/@aws-cdk/core/lib/custom-resource.ts:36:21)
        \_ new HelmChart (/gitpod/node_modules/@aws-cdk/aws-eks/lib/helm-chart.ts:69:5)
        \_ ImportedCluster.addHelmChart (/gitpod/node_modules/@aws-cdk/aws-eks/lib/cluster.ts:392:12)
        \_ new AWSLoadBalancerController (/gitpod/lib/charts/load-balancer.ts:12:35)
        \_ new AddonsStack (/gitpod/lib/addons.ts:19:9)
        \_ Object.<anonymous> (/gitpod/bin/provision.ts:43:16)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Module.m._compile (/gitpod/node_modules/ts-node/src/index.ts:1371:23)
        \_ Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Object.require.extensions.<computed> [as .ts] (/gitpod/node_modules/ts-node/src/index.ts:1374:12)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ main (/gitpod/node_modules/ts-node/src/bin.ts:331:12)
        \_ Object.<anonymous> (/gitpod/node_modules/ts-node/src/bin.ts:482:3)
        \_ Module._compile (node:internal/modules/cjs/loader:1101:14)
        \_ Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
        \_ Module.load (node:internal/modules/cjs/loader:981:32)
        \_ Function.Module._load (node:internal/modules/cjs/loader:822:12)
        \_ Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
        \_ node:internal/main/run_main_module:17:47


 ❌  Addons failed: Error: The stack named Addons failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
    at Object.waitForStackDeploy (/usr/local/lib/node_modules/aws-cdk/lib/api/util/cloudformation.ts:307:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at prepareAndExecuteChangeSet (/usr/local/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:351:26)
    at CdkToolkit.deploy (/usr/local/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:194:24)
    at initCommandLine (/usr/local/lib/node_modules/aws-cdk/bin/cdk.ts:267:9)
The stack named Addons failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE
make: *** [install] Error 1
```

**Comment by aledbf** [comment]
Closing. Duplicate https://github.com/gitpod-io/gitpod-eks-guide/issues/37
