### ISSUE TITLE
Error running prebuilds on GitLab self-hosted v12.x

### ISSUE THREAD

**Issue by jldec** [gitpod-io/gitpod#7453]
The following error shows in the console when triggering a prebuild on a project for a GitLab self-hosted repository, using the "Run Prebuild" button in the project Prebuilds page.

```
Cannot read properties of undefined (reading 'split')
```

The same error is visible in the Configuration page.

**Comment by jldec** [comment]
![Screenshot 2022-01-05 at 10 00 47](https://user-images.githubusercontent.com/849592/148199739-0bae6751-5257-4d1a-8397-57fd7d51a453.png)


![Screenshot 2022-01-05 at 10 02 47](https://user-images.githubusercontent.com/849592/148199705-c09a1b80-deb3-4d60-8a30-d4be34250ba5.png)

**Comment by jldec** [comment]
server trace:
```
TypeError: Cannot read properties of undefined (reading 'split')
    at EnvvarPrefixParser.parse (/app/node_modules/@gitpod/server/dist/src/workspace/envvar-prefix-context-parser.js:44:34)
    at EnvvarPrefixParser.findPrefix (/app/node_modules/@gitpod/server/dist/src/workspace/envvar-prefix-context-parser.js:27:29)
    at ContextParser.findPrefix (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:84:35)
    at ContextParser.<anonymous> (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:53:43)
    at Generator.next (<anonymous>)
    at /app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:18:12)
    at ContextParser.handle (/app/node_modules/@gitpod/server/dist/src/workspace/context-parser-service.js:48:16)
    at Proxy.<anonymous> (/app/node_modules/@gitpod/server/dist/ee/src/workspace/gitpod-server-impl.js:1420:54)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/@gitpod/server/dist/ee/src/workspace/gitpod-server-impl.js:19:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by AlexTugarev** [comment]
just compared the docs of the old version of self-managed GitLab with the recent one and it's clear that we're expecting a `web_url` property in the `GET branches` response which is missing back in old versions. 

cf. 
https://docs.gitlab.com/12.10/ee/api/branches.html
https://docs.gitlab.com/ee/api/branches.html

@jldec, given that the v12 releases of GitLab are quite old and the API looks different, I'd propose to not spend time in supporting it unless it's getting requested. also, a bump of our internal GItLab instance would be great!

**Comment by gtsiolis** [comment]
> I'd propose to not spend time in supporting it unless it's getting requested. also, a bump of our internal GItLab instance would be great!

Agree with @AlexTugarev here. GitLab 12.0 is quite old, released back in June 2019. 💯

**Comment by JanKoehnlein** [comment]
From [platform](https://github.com/gitpod-io/ops/issues/605#issuecomment-1006589748
)
> From this #425 (comment) it sounds like @corneliusludmann has a solution for creating an on-demand instance. Would that work for us here?

**Comment by geropl** [comment]
@AlexTugarev Do we still need to do anything here, as we now have the UI hint? Maybe adding more checks on the backend to avoid the `TypeError`?

**Comment by AlexTugarev** [comment]
@jldec, are you fine with closing this issue? 

I think we need to start reading `https://<gitlab>/api/v4/version`

**Comment by jldec** [comment]
yes - closing - thanks @AlexTugarev
