### ISSUE TITLE
Python Language server startup fail

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#790]
**Describe the bug**
https://gitpod.io/#https://github.com/JesterOrNot/VoiceID
Python language server refuses to start repository URL
Error message
TypeError: s.languages.registerDeclarationProvider is not a function
    at t.DeclarationFeature.registerLanguageProvider (/tmp/vscode-extensions/ms-python.python@2019.8.30787/extension/out/client/extension.js:75:95904)
    at t.DeclarationFeature.register (/tmp/vscode-extensions/ms-python.python@2019.8.30787/extension/out/client/extension.js:1:178268)
    at t.DeclarationFeature.initialize (/tmp/vscode-extensions/ms-python.python@2019.8.30787/extension/out/client/extension.js:75:95261)
    at t.LanguageClient.initializeFeatures (/tmp/vscode-extensions/ms-python.python@2019.8.30787/extension/out/client/extension.js:1:213726)
    at e.initialize.then.t (/tmp/vscode-extensions/ms-python.python@2019.8.30787/extension/out/client/extension.js:1:206308)
**To Reproduce**
Open link provided
**Expected behavior**
Language server starts normally

**Comment by AlexTugarev** [comment]
This is solved in Theia https://github.com/eclipse-theia/theia/pull/6173.
An update to Gitpod will be available soon!

**Comment by JesterOrNot** [comment]
Thank-you
