### ISSUE TITLE
VSCode settings sync error `Server did not return the ref`

### ISSUE THREAD

**Issue by jeanp413** [gitpod-io/gitpod#8494]
### Bug description

A user reported that settings sync is not working for him with the following error in console

```
[2022-02-25 10:43:49.037] [settingssync] [info] Using settings sync service https://gitpod.io/code-sync
[2022-02-25 10:43:49.076] [settingssync] [info] Auto Sync is enabled.
[2022-02-25 10:43:49.115] [settingssync] [info] Auto Sync: Suspended until auth token is available.
[2022-02-25 10:43:51.276] [settingssync] [info] Auto Sync: Started
[2022-02-25 10:43:51.307] [settingssync] [info] Auto Sync: Triggered by Interval
[2022-02-25 10:43:51.349] [settingssync] [error] NoRef (UserDataSyncError) syncResource:unknown operationId:279251e8-4b0a-4bc4-ae6e-1370b9443e0b: Server did not return the ref
    at D.manifest (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:172722)
    at async S.createSyncTask (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:148410)
    at async S.doSync (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:144901)
[2022-02-25 10:43:51.440] [settingssync] [error] NoRef (UserDataSyncError) syncResource:unknown operationId:279251e8-4b0a-4bc4-ae6e-1370b9443e0b: Server did not return the ref
    at D.manifest (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:172722)
    at async S.createSyncTask (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:148410)
    at async S.doSync (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:144901)
[2022-02-25 10:48:51.353] [settingssync] [info] Auto Sync: Triggered by Interval
[2022-02-25 10:48:51.453] [settingssync] [error] NoRef (UserDataSyncError) syncResource:unknown operationId:739c733f-8763-442a-bc73-d86842074efe: Server did not return the ref
    at D.manifest (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:172722)
    at async S.createSyncTask (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:148410)
    at async S.doSync (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:144901)
[2022-02-25 10:48:51.476] [settingssync] [error] NoRef (UserDataSyncError) syncResource:unknown operationId:739c733f-8763-442a-bc73-d86842074efe: Server did not return the ref
    at D.manifest (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:172722)
    at async S.createSyncTask (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:148410)
    at async S.doSync (https://blobserve.ws-us34xl.gitpod.io/eu.gcr.io/gitpod-core-dev/build/ide/code:commit-890de80174c7dd9d073d63ef2b1f9eac68f063c1/__files__/out/vs/workbench/workbench.web.main.js:787:144901)
[2022-02-25 10:50:34.648] [settingssync] [info] Auto Sync: Triggered by Activity
```

Context:
https://gitpod.slack.com/archives/C032GEUGV09/p1645817535491169

**Comment by jeanp413** [comment]
The issue was caused by [ClearURLs](https://chrome.google.com/webstore/detail/clearurls/lckanjgmijmafbedllaakclkaicjfmnk?hl) chrome extension, it has a feature to [remove all etag headers](https://github.com/ClearURLs/Addon/blob/3f707bfd3af06d1aea5cea9d6de45fd4ddab8651/core_js/eTagFilter.js)
Disabling that feature or removing the extension fixed the issue
