### ISSUE TITLE
"Sorry, something went wrong" when starting a workspace with Edge

### ISSUE THREAD

**Issue by spoenemann** [gitpod-io/gitpod#853]
**Describe the bug**
I tried to log in and start a workspace with MS Edge, but all I get is a page saying

    Sorry, something went wrong 😓
    Error

The browser log says:
```
HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
(Fetch)GET - https://gitpod.io/api/refresh-login

RWS: open
sorry.js (56,108637)

RWS: reconnectDelay: 1317.5001572074045
sorry.js (56,108637)

[object Error]: {code: 401, data: undefined, description: "User is not authenticated. Please login.", message: "User is not authenticated. Please login.", stack: "Error: User is not authenticated. Please login. at i (https://gitpod.io/sorry.js:21:28200) at Anonymous function (https://gitpod.io/sorry.js:6:47571) at Anonymous function (https://gitpod.io/sorry.js:6:46704) at Anonymous function (https://gitpod.io/sorry.js:6:43876)"}

[object Error]: {code: 401, data: undefined, description: "User is not authenticated. Please login.", message: "User is not authenticated. Please login.", stack: "Error: User is not authenticated. Please login. at i (https://gitpod.io/sorry.js:21:28200) at Anonymous function (https://gitpod.io/sorry.js:6:47571) at Anonymous function (https://gitpod.io/sorry.js:6:46704) at Anonymous function (https://gitpod.io/sorry.js:6:43876)"}
```

**To Reproduce**
Log in and start a workspace with Edge

**Expected behavior**
It should work as usual, or if Edge is not supported it should tell me so with a clear message.

**Comment by AlexTugarev** [comment]
you'll see the 404 for `refresh-login` if you're not logged in.

is that always the case with edge?
cc. @geropl

**Comment by spoenemann** [comment]
This happened when I had to click on the "Login with GitHub" button to open the workspace. It actually works fine if I log in to Gitpod first, then open the workspace.

**Comment by geropl** [comment]
@AlexTugarev I think we never tested with MS Edge to be honest.
