### ISSUE TITLE
[agent-smith] Concurrent map write during start

### ISSUE THREAD

**Issue by aledbf** [gitpod-io/gitpod#8843]
### Bug description

```
{"level":"info","message":"procfs detector started","serviceContext":{"service":"agent-smith","version":"commit-526ed855bb509e6523f1318a7f207a55cefdb054"},"severity":"INFO","time":"2022-03-16T17:18:38Z"}
fatal error: concurrent map read and map write

goroutine 31 [running]:
runtime.throw({0x17950a1, 0x1})
	runtime/panic.go:1198 +0x71 fp=0xc000560e40 sp=0xc000560e10 pc=0x436b31
runtime.mapaccess2_fast64(0xc0002a7d00, 0xc00059c150, 0xa485)
	runtime/map_fast64.go:61 +0x176 fp=0xc000560e60 sp=0xc000560e40 pc=0x411536
github.com/gitpod-io/gitpod/agent-smith/pkg/agent.(*Smith).Start.func1()
	github.com/gitpod-io/gitpod/agent-smith/pkg/agent/agent.go:231 +0x175 fp=0xc000560fe0 sp=0xc000560e60 pc=0x13c0815
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc000560fe8 sp=0xc000560fe0 pc=0x46a701
created by github.com/gitpod-io/gitpod/agent-smith/pkg/agent.(*Smith).Start
	github.com/gitpod-io/gitpod/agent-smith/pkg/agent/agent.go:222 +0x2b4

goroutine 1 [select, 17 minutes]:
github.com/gitpod-io/gitpod/agent-smith/cmd.glob..func3(0x2570cc0, {0x1776031, 0x2, 0x2})
	github.com/gitpod-io/gitpod/agent-smith/cmd/run.go:107 +0xbff
github.com/spf13/cobra.(*Command).execute(0x2570cc0, {0xc00053c0c0, 0x2, 0x2})
	github.com/spf13/cobra@v1.1.3/command.go:856 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x2570a40)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
github.com/gitpod-io/gitpod/agent-smith/cmd.Execute()
	github.com/gitpod-io/gitpod/agent-smith/cmd/root.go:48 +0x25
main.main()
	github.com/gitpod-io/gitpod/agent-smith/main.go:15 +0x17


```

### Steps to reproduce

-

**Comment by aledbf** [comment]
```
gent-smith-2ntj5             2/2     Running   0               21m
agent-smith-2rwth             2/2     Running   1 (16m ago)     18m
agent-smith-5bmnd             2/2     Running   0               20m
agent-smith-6jjkj             2/2     Running   0               23m
agent-smith-7g797             2/2     Running   1 (29m ago)     29m
agent-smith-85rbx             2/2     Running   1 (29m ago)     29m
agent-smith-btk4t             2/2     Running   0               105s
agent-smith-chqvq             2/2     Running   2 (15m ago)     17m
agent-smith-kcb6q             2/2     Running   0               13m
agent-smith-n6sfn             2/2     Running   0               14m
agent-smith-nztv2             2/2     Running   0               16m
agent-smith-pq6bp             2/2     Running   1 (29m ago)     29m
agent-smith-pszgl             2/2     Running   1 (5m39s ago)   12m
agent-smith-pzshq             2/2     Running   2 (23m ago)     29m
agent-smith-qkhv8             2/2     Running   1 (29m ago)     29m
agent-smith-rnshw             2/2     Running   1 (29m ago)     29m
agent-smith-xb2v9             2/2     Running   0               11m
agent-smith-xg8lg             2/2     Running   0               2m57s

```

**Comment by princerachit** [comment]
## Works
### Pods status
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/32481722/158773337-40c57732-2739-4359-90fc-4c90103ea8ce.png">

### Graph

<img width="2481" alt="image" src="https://user-images.githubusercontent.com/32481722/158770490-4164d39c-36a7-4b30-ba7c-85c905456b93.png">
