### ISSUE TITLE
In preview envs, db-migrations fail

### ISSUE THREAD

**Issue by meysholdt** [gitpod-io/gitpod#9067]
Error:
```
Migration PWSUIndexes1643879235654 has been executed successfully.
query: SELECT COUNT(1) AS cnt FROM INFORMATION_SCHEMA.COLUMNS
            WHERE   table_schema = 'gitpod'
                AND table_name = 'd_b_auth_provider_entry'
                AND column_name = 'oauthRevision'
query: ALTER TABLE d_b_auth_provider_entry ADD COLUMN oauthRevision varchar(128) NOT NULL DEFAULT ''
query: SELECT COUNT(1) AS cnt FROM INFORMATION_SCHEMA.STATISTICS
            WHERE   table_schema = 'gitpod'
                AND table_name = 'd_b_auth_provider_entry'
                AND index_name = 'ind_oauthRevision'
query: CREATE INDEX ind_oauthRevision ON d_b_auth_provider_entry (oauthRevision)
Loading TypeORM entities and migrations from /app/node_modules/@gitpod/gitpod-db/lib/typeorm
Using DB: db:3306/gitpod
query: ROLLBACK
Error during migration run:
Error: Environment variable undefined or empty: DB_ENCRYPTION_KEYS
    at getEnvVar (/app/node_modules/@gitpod/gitpod-protocol/lib/env.js:44:15)
    at Config.get dbEncryptionKeys [as dbEncryptionKeys] (/app/node_modules/@gitpod/gitpod-db/lib/config.js:42:36)
    at Binding.dynamicValue (/app/node_modules/@gitpod/gitpod-db/lib/container-module.js:103:85)
    at /app/node_modules/inversify/lib/resolution/resolver.js:66:118
    at invokeFactory (/app/node_modules/inversify/lib/resolution/resolver.js:11:16)
    at /app/node_modules/inversify/lib/resolution/resolver.js:66:26
    at Array.map (<anonymous>)
    at Object.resolveInstance (/app/node_modules/inversify/lib/resolution/instantiation.js:46:67)
    at /app/node_modules/inversify/lib/resolution/resolver.js:75:42
    at Array.map (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

To reproduce: run `werft run github -a with-helm=true`

**Comment by meysholdt** [comment]
duplicate of https://github.com/gitpod-io/gitpod/issues/8829
